<?php

declare(strict_types=1);

namespace Database\Seeders\Book;

use Aquelarre\Core\Framework\Infrastructure\Seed\Seeder;
use Illuminate\Support\Carbon;

class BooksTableSeeder extends Seeder
{
    protected string $table = 'books';

    public function run(): void
    {
        $this->resetTable();
        $this->db->table($this->table)->insert($this->getData());
    }

    protected function getData(): array
    {
        $now = Carbon::now();
        return [
            [
                'name' => 'Aquelarre - Manual Básico Primera Edición',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-038-X',
                'isbn13' => '978-84-7831-038-8',
                'editorial_code' => '1001',
                'published_at' => Carbon::make(var: '1994-11-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Lilith',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-044-4',
                'isbn13' => '978-84-7831-044-9',
                'editorial_code' => '1002',
                'published_at' => Carbon::make(var: '1991-01-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Rerum Demoni',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-065-7',
                'isbn13' => '978-84-7831-065-4',
                'editorial_code' => '1003',
                'published_at' => Carbon::make(var: '1992.02.01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Danza Macabra',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-072-X',
                'isbn13' => '978-84-7831-072-2',
                'editorial_code' => '1004',
                'published_at' => Carbon::make(var: '1992-05-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Rinascita',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-113-0',
                'isbn13' => '978-84-7831-113-2',
                'editorial_code' => '1005',
                'published_at' => Carbon::make(var: '1993-07-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Dracs',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-126-2',
                'isbn13' => '978-84-7831-126-2',
                'editorial_code' => '1006',
                'published_at' => Carbon::make(var: '1994-04-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Rincón',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => '84-7831-141-6',
                'isbn13' => '978-84-7831-141-5',
                'editorial_code' => '1007',
                'published_at' => Carbon::make(var: '1995-03-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Angelicum Natura',
                'type' => 'book',
                'edition' => 1,
                'editorial' => 'JOC Internacional',
                'isbn10' => null,
                'isbn13' => null,
                'editorial_code' => '1009',
                'published_at' => null,
                'url' => null,
                'comment' => 'No publicado',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Aquelarre - La Tentación',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-95649-02-0',
                'isbn13' => '978-84-95649-02-7',
                'editorial_code' => 'AQU002',
                'published_at' => Carbon::make(var: '2001-04-23'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Mitos y Leyendas vol 0',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-931347-0-8',
                'isbn13' => '978-84-931347-0-9',
                'editorial_code' => 'AQU101',
                'published_at' => Carbon::make(var: '2000-02-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Mitos y Leyendas vol 1 - Ad Intra Mare',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-931347-0-8',
                'isbn13' => '978-84-931347-0-9',
                'editorial_code' => 'AQU102',
                'published_at' => Carbon::make(var: '2000-06-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Mitos y Leyendas vol 2 - Ad Intra Mare',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-931347-4-0',
                'isbn13' => '978-84-931347-4-7',
                'editorial_code' => 'AQU103',
                'published_at' => Carbon::make(var: '2000-07-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Mitos y Leyendas - Ultreya',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-95649-00-4',
                'isbn13' => '978-84-95649-00-3',
                'editorial_code' => 'AQU104',
                'published_at' => Carbon::make(var: '2000-01-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Aker Codex Vol. 1 – Jentilen Lurra',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-931347-1-6',
                'isbn13' => '978-84-931347-1-6',
                'editorial_code' => 'AQU201',
                'published_at' => Carbon::make(var: '2000-03-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Aker Codex Vol. 2 – Fogar de Breogan',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Caja de Pandora',
                'isbn10' => '84-931347-5-9',
                'isbn13' => '978-84-931347-5-4',
                'editorial_code' => 'AQU202',
                'published_at' => Carbon::make(var: '2000-10-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'La Fraternitas de la Vera Lucis',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-01-6',
                'isbn13' => '978-84-95949-01-1',
                'editorial_code' => 'AQS001',
                'published_at' => Carbon::make(var: '2001-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'El Tribunal de la Santa Inquisición',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-00-8',
                'isbn13' => '978-84-95949-00-4',
                'editorial_code' => 'AQS002',
                'published_at' => Carbon::make(var: '2001-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'La Danza Macabra y otros relatos',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-11-3',
                'isbn13' => '978-84-95949-11-0',
                'editorial_code' => 'AQS003',
                'published_at' => Carbon::make(var: '2002-01-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Al Andalus',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-13-X',
                'isbn13' => '978-84-95949-13-4',
                'editorial_code' => 'AQS004',
                'published_at' => Carbon::make(var: '2002-04-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Medina Gharnata',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-14-8',
                'isbn13' => '978-84-95949-14-1',
                'editorial_code' => 'AQS005',
                'published_at' => Carbon::make(var: '2002-04-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'El Brumoso Norte Vol. 1 - Jentilen Lurra',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-37-7',
                'isbn13' => '978-84-95949-37-0',
                'editorial_code' => 'AQS007',
                'published_at' => Carbon::make(var: '2002-07-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ars Medica',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-21-0',
                'isbn13' => '978-84-95949-21-0',
                'editorial_code' => 'AQS006',
                'published_at' => Carbon::make(var: '2002-07-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Grimorio',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-38-5',
                'isbn13' => '978-84-95949-38-7',
                'editorial_code' => 'AQS100',
                'published_at' => Carbon::make(var: '2002-08-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'El Brumoso Norte Vol. 2 - Forgar de Breogan',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-52-0',
                'isbn13' => '978-84-95949-52-3',
                'editorial_code' => 'AQS009',
                'published_at' => Carbon::make(var: '2002-10-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Sefarat - Los secretos de la Cábala Judía',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-51-2',
                'isbn13' => '978-84-95949-51-6',
                'editorial_code' => 'AQS008',
                'published_at' => Carbon::make(var: '2002-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ad Intra Mare 2 Edicion',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-56-3',
                'isbn13' => '978-84-95949-56-1',
                'editorial_code' => 'AQS010',
                'published_at' => Carbon::make(var: '2002-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Aquelarre Apócrifo',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-57-1',
                'isbn13' => '978-84-95949-57-8',
                'editorial_code' => 'AQS101',
                'published_at' => Carbon::make(var: '2002-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ars Magna, el libro secreto de los alquimistas',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-65-2',
                'isbn13' => '978-84-95949-65-3',
                'editorial_code' => 'AQS014',
                'published_at' => Carbon::make(var: '2003-02-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ars Carmina, el libro secreto de los juglares',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-60-1',
                'isbn13' => '978-84-95949-60-8',
                'editorial_code' => 'AQU012',
                'published_at' => Carbon::make(var: '2003-03-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Descriptio Cordubae',
                'type' => 'book',
                'edition' => 2,
                'editorial' => 'Cron',
                'isbn10' => '84-95949-70-9',
                'isbn13' => '978-84-95949-70-7',
                'editorial_code' => 'AQU013',
                'published_at' => Carbon::make(var: '2003-04-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Aquelarre Tercera Edición',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-937200-7-0',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2011-04-18'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Asturies Medievalia',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-940709-0-7',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2012-11-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Saeptum Arbitri',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => null,
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2012-12-01'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ars Malefica',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-941320-5-6',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2013-09-03'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Legendarium Inferni',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-941940-6-1',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2014-04-12'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Daemonolatreia',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-943243-6-9',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2015-02-25'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Bestiarium Hispaniae',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-944352-3-2',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2015-10-28'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Decameron',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-16780-35-8',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2016-12-19'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Retorno a Rincón',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-16780-55-6',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2017-05-18'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Ex Mundo Tenebrarum',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-16780-98-3',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2018-02-15'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'name' => 'Liber Nobilium',
                'type' => 'book',
                'edition' => 3,
                'editorial' => 'NoSoloRol',
                'isbn10' => null,
                'isbn13' => '978-84-17775-53-7',
                'editorial_code' => null,
                'published_at' => Carbon::make(var: '2019-11-14'),
                'url' => null,
                'comment' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ];
    }
}
