<?php

declare(strict_types=1);

namespace Database\Seeders\Commerce;

use Aquelarre\Commerce\Domain\Dto\DBSeed\Price;
use Aquelarre\Commerce\Infrastructure\Seed\Loader\ItemsLoader;
use Aquelarre\Core\Framework\Infrastructure\Seed\Seeder;

class PricesSeeder extends Seeder
{
    public function run(): bool
    {
        return $this->db->table('prices')->insert(array_map(
            fn (Price $price) => $price->toArray(),
            $this->getData()
        ));
    }

    protected function getData(): array
    {
        $items = $this->getLoadedLoader(ItemsLoader::class);

        return [
            Price::ofItem($items->getIdByName('alfanje'))->amount(108),
            Price::ofItem($items->getIdByName('almarada'))->amount(3),
            Price::ofItem($items->getIdByName('arbalesta'))->amount(216),
            Price::ofItem($items->getIdByName('archa'))->amount(36),
            Price::ofItem($items->getIdByName('arco corto'))->amount(36),
            Price::ofItem($items->getIdByName('arco largo'))->amount(58),
            Price::ofItem($items->getIdByName('arco recurvado'))->amount(72),
            Price::ofItem($items->getIdByName('ballesta'))->amount(136),
            Price::ofItem($items->getIdByName('ballesta ligera'))->amount(108),
            Price::ofItem($items->getIdByName('baston de combate'))->amount(2),
            Price::ofItem($items->getIdByName('bordon'))->amount(3),
            Price::ofItem($items->getIdByName('bracamante'))->amount(68),
            Price::ofItem($items->getIdByName('cayado'))->amount(3),
            Price::ofItem($items->getIdByName('clava'))->amount(2),
            Price::ofItem($items->getIdByName('coltell'))->amount(10),
            Price::ofItem($items->getIdByName('dabus'))->amount(6),
            Price::ofItem($items->getIdByName('daga'))->amount(12),
            Price::ofItem($items->getIdByName('espada bastarda'))->amount(85),
            Price::ofItem($items->getIdByName('espada corta'))->amount(51),
            Price::ofItem($items->getIdByName('espada de mano'))->amount(68),
            Price::ofItem($items->getIdByName('estilete'))->amount(12),
            Price::ofItem($items->getIdByName('estoque'))->amount(51),
            Price::ofItem($items->getIdByName('gumia'))->amount(12),
            Price::ofItem($items->getIdByName('hacha de armas'))->amount(6),
            Price::ofItem($items->getIdByName('hacha de combate'))->amount(27),
            Price::ofItem($items->getIdByName('hacha de petos'))->amount(36),
            Price::ofItem($items->getIdByName('honda'))->amount(1),
            Price::ofItem($items->getIdByName('horquilla'))->amount(36),
            Price::ofItem($items->getIdByName('jineta nashri'))->amount(360),
            Price::ofItem($items->getIdByName('lanza corta'))->amount(6),
            Price::ofItem($items->getIdByName('lanza de caballeria'))->amount(10),
            Price::ofItem($items->getIdByName('lanza larga'))->amount(12),
            Price::ofItem($items->getIdByName('mangual'))->amount(216),
            Price::ofItem($items->getIdByName('martillo de guerra'))->amount(51),
            Price::ofItem($items->getIdByName('mayal de armas'))->amount(72),
            Price::ofItem($items->getIdByName('maza'))->amount(7),
            Price::ofItem($items->getIdByName('maza de armas'))->amount(10),
            Price::ofItem($items->getIdByName('maza pesada'))->amount(14),
            Price::ofItem($items->getIdByName('montante'))->amount(108),
            Price::ofItem($items->getIdByName('morosa'))->amount(18),
            Price::ofItem($items->getIdByName('nimcha'))->amount(68),
            Price::ofItem($items->getIdByName('pico de cuervo'))->amount(72),
            Price::ofItem($items->getIdByName('saif'))->amount(68),
            Price::ofItem($items->getIdByName('takuba'))->amount(68),
            Price::ofItem($items->getIdByName('telek'))->amount(14),
            Price::ofItem($items->getIdByName('terciado'))->amount(18),
            Price::ofItem($items->getIdByName('tripa'))->amount(2),
            // ARMORS
            Price::ofItem($items->getIdByName('arnes'))->amount(2700),
            Price::ofItem($items->getIdByName('bacinete'))->amount(108),
            Price::ofItem($items->getIdByName('brazales'))->amount(48),
            Price::ofItem($items->getIdByName('capacete'))->amount(36),
            Price::ofItem($items->getIdByName('celada'))->amount(180),
            Price::ofItem($items->getIdByName('coracina'))->amount(432),
            Price::ofItem($items->getIdByName('coraza corta'))->amount(648),
            Price::ofItem($items->getIdByName('cota de placas'))->amount(1620),
            Price::ofItem($items->getIdByName('gambeson'))->amount(288),
            Price::ofItem($items->getIdByName('gambeson reforzado'))->amount(432),
            Price::ofItem($items->getIdByName('gorro de cuero'))->amount(18),
            Price::ofItem($items->getIdByName('grebas de cuero'))->amount(48),
            Price::ofItem($items->getIdByName('grebas de metal'))->amount(142),
            Price::ofItem($items->getIdByName('loriga de malla'))->amount(900),
            Price::ofItem($items->getIdByName('pelliza de piel'))->amount(108),
            Price::ofItem($items->getIdByName('ropas gruesas'))->amount(216),
            Price::ofItem($items->getIdByName('velmez'))->amount(288),
            Price::ofItem($items->getIdByName('yelmo'))->amount(252),
            // SHIELDS
            Price::ofItem($items->getIdByName('adarga'))->amount(24),
            Price::ofItem($items->getIdByName('broquel'))->amount(12),
            Price::ofItem($items->getIdByName('escudo de madera'))->amount(24),
            Price::ofItem($items->getIdByName('escudo de metal'))->amount(48),
            Price::ofItem($items->getIdByName('paves'))->amount(72),
            Price::ofItem($items->getIdByName('rodela'))->amount(18),
            Price::ofItem($items->getIdByName('tarja'))->amount(102),
            // POISONS
            Price::ofItem($items->getIdByName('aconito'))->amount(12)->description('Coste de una onza de acónito'),
            Price::ofItem($items->getIdByName('adormidera'))->amount(6)->description('Coste de una onza de adormidera'),
            Price::ofItem($items->getIdByName('albayalde'))->amount(1)->dineros()->description('Coste de una onza de albayalde'),
            Price::ofItem($items->getIdByName('arsenico'))->amount(6)->dineros()->description('Coste de una onza de arsénico'),
            Price::ofItem($items->getIdByName('beleno'))->amount(2)->dineros()->description('Coste de una onza de beleño'),
            Price::ofItem($items->getIdByName('cantaridas'))->amount(11)->description('Coste de una onza de cantáridas'),
            Price::ofItem($items->getIdByName('cicuta'))->amount(6)->dineros()->description('Coste de una onza de cicuta'),
            Price::ofItem($items->getIdByName('escorpion'))->amount(4)->dineros()->description('Coste de una onza de veneno de escorpión'),
            Price::ofItem($items->getIdByName('mandragora'))->amount(1)->description('Coste de una onza de mandrágora'),
            Price::ofItem($items->getIdByName('sardonia'))->amount(10)->dineros()->description('Coste de una onza de sardonia'),
            Price::ofItem($items->getIdByName('setas venenosas'))->amount(8)->dineros()->description('Coste de una onza de setas venenosas'),
            Price::ofItem($items->getIdByName('vivora'))->amount(9)->dineros()->description('Coste de una onza de veneno de víbora'),
            Price::ofItem($items->getIdByName('zaragatona'))->amount(5)->dineros()->description('Coste de una onza de zaragatona'),
            // FOODS
            Price::ofItem($items->getIdByName('acemita'))->amount(8)->dineros(),
            Price::ofItem($items->getIdByName('al cuzcuz'))->amount(15)->dineros(),
            Price::ofItem($items->getIdByName('asado de carnero'))->amount(3),
            Price::ofItem($items->getIdByName('ave de caza en espeton'))->amount(7),
            Price::ofItem($items->getIdByName('bocados de manjar blanco'))->amount(8)->dineros(),
            Price::ofItem($items->getIdByName('bolsillos de aman'))->amount(3),
            Price::ofItem($items->getIdByName('carne hojaldrada'))->amount(2),
            Price::ofItem($items->getIdByName('cecina'))->amount(1),
            Price::ofItem($items->getIdByName('empanada de menudillos'))->amount(8)->dineros(),
            Price::ofItem($items->getIdByName('gachas'))->amount(6)->dineros(),
            Price::ofItem($items->getIdByName('haraveulas'))->amount(2),
            Price::ofItem($items->getIdByName('harisa'))->amount(1),
            Price::ofItem($items->getIdByName('huevos jaminados'))->amount(5)->dineros(),
            Price::ofItem($items->getIdByName('huevos pasados por agua'))->amount(8)->dineros(),
            Price::ofItem($items->getIdByName('idish'))->amount(4),
            Price::ofItem($items->getIdByName('lechon asado'))->amount(30),
            Price::ofItem($items->getIdByName('manteca'))->amount(15)->dineros(),
            Price::ofItem($items->getIdByName('migas'))->amount(5)->dineros(),
            Price::ofItem($items->getIdByName('mondongos'))->amount(1),
            Price::ofItem($items->getIdByName('pan'))->amount(4)->dineros(),
            Price::ofItem($items->getIdByName('pan trenzado'))->amount(5)->dineros(),
            Price::ofItem($items->getIdByName('pescado en salazon'))->amount(2),
            Price::ofItem($items->getIdByName('potaje'))->amount(2),
            Price::ofItem($items->getIdByName('queso de cabra'))->amount(1),
            Price::ofItem($items->getIdByName('sopa de ajo y pan'))->amount(5)->dineros(),
            Price::ofItem($items->getIdByName('torrenzo'))->amount(2)->dineros(),
            Price::ofItem($items->getIdByName('avena para caballo'))->amount(3),
            Price::ofItem($items->getIdByName('bizcocho de viaje'))->amount(10),
            Price::ofItem($items->getIdByName('raciones de viaje'))->amount(15),
            Price::ofItem($items->getIdByName('jarra de leche'))->amount(4)->dineros(),
            Price::ofItem($items->getIdByName('jarra de agua de ajenjos'))->amount(5)->dineros(),
            Price::ofItem($items->getIdByName('jarra de aguapie'))->amount(2)->dineros(),
            Price::ofItem($items->getIdByName('jarra de rubb'))->amount(2)->dineros(),
            Price::ofItem($items->getIdByName('jarra de vino'))->amount(3)->dineros(),
            Price::ofItem($items->getIdByName('jarra de sidra'))->amount(3)->dineros(),
            Price::ofItem($items->getIdByName('jarra de hipocras'))->amount(4)->dineros(),
            Price::ofItem($items->getIdByName('jarra de aguardiente'))->amount(6)->dineros(),
            Price::ofItem($items->getIdByName('jarra de jamguri'))->amount(5)->dineros(),
            // CLOTHES
            Price::ofItem($items->getIdByName('ropa humilde de hombre'))->amount(60),
            Price::ofItem($items->getIdByName('ropa humilde de mujer'))->amount(108),
            Price::ofItem($items->getIdByName('ropa humilde de nino'))->amount(36),
            Price::ofItem($items->getIdByName('ropa elegante de hombre'))->amount(576),
            Price::ofItem($items->getIdByName('ropa elegante de mujer'))->amount(1008),
            Price::ofItem($items->getIdByName('ropa elegante de nino'))->amount(360),
            Price::ofItem($items->getIdByName('ropa lujosa de hombre'))->amount(1188),
            Price::ofItem($items->getIdByName('ropa lujosa de mujer'))->amount(2052),
            Price::ofItem($items->getIdByName('ropa lujosa de nino'))->amount(900),
            Price::ofItem($items->getIdByName('sotana habito humildes'))->amount(68),
            Price::ofItem($items->getIdByName('sotana habito elegantes'))->amount(384),
            Price::ofItem($items->getIdByName('sotana habito lujosos'))->amount(1008),
            Price::ofItem($items->getIdByName('chilaba hebrea humilde'))->amount(60),
            Price::ofItem($items->getIdByName('chilaba hebrea elegante'))->amount(576),
            Price::ofItem($items->getIdByName('caftan humilde'))->amount(60),
            Price::ofItem($items->getIdByName('caftan elegante'))->amount(576),
            Price::ofItem($items->getIdByName('caftan lujoso tiraz'))->amount(1188),
            Price::ofItem($items->getIdByName('alfombra de oracion'))->amount(54),
            Price::ofItem($items->getIdByName('aljuba'))->amount(36),
            Price::ofItem($items->getIdByName('alpargatas'))->amount(3),
            Price::ofItem($items->getIdByName('balandran'))->amount(120),
            Price::ofItem($items->getIdByName('bolsillo'))->amount(2),
            Price::ofItem($items->getIdByName('borceguies con banda'))->amount(35),
            Price::ofItem($items->getIdByName('botas de camino'))->amount(50),
            Price::ofItem($items->getIdByName('calzas'))->amount(68),
            Price::ofItem($items->getIdByName('capa de pano pardo'))->amount(60),
            Price::ofItem($items->getIdByName('capirote de vestir'))->amount(12),
            Price::ofItem($items->getIdByName('chapines'))->amount(6),
            Price::ofItem($items->getIdByName('guantes de carnero'))->amount(21),
            Price::ofItem($items->getIdByName('guantes de cetreria'))->amount(42),
            Price::ofItem($items->getIdByName('jubon'))->amount(68),
            Price::ofItem($items->getIdByName('morral'))->amount(30),
            Price::ofItem($items->getIdByName('saya'))->amount(20),
            Price::ofItem($items->getIdByName('sobreveste'))->amount(216),
            Price::ofItem($items->getIdByName('talit'))->amount(24),
            Price::ofItem($items->getIdByName('zapatos doblados'))->amount(15),
            Price::ofItem($items->getIdByName('zurron'))->amount(30),
            // TRANSPORTS
            Price::ofItem($items->getIdByName('asno'))->amount(180),
            Price::ofItem($items->getIdByName('caballo de tiro'))->amount(720),
            Price::ofItem($items->getIdByName('caballo de monta'))->amount(3000),
            Price::ofItem($items->getIdByName('corcel'))->amount(7200),
            Price::ofItem($items->getIdByName('jamelgo'))->amount(360),
            Price::ofItem($items->getIdByName('mula'))->amount(648),
            Price::ofItem($items->getIdByName('potro'))->amount(900),
            Price::ofItem($items->getIdByName('espuelas'))->amount(10),
            Price::ofItem($items->getIdByName('gualdrapa'))->amount(72),
            Price::ofItem($items->getIdByName('herraduras'))->amount(6),
            Price::ofItem($items->getIdByName('carro normal'))->amount(720),
            Price::ofItem($items->getIdByName('carruaje pequeno'))->amount(2160),
            Price::ofItem($items->getIdByName('carruaje grande'))->amount(14400),
            Price::ofItem($items->getIdByName('barca'))->amount(1800),
            Price::ofItem($items->getIdByName('carraca'))->amount(16200),
            Price::ofItem($items->getIdByName('coca'))->amount(1800),
            Price::ofItem($items->getIdByName('fusta'))->amount(5400),
            Price::ofItem($items->getIdByName('galeaza'))->amount(86400),
            Price::ofItem($items->getIdByName('galeota'))->amount(9000),
            Price::ofItem($items->getIdByName('galera'))->amount(61200),
            Price::ofItem($items->getIdByName('saeta'))->amount(27000),
            // GOODS
            Price::ofItem($items->getIdByName('buey'))->amount(432),
            Price::ofItem($items->getIdByName('cabra'))->amount(24),
            Price::ofItem($items->getIdByName('cabrito'))->amount(6),
            Price::ofItem($items->getIdByName('capon'))->amount(4),
            Price::ofItem($items->getIdByName('carnero'))->amount(36),
            Price::ofItem($items->getIdByName('cerdo'))->amount(48),
            Price::ofItem($items->getIdByName('conejo'))->amount(1),
            Price::ofItem($items->getIdByName('gallina'))->amount(2),
            Price::ofItem($items->getIdByName('gallo'))->amount(5),
            Price::ofItem($items->getIdByName('ganso'))->amount(8),
            Price::ofItem($items->getIdByName('gato'))->amount(2),
            Price::ofItem($items->getIdByName('gerifalte nebli'))->amount(300),
            Price::ofItem($items->getIdByName('oveja'))->amount(24),
            Price::ofItem($items->getIdByName('paloma'))->amount(5),
            Price::ofItem($items->getIdByName('perdiz'))->amount(1),
            Price::ofItem($items->getIdByName('perro'))->amount(5),
            Price::ofItem($items->getIdByName('perro de caza'))->amount(27),
            Price::ofItem($items->getIdByName('pollo'))->amount(1),
            Price::ofItem($items->getIdByName('ternera'))->amount(36),
            Price::ofItem($items->getIdByName('toro'))->amount(720),
            Price::ofItem($items->getIdByName('vaca'))->amount(445),
            Price::ofItem($items->getIdByName('algodon'))->amount(9000),
            Price::ofItem($items->getIdByName('cera'))->amount(7200),
            Price::ofItem($items->getIdByName('cuero'))->amount(250),
            Price::ofItem($items->getIdByName('especias'))->amount(36000),
            Price::ofItem($items->getIdByName('hierro'))->amount(1080),
            Price::ofItem($items->getIdByName('lana'))->amount(1980),
            Price::ofItem($items->getIdByName('lena'))->amount(16),
            Price::ofItem($items->getIdByName('lino'))->amount(6800),
            Price::ofItem($items->getIdByName('madera'))->amount(24),
            Price::ofItem($items->getIdByName('piedra'))->amount(24),
            Price::ofItem($items->getIdByName('sebo'))->amount(2088),
            Price::ofItem($items->getIdByName('seda'))->amount(100000),
            Price::ofItem($items->getIdByName('trigo'))->amount(480),
            Price::ofItem($items->getIdByName('vino'))->amount(160),
            Price::ofItem($items->getIdByName('aceituni'))->amount(3150),
            Price::ofItem($items->getIdByName('bervi'))->amount(1350),
            Price::ofItem($items->getIdByName('brocado'))->amount(23400),
            Price::ofItem($items->getIdByName('contray'))->amount(1050),
            Price::ofItem($items->getIdByName('damasco'))->amount(4200),
            Price::ofItem($items->getIdByName('de londres'))->amount(6750),
            Price::ofItem($items->getIdByName('fustan'))->amount(300),
            Price::ofItem($items->getIdByName('lienzo'))->amount(125),
            Price::ofItem($items->getIdByName('pardillo'))->amount(525),
            Price::ofItem($items->getIdByName('pardo'))->amount(425),
            Price::ofItem($items->getIdByName('sanjuanes'))->amount(1050),
            Price::ofItem($items->getIdByName('tercenel'))->amount(5250),
            Price::ofItem($items->getIdByName('velarte'))->amount(2700),
            // POSSESSIONS
            Price::ofItem($items->getIdByName('cabana'))->amount(345),
            Price::ofItem($items->getIdByName('granja'))->amount(3600),
            Price::ofItem($items->getIdByName('casa sencila'))->amount(3600),
            Price::ofItem($items->getIdByName('casa normal'))->amount(27000),
            Price::ofItem($items->getIdByName('casa lujosa'))->amount(72000),
            Price::ofItem($items->getIdByName('torre fortificada'))->amount(45000),
            Price::ofItem($items->getIdByName('castillo pequeno'))->amount(225000),
            Price::ofItem($items->getIdByName('castillo grande'))->amount(3600000),
            Price::ofItem($items->getIdByName('noria de sangre'))->amount(27000),
            Price::ofItem($items->getIdByName('puente de madera'))->amount(150000),
            Price::ofItem($items->getIdByName('puente de piedra'))->amount(1200000),
            Price::ofItem($items->getIdByName('tierras de pastos'))->amount(17),
            Price::ofItem($items->getIdByName('tierras de cultivo'))->amount(36),
            Price::ofItem($items->getIdByName('huertos'))->amount(72),
            Price::ofItem($items->getIdByName('vinedos'))->amount(144),
            // SERVICES
            Price::ofItem($items->getIdByName('alojamiento trabajando'))->amount(0),
            Price::ofItem($items->getIdByName('alojamiento medio'))->amount(6),
            Price::ofItem($items->getIdByName('alojamiento completo'))->amount(10),
            Price::ofItem($items->getIdByName('habitacion privada'))->amount(12),
            Price::ofItem($items->getIdByName('habitacion privada completa'))->amount(18),
            Price::ofItem($items->getIdByName('establo'))->amount(10),
            Price::ofItem($items->getIdByName('armero metal'))->amount(10),
            Price::ofItem($items->getIdByName('armero cuero'))->amount(5),
            Price::ofItem($items->getIdByName('barbero'))->amount(3),
            Price::ofItem($items->getIdByName('barquero'))->amount(1),
            Price::ofItem($items->getIdByName('bufon'))->amount(8),
            Price::ofItem($items->getIdByName('carretero'))->amount(2),
            Price::ofItem($items->getIdByName('criado'))->amount(36),
            Price::ofItem($items->getIdByName('curandero'))->amount(6),
            Price::ofItem($items->getIdByName('entierro'))->amount(9),
            Price::ofItem($items->getIdByName('esclavo'))->amount(300),
            Price::ofItem($items->getIdByName('entregar una carta'))->amount(5),
            Price::ofItem($items->getIdByName('escriba'))->amount(2),
            Price::ofItem($items->getIdByName('guia'))->amount(5),
            Price::ofItem($items->getIdByName('hombre de armas'))->amount(144),
            Price::ofItem($items->getIdByName('maestro'))->amount(10),
            Price::ofItem($items->getIdByName('medico'))->amount(36),
            Price::ofItem($items->getIdByName('misas'))->amount(5),
            Price::ofItem($items->getIdByName('partera'))->amount(3),
            Price::ofItem($items->getIdByName('peon'))->amount(2),
            Price::ofItem($items->getIdByName('prostituta de clase baja'))->amount(15),
            Price::ofItem($items->getIdByName('prostituta de clase alta'))->amount(120),
            Price::ofItem($items->getIdByName('soldado bisono'))->amount(36),
            Price::ofItem($items->getIdByName('soldado experto'))->amount(72),
            // ITEMS
            Price::ofItem($items->getIdByName('aceite de candil'))->amount(1),
            Price::ofItem($items->getIdByName('agujas'))->amount(1),
            Price::ofItem($items->getIdByName('albardas'))->amount(10),
            Price::ofItem($items->getIdByName('alforjas'))->amount(7),
            Price::ofItem($items->getIdByName('aljaba'))->amount(12),
            Price::ofItem($items->getIdByName('anteojos'))->amount(20),
            Price::ofItem($items->getIdByName('antorchas'))->amount(3),
            Price::ofItem($items->getIdByName('aparejo basico'))->amount(108),
            Price::ofItem($items->getIdByName('aparejo de lujo'))->amount(720),
            Price::ofItem($items->getIdByName('arcon'))->amount(75),
            Price::ofItem($items->getIdByName('baraja de naipes'))->amount(2),
            Price::ofItem($items->getIdByName('bardas'))->amount(6840),
            Price::ofItem($items->getIdByName('bardas de vaqueta'))->amount(810),
            Price::ofItem($items->getIdByName('bota de vino'))->amount(1),
            Price::ofItem($items->getIdByName('bacia'))->amount(12),
            Price::ofItem($items->getIdByName('caja'))->amount(12),
            Price::ofItem($items->getIdByName('calamo'))->amount(2)->dineros(),
            Price::ofItem($items->getIdByName('caliz'))->amount(18),
            Price::ofItem($items->getIdByName('candil'))->amount(3),
            Price::ofItem($items->getIdByName('candado'))->amount(2),
            Price::ofItem($items->getIdByName('cazo'))->amount(10),
            Price::ofItem($items->getIdByName('cirio'))->amount(2),
            Price::ofItem($items->getIdByName('clavos'))->amount(5),
            Price::ofItem($items->getIdByName('componentes quimicos'))->amount(10),
            Price::ofItem($items->getIdByName('cranequin'))->amount(18),
            Price::ofItem($items->getIdByName('cruz de altar'))->amount(252),
            Price::ofItem($items->getIdByName('crucifijo'))->amount(10),
            Price::ofItem($items->getIdByName('cuchillo'))->amount(3),
            Price::ofItem($items->getIdByName('cuerda'))->amount(20),
            Price::ofItem($items->getIdByName('devociones'))->amount(6),
            Price::ofItem($items->getIdByName('escalera'))->amount(20),
            Price::ofItem($items->getIdByName('escribania'))->amount(5),
            Price::ofItem($items->getIdByName('esmeril'))->amount(2),
            Price::ofItem($items->getIdByName('espejo'))->amount(13),
            Price::ofItem($items->getIdByName('estera'))->amount(24),
            Price::ofItem($items->getIdByName('flauta'))->amount(1),
            Price::ofItem($items->getIdByName('flechas'))->amount(3),
            Price::ofItem($items->getIdByName('ganzuas'))->amount(36),
            Price::ofItem($items->getIdByName('garfio'))->amount(10),
            Price::ofItem($items->getIdByName('hacha'))->amount(2),
            Price::ofItem($items->getIdByName('hisopo'))->amount(9),
            Price::ofItem($items->getIdByName('incensario'))->amount(18),
            Price::ofItem($items->getIdByName('instrumentos de alquimista'))->amount(360),
            Price::ofItem($items->getIdByName('instrumentos de peso y medida'))->amount(48),
            Price::ofItem($items->getIdByName('laud'))->amount(20),
            Price::ofItem($items->getIdByName('libro de horas'))->amount(15),
            Price::ofItem($items->getIdByName('libro sagrado guarnecido'))->amount(3600),
            Price::ofItem($items->getIdByName('libro en blanco'))->amount(3),
            Price::ofItem($items->getIdByName('lienzos'))->amount(5),
            Price::ofItem($items->getIdByName('navaja de barbero'))->amount(3),
            Price::ofItem($items->getIdByName('maletas de vaqueta'))->amount(12),
            Price::ofItem($items->getIdByName('manta'))->amount(36),
            Price::ofItem($items->getIdByName('martillo'))->amount(10),
            Price::ofItem($items->getIdByName('menorah'))->amount(18),
            Price::ofItem($items->getIdByName('odre'))->amount(10),
            Price::ofItem($items->getIdByName('pala'))->amount(8),
            Price::ofItem($items->getIdByName('pergaminos'))->amount(6),
            Price::ofItem($items->getIdByName('pico'))->amount(12),
            Price::ofItem($items->getIdByName('portacartas'))->amount(6),
            Price::ofItem($items->getIdByName('pretina para daga'))->amount(15),
            Price::ofItem($items->getIdByName('pretina para espada'))->amount(34),
            Price::ofItem($items->getIdByName('rejuelas de tener lumbre'))->amount(12),
            Price::ofItem($items->getIdByName('reloj de arena'))->amount(36),
            Price::ofItem($items->getIdByName('retablo'))->amount(150),
            Price::ofItem($items->getIdByName('romana'))->amount(36),
            Price::ofItem($items->getIdByName('saco'))->amount(6),
            Price::ofItem($items->getIdByName('tenazas'))->amount(6),
            Price::ofItem($items->getIdByName('tenacillas de barbero'))->amount(2),
            Price::ofItem($items->getIdByName('tijeras'))->amount(9),
            Price::ofItem($items->getIdByName('tinta'))->amount(1),
            Price::ofItem($items->getIdByName('virotes'))->amount(6),
            Price::ofItem($items->getIdByName('yesquero'))->amount(6),
            Price::ofItem($items->getIdByName('zaque'))->amount(4),
            // JEWELRY
            Price::ofItem($items->getIdByName('anillo de oro con joyas'))->amount(3000),
            Price::ofItem($items->getIdByName('anillo de oro'))->amount(1800),
            Price::ofItem($items->getIdByName('anillo de plata'))->amount(900),
            Price::ofItem($items->getIdByName('anillo de bronce'))->amount(360),
            Price::ofItem($items->getIdByName('sortija de oro con joyas'))->amount(3000),
            Price::ofItem($items->getIdByName('sortija de oro'))->amount(1800),
            Price::ofItem($items->getIdByName('sortija de plata'))->amount(900),
            Price::ofItem($items->getIdByName('sortija de bronce'))->amount(360),
            Price::ofItem($items->getIdByName('sello de oro'))->amount(1800),
            Price::ofItem($items->getIdByName('sello de plata'))->amount(900),
            Price::ofItem($items->getIdByName('sello de bronce'))->amount(360),
            Price::ofItem($items->getIdByName('alianza de oro con joyas'))->amount(3000),
            Price::ofItem($items->getIdByName('alianza de oro'))->amount(1800),
            Price::ofItem($items->getIdByName('alianza de plata'))->amount(900),
            Price::ofItem($items->getIdByName('collar de oro con joyas'))->amount(10000),
            Price::ofItem($items->getIdByName('collar de oro'))->amount(6000),
            Price::ofItem($items->getIdByName('collar de plata'))->amount(3000),
            Price::ofItem($items->getIdByName('collar de bronce'))->amount(1200),
            Price::ofItem($items->getIdByName('diadema de oro con joyas'))->amount(10000),
            Price::ofItem($items->getIdByName('diadema de oro'))->amount(6000),
            Price::ofItem($items->getIdByName('diadema de plata'))->amount(3000),
            Price::ofItem($items->getIdByName('brazalete de oro con joyas'))->amount(7000),
            Price::ofItem($items->getIdByName('brazalete de oro'))->amount(4200),
            Price::ofItem($items->getIdByName('brazalete de plata'))->amount(2100),
            Price::ofItem($items->getIdByName('brazalete de bronce'))->amount(800),
            Price::ofItem($items->getIdByName('pulsera de oro con joyas'))->amount(5000),
            Price::ofItem($items->getIdByName('pulsera de oro'))->amount(3000),
            Price::ofItem($items->getIdByName('pulsera de plata'))->amount(1500),
            Price::ofItem($items->getIdByName('pulsera de bronce'))->amount(600),
        ];
    }
}
