<?php

declare(strict_types=1);

namespace Database\Seeders\Core\Rituals;

use Aquelarre\Core\Framework\Infrastructure\Seed\Loaders\Book\BookLoader;
use Aquelarre\Core\Framework\Infrastructure\Seed\Seeder;
use Aquelarre\Core\Rituals\Domain\Dto\RitualFluent;
use Aquelarre\Core\Shared\Domain\Support\Str;
use Illuminate\Support\Collection;

class RitualSeeder extends Seeder
{
    protected string $table = 'rituals';

    public function run(): bool
    {
        $this->db->table(table: $this->table)->insert($this->getData());
        return true;
    }

    public function getData(): array
    {
        /** @var BookLoader $books */
        $books = $this->getLoadedLoader(class: BookLoader::class);

        return collect(value: [
            'first',
            'second',
            'third',
            'fourth',
            'fifth',
            'sixth',
        ])->map(
            callback: static fn (string $name): string => (string)Str::of($name)->ucfirst()
                ->prepend('get')
                ->append('Ordo')
        )->reduce(
            callback: fn (Collection $rituals, string $method): Collection => $rituals->merge($this->$method()),
            initial: new Collection()
        )->map(
            callback: static fn (RitualFluent $fluent): RitualFluent => $fluent->book($books->aq3Ed())
        )->toArray();
    }

    private function getFirstOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Absolución')->latin('Absolutio')
                ->ceremony('El sacerdote debe escuchar al pecador —que debe acudir de forma voluntaria y verdaderamente arrepentido (si no es así, el ritual falla automáticamente)—, que hará una relación de los pecados cometidos. En algunos momentos especiales, como antes de una batalla, es posible que un sacerdote lleve a cabo una absolución general: para ello es necesario que durante el tiempo que dure la ceremonia, todos los que participen de la absolución (incluyendo al sacerdote) recen con devoción. Si alguno de los que lo hace pierde ese estado de concentración, el ritual también fallará de forma automática. Para los musulmanes, la absolución es mucho más rápida, ya que sólo requiere que el sacerdote y el pecador recen juntos varias rakas (estrofas) del Corán')
                ->duration('Entre 5 minutos y una hora. Los musulmanes no suelen tardar más de un minuto')
                ->effects('Sea cual sea el resultado obtenido en la tirada de activación, al pecador se le perdonarán todos los pecados que haya cometido anteriormente quedando en estado de gracia. Pero, en el caso de que fuera un éxito, el pecador recibirá, además, un bonificadorde +25% para rezar a los santos (véase "Rezando a los Santos", pág. 268). Los personajes sacerdotes (los que pueden realizar rituales de fe) no pueden utilizar la Absolución sobre ellos mismos, sino que la tienen que recibir de otro personaje sacerdote, que le exigirá además la realización de algún tipo de penitencia (véase "Pecados y Penitencias", pág. 264).'),
            RitualFluent::make(name: 'Bautismo')->latin('Baptismus')
                ->ceremony('El receptor del ritual, que debe encontrarse en estado de gracia (si no es así, puede recibir antes una Absolución), debe abjurar previamente, y de forma voluntaria, de su religión anterior, en el caso de que la tuviera, claro —los niños recién nacidos, por ejemplo, no tienen que hacerlo—. Si el ritual lo lleva a cabo un sacerdote cristiano, se vierte sobre el receptor agua bendita —o, en caso de extrema necesidad, se le salpica mediante aspersión—, se le unge con óleos consagrados, al tiempo que se solicita la bendición de la Trinidad sobre la persona bautizada y se le da su nombre en la comunidad. En el judaísmo la ceremonia se denomina berit milá y requiere que el receptor sea circuncidado —en el caso de ser hombre, naturalmente—, tras lo cual se da de beber al nuevo judío una copa de vino (a los niños pequeños se les coloca una gota en los labios). Los musulmanes también practican la circuncisión, pero en su caso obligan al receptor a pronunciar la sachada delante del ulema.')
                ->duration('Aproximadamente una hora.')
                ->effects('Una vez realizado el ritual, tenga éxito o no la tirada, el receptor es aceptado en la comunidad religiosa: escoge un nuevo nombre, pierde su religión anterior, e ingresa en la nueva, donde se convierte (al menos en teoría) en uno más. En el caso de que el receptor estuviera ordenado como sacerdote en su anterior religión, perderá ese puesto y, por tanto, la capacidad de utilizar rituales de fe, ya que ha ingresado como un fiel más, aunque nada impide que con el tiempo sea ordenado sacerdote en su nueva religión. Si la tirada de activación del ritual tuvo éxito, el receptor verá además aumentada su RR en +2D10, ya que la conversión ha traído aires renovadores a su fe y ha iluminado su camino.'),
            RitualFluent::make(name: 'Eucaristía')->latin('Eucharistia')
                ->ceremony('El sacerdote debe oficiar una celebración conforme al rito establecido en su religión: en el mundo cristiano, por ejemplo, los fieles asisten a una misa en la que se llevan a cabo lecturas del Santo Evangelio, se bendice el pan y el vino y los fieles lo toman en comunión. Los judíos entonan oraciones en comunidad (habitualmente durante el sabbat), en la que se recitan salmos, y les dan diferentes nombres según si se realiza por la mañana (chaharit), por la tarde (minhah) o por la noche (maarib). Los musulmanes tienen una oración en comunidad todos los días, aunque es más importante la de los viernes: durante la misma, se reza sobre las alfombrillas de oración, de rodillas y con el rostro hacia la Meca, al tiempo que se recitan azoras del Corán.')
                ->duration('Como mínimo, 30 minutos.')
                ->effects('Este ritual, que al igual que otros rituales sacramentales no necesita que tenga éxito en la tirada de activación, fomenta la unión de la comunidad con su Dios y suele celebrarse diariamente. Claro que en el caso de que el sacerdote obtenga, además, un éxito en la tirada de activación, todos aquellos fieles que hayan rezado con fervor, se encuentren en estado de gracia (y que hubieran comulgado, si eran cristianos) y fallen una tirada de RR, verán aumentada esta característica en +1%. Si entre la congregación que acude a la ceremonia se encuentra algún personaje con capacidad de utilizar rituales de fe, no ganará ningún punto de RR, ya que asistir a la oración diaria, es algo que se espera de ellos y que deben hacer de forma cotidiana si no quieren manchar su alma con el estigma del pecado (véase "Pecados y Penitencias", pág. 264)'),
            RitualFluent::make(name: 'Matrimonio')->latin('Matrimonium')
                ->ceremony('La celebración del matrimonio se lleva a cabo atendiendo a las normas de la religión de los contrayentes (y del sacerdote), a las que habrá que añadir las costumbres de la región, si existen. Para los cristianos lo principal es que los contrayentes expresen ante la comunidad (o al menos ante dos testigos y el sacerdote) su intención de casarse "hasta que la muerte los separe", que lo compartan todo y que la Iglesia los bendiga; para los judíos, la ceremonia es muy similar, también con intercambio de anillos, aunque lo llevan a cabo bajo la jupá (un palio) y al finalizar el novio rompe una copa; en el mundo islámico, no existen tampoco muchas diferencias: presencia de testigos, oraciones, bendiciones y compromisos entre los contrayentes. En todo caso, los contrayentes deben casarse de forma libre y voluntaria —al menos si queremos que el ritual tenga éxito—, tener más de quince años y, naturalmente, estar solteros o viudos (excepto en algunos puntos del mundo islámico, donde es lícito tener más de una esposa, pero no en el reino de Granada)')
                ->duration('Al menos, 30 minutos.')
                ->effects('Una vez realizado el ritual (da igual si tiene éxito o no), los contrayentes se convierten en marido y mujer, y se considera un matrimonio perfectamente válido, tanto a ojos de Dios como de los hombres. En el caso de que el sacerdote obtenga un éxito en la tirada de activación, ambos contrayentes conseguirán, además, un bonificador igual a la RR del sacerdote que los casó para enfrentarse a cualquier efecto de un hechizo o al poder de una criatura que intente romper dicho matrimonio, como las intervenciones de los súcubos o íncubos, los hechizos de Filtro Amoroso, Discordia, etc., al menos hasta que alguno de los dos decida voluntariamente serle infiel al otro, momento en el que desaparecerá dicho modificador'),
            RitualFluent::make(name: 'Ordenación')->latin('Ordenatio')
                ->ceremony('Para llevar a cabo este ritual, el sacerdote debe poseer cierto rango dentro de la jerarquía eclesiástica: si es cristiano, deberá ser al menos un obispo o abad; si es judío, deberá ser al menos un rab (un juez superior nombrado por el rey cuya jurisdicción abarca una judería de cierta importancia o todas las juderías de una región); y si es musulmán, el sacerdote deberá ser al menos cadí (un ulema con prerrogativas de juez en tierras islámicas). Además, debe llevar a cabo la ceremonia asistido por, al menos, otros dos sacerdotes, del rango que sean.
                        Tras ayunar durante veinticuatro horas, el receptor de la ceremonia —que debe poseer al menos 50% en Teología y otro 50% en Racionalidad— debe llegar a la ceremonia en estado de gracia, y durante todo el tiempo que dure la misma, recitará los salmos y las oraciones a coro con el sacerdote, que al finalizar la misma impondrá las manos sobre el receptor.
                        Normalmente, esta ceremonia suele tener lugar en unos días concretos del año; por ejemplo, en el mundo cristiano se acostumbran a llevar a cabo ordenaciones durante las témporas (el miércoles, viernes y sábado de la semana posterior al tercer domingo de Adviento, el primer domingo de Cuaresma, en Pentecostés y el 14 de septiembre, cuando se celebra la Exaltación de la Cruz). Además, es costumbre que la persona que va a recibir la ordenación pase varios años estudiando la teología y las doctrinas de su religión junto a un maestro')
                ->duration('Al menos dos horas de cánticos y rezos.')
                ->effects('Al llevar a cabo el ritual el receptor es ordenado sacerdote de su religión, por lo que a partir de ese momento puede utilizar los rituales de fe, aunque también quedará sujeto a las restricciones a los Puntos de Fe que conllevan los pecados (véase "Pecados y Penitencias", pág. 264). Además, si el sacerdote tiene éxito en la tirada de activación, el receptor aumentará en +2D10 su RR debido a la iluminación que supone la ceremonia.
Recordamos que aunque hablemos de sacerdotes y de ordenación, el receptor deberá pasar por el mismo ritual aunque su futuro sea ser monje, monja, ulema, caballero de orden militar, etc'),
            RitualFluent::make(name: 'Réquiem')->latin('Requiem')
                ->ceremony('El sacerdote oficia el funeral del receptor, que estará, como no, muerto. Para los cristianos eso supone comenzar en la Extremaunción y terminar con la lectura del panegírico delante de su tumba, pasando por el velatorio, el funeral en sí y la procesión hasta el cementerio. Los judíos denominan a este ritual Animut y los musulmanes Takbira.')
                ->duration('Lo habitual es que dure al menos un día entre el fallecimiento y el entierro')
                ->effects('Con este ritual, el sacerdote puede enterrar a un miembro de su congregación siguiendo las normas que imponen la fe y la tradición, por lo que el ánima del fallecido podrá ir al lugar que le corresponda en la Otra Vida (ya sea el Cielo o el Infierno), y no podrá ser convertida en un ánima errante o en un espectro similar. Además, si la tirada de activación tiene éxito y se intenta utilizar el cuerpo del fallecido para llevar a cabo algún tipo de hechizo, ritual mágico o invocación, éste tendrá un penalizador igual a la RR del sacerdote que ofició el ritual de fe'),
        ])
            ->map(callback: fn (RitualFluent $fluent): RitualFluent => $fluent->ordo(1));
    }

    private function getSecondOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Alivio de Enfermedades')->latin('Lenimen Morborum')
                ->ceremony('El sacerdote deberá acompañar al enfermo durante todo un día, y animarlo a rezar junto a él, siempre y cuando la enfermedad del receptor se lo permita —o que quiera hacerlo, ya que si no desea rezar, el ritual fallará automáticamente—. Una vez pasado ese tiempo, el sacerdote impondrá sus manos sobre el cuerpo del enfermo, normalmente sobre su cabeza')
                ->duration('24 horas')
                ->effects('Si se activa correctamente el ritual, se conseguirá aliviar parcialmente la enfermedad del receptor, reduciendo en un grado la convalecencia de su enfermedad (véanse las reglas de enfermedades en la pág. 103): si era máxima, pasará a normal; si era normal, a mínima y, si era mínima, desaparecerá por completo. También es posible combinar el ritual con una tirada de Medicina, lo que permitiría al enfermo reducir su nivel de convalecencia en dos grados. En caso de obtener un crítico en la tirada de activación, el enfermo reduciría en dos grados su enfermedad, pero si fuera una pifia, el sacerdote se contagiaría de la enfermedad del receptor.
Este ritual no puede utilizarse sobre enfermedades incurables, como la lepra o la peste. En esos casos sólo se puede utilizar el ritual Curación Milagrosa (pág. 263)'),
            RitualFluent::make(name: 'Bendición')->latin('Benedictio')
                ->ceremony('Durante treinta minutos, el sacerdote realiza un ritual con el que invoca la bendición de Dios sobre el objeto. Los cristianos acostumbran a llevarlo a cabo rezando y haciendo repetidamente el signo de la cruz sobre el objeto, mientras que los musulmanes escriben y graban una azora del Corán (normalmente las "azoras protectoras", la CXIII o la CXXXIV) en el objeto, de manera similar a como lo hacen los judíos con el Antiguo Testamento')
                ->duration('Al menos treinta minutos')
                ->effects('Si se tiene éxito en la tirada de activación del ritual, el sacerdote conseguirá bendecir un objeto concreto, aunque los efectos serán diferentes según el tipo de objeto que haya sido bendecido. A continuación te presentamos algunos ejemplos, aunque el DJ es libre de permitir a sus jugadores que bendigan otro tipo de objetos:
                <ul>
                <li>Arma: Un arma bendita puede herir a las criaturas malvadas que, de otro modo, serían invulnerables al daño físico, como las sombras o el demonio menor Camos, por poner un par de ejemplos, y aunque no anularán en ningún caso la posible armadura mágica que puedan tener, sí que atraviesan completamente sus auras de protección.</li>
                <li>Agua: Con el ritual es posible bendecir como máximo el contenido de una redoma de agua mezclada con sal que puede utilizarse para llevar a cabo rituales de fe que lo requieran o para derramarla sobre una criatura malvada (previa tirada de Lanzar, claro). Si se utiliza de esta forma, el agua le causará 1D8+1 PD, y aunque respetará la posible armadura que lleve, ya sea mágica o no, atravesará completamente el aura de protección que tenga (si es que la tiene). Ya que los judíos y musulmanes deben escribir sobre el objeto bendecido no pueden utilizar agua; ellos usan, en cambio, papeles sobre los que escriben y que luego pueden usar sobre criaturas malvadas</li>
                <li>Símbolo Religioso: Si el sacerdote bendice un símbolo religioso, obtendrá un bonificador en los rituales de Confrontación y Exorcismo. Además, si toca a una criatura malvada le provocará una quemadura de 1D6 PD.</li>
                <li>Otros Objetos (por ejemplo, comida, un estandarte, etc.): Causará una quemadura de 1D6 PD sobre toda criatura malvada a la que toque directamente sobre la piel, ignorando cualquier aura de protección que tenga, o también podrá atemorizar a las criaturas malvadas que lo vean.</li>
                </ul>
                El tiempo exacto que dura una bendición es variable, y normalmente se reduce a la escena o combate29 para el que se creara, ya que para realizar una bendición permanente es necesario utilizar el ritual Bendición Perpetua. Además, recomendamos a los jugadores que no abusen del uso de este ritual, ya que las bendiciones no son chocolatinas, y repartirlas a diestro y siniestro puede sentarle mal al que está allí arriba...'),
            RitualFluent::make(name: 'Confrontación')->latin('Collatio')
                ->ceremony('Este ritual sólo puede utilizarse para enfrentarse a una criatura de origen malvado. Para llevarlo a cabo, el sacerdote exhortará mediante palabras y gestos a la criatura a que abandone el lugar, aferrando en sus manos un objeto sagrado de su religión, excepto los sacerdotes musulmanes, que lo único que deben hacer es repetir una y otra vez la sachada, la profesión de fe ("No hay más dios que Allah y Mahoma es su enviado")')
                ->duration('Varios asaltos, según la exhortación')
                ->effects('Si se realiza con éxito, el sacerdote utilizará la fuerza de su fe para tratar de expulsar a la criatura del lugar donde se encuentra. Para saber si tiene éxito en la expulsión, el sacerdote comparará su RR con la IRR de la criatura en la Tabla de Confrontación, modificando ambas características con los siguientes modificadores:
                <ul>
                <li>Si el sacerdote obtiene un éxito crítico en la activación del ritual: multiplica x2 su RR.</li>
                <li>Si el sacerdote ha alcanzado la santidad: multiplica x2 su RR.</li>
                <li>Si la Confrontación tiene lugar en un lugar sagrado (una iglesia, una catedral, un cementerio, un lugar afectado por el ritual de Sacralización, etc.): +25 a la RR del sacerdote.</li>
                <li>Si la Confrontación se realiza en un lugar maldito (una Puerta al Infierno, un lugar de celebración de aquelarres, etc.): +25 a la IRR de la criatura.</li>
                <li>Si el objeto que esgrime el sacerdote ha sido bendecido (véase Bendición): +20 a la RR del sacerdote.</li>
                <li>Si el sacerdote se encuentra en estado de gracia: +10 a la RR del sacerdote.</li>
                <li>Por cada voto privado que haya hecho el sacerdote (véase "Votos y Promesas", pág. 267): +5 a la RR del sacerdote.</li>
                </ul>
                Los posibles ataques que lleve a cabo la criatura seguirán las reglas habituales que aparecen en el capítulo de combate, aunque siempre obtendrán una Iniciativa mayor que la del sacerdote. Además, el Director de Juego deberá amoldar los resultados obtenidos en la tabla con las características concretas del enfrentamiento: por ejemplo, si el sacerdote intenta expulsar a un espíritu maligno, éste no podrá atacarle físicamente, diga lo que diga la Tabla de Confrontación'),
            RitualFluent::make(name: 'Don de Sirin')->latin('Donum Sirinis')
                ->ceremony('El sacerdote impone las manos sobre el receptor –que puede ser él mismo— y entona una oración durante diez minutos —normalmente suele ser, al menos en la religión cristiana o judía, el salmo 45, Poema nupcial al rey mesiánico—. Este ritual sólo puede utilizarse sobre un receptor en estado de gracia: si no es así y el ritual tiene éxito, se aplican automáticamente los efectos de la pifia')
                ->duration('Al menos diez minutos')
                ->effects('Si se lleva a cabo correctamente el ritual y se obtiene un éxito critico en la tirada, el sacerdote invoca a Sirin, una de las Aves del Paraíso (véase pág. 317) para que le conceda el don de la belleza y de la felicidad: en términos de juego, el Aspecto, la Suerte y las competencias de Comunicación del receptor (Elocuencia, Seducción, Mando, Comerciar, etc.) se verán incrementadas en un 50% (por ejemplo, si tiene un ASP de 14 ahora tendrá 21: 21 + 7, que es el 50% de 14). Si el éxito obtenido no es crítico, sino normal, no conseguirá nada, ya que Sirin sólo premia a los que demuestran de verdad su valía.
                Claro que en el caso de obtener una pifia, el Ave del Paraíso que acudirá será la gemela de Sirin, Alkanost, cuyo don es el dolor y la muerte: tanto el receptor como el sacerdote deberán hacer una tirada de Resistencia x5 y, si la fallan, morirán entre dolores terribles y su alma se convertirá en un ánima errante. Si tienen éxito, sólo perderán el 50% de los PV que tengan en el momento de recibir el don de Alkanost. Como puedes ver, es necesario pensárselo dos veces antes de invocar el don de Sirin. Debe quedar claro que en ningún momento se presentarán físicamente ninguna de las dos Aves del Paraíso: sólo enviarán sus dones al receptor y nada más'),
            RitualFluent::make(name: 'Pentecostés')->latin('Pentecoste')
                ->ceremony('Para llevar a cabo este ritual el sacerdote debe estar completamente purificado, tanto por dentro como por fuera: debe estar en estado de gracia, haber comido sólo pan y agua durante la última semana y estar limpio (entendámonos: con las manos, cara y pies lavados, y con una muda de ropa nueva). Si es así, sólo debe rezar durante treinta minutos para llevar a cabo la ceremonia')
                ->duration('30 minutos')
                ->effects('Si se efectúa correctamente la ceremonia, el sacerdote recibirá la iluminación divina (los cristianos aseguran que es el Espíritu Santo que se les presenta en forma de lengua de fuego, aunque el ritual no tiene efecto visible alguno) y mientras duren sus efectos, entenderá todas las lenguas de la Tierra: tanto las que se utilizan como las que desaparecieron, e incluso las que usan los demonios y los ángeles para hablar entre ellos. Además, todo aquél que escuche al sacerdote entenderá de inmediato lo que éste le dice, pues, a sus oídos, el sacerdote estará hablando su lengua. Por tanto, a efectos de juego, podemos considerar que el sacerdote tiene un porcentaje de 100% en todas las competencias de Idioma, aunque su competencia de Leer y Escribir no se verá afectada, lo que significa que sigue teniendo que hacer una tirada para comprender un texto escrito o para escribirlo. Los efectos del ritual terminarán al escuchar el siguiente canto del gallo, o sea, al amanecer del día siguiente'),
            RitualFluent::make(name: 'Revelación')->latin('Revelatio')
                ->ceremony('Este ritual sólo puede utilizarse si el sacerdote desea obtener información de un demonio —o de alguno de sus seguidores— con el que se esté enfrentando. Para llevar a cabo la ceremonia es necesario que el sacerdote se aísle en un lugar solitario y silencioso (una iglesia, una capilla, la celda de un monasterio, etc.) donde no pueda ser molestado durante al menos 24 horas, tiempo en el que ni beberá ni probará bocado alguno. Terminado dicho tiempo de ayuno y oración, rogará a Dios que le conceda sabiduría y se retirará a dormir')
                ->duration('24 horas, más el tiempo que pase el sacerdote durmiendo')
                ->effects('Si se activa con éxito el ritual, mientras el sacerdote duerme recibirá procedente del Cielo una revelación en forma de sueño que le ofrecerá algún tipo de información sobre el demonio al que se está enfrentando, o sobre sus sirvientes (debilidades, defectos, hechos pasados o futuros, hechos que están teniendo lugar en otro lugar, etc.). Estas ensoñaciones nunca serán del todo claras (excepto si el sacerdote ha obtenido un éxito crítico), y aparecerán mezcladas con fantasías y sueños del inconsciente del sacerdote, así que una vez despierto es tarea suya discernir lo correcto de lo inventado. En caso de obtener una pifia en la tirada, toda la visión que ha tenido el sacerdote es directamente falsa, por lo que recomendamos que sea el Director de Juego el que haga la tirada para activar este ritual de fe. Además, es un ritual del que no se debe abusar, ya que no suele ser del agrado de la Divinidad verse molestada cada noche con tribulaciones y solicitudes, y suele castigar a los sacerdotes con insomnio y fatiga si intentan molestarla a menudo'),
        ])
            ->map(callback: fn (RitualFluent $fluent): RitualFluent => $fluent->ordo(2));
    }

    public function getThirdOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Exorcismo')->latin('Exorcismus')
                ->ceremony('El sacerdote debe llevar a cabo un largo ritual durante el cual no dejará de rezar ni de exhortar a la criatura que salga del cuerpo del receptor. Durante todo ese tiempo el sacerdote puede recibir la ayuda de hasta siete personas de conducta pura y recta (o sea, que se encuentren en estado de gracia) —no importa si la religión que profesan es la misma que la del sacerdote o no—, que deberán acompañarle en sus oraciones, y que en caso de que el sacerdote gane o pierda RR, también lo harán ellos. Advertimos que los rituales de exorcismo son ceremonias violentas, no aptas para corazones débiles, que pueden exigir alguna que otra tirada de Templanza por parte de los testigos o de los ayudantes del sacerdote. Además, este tipo de ritual suele atraer la atención de las criaturas malvadas que estén en los alrededores, que no dudarán en aparecer durante su celebración para interrumpir el ritual. Por otra parte, según el derecho canónico, sólo aquellos sacerdotes que hayan obtenido antes el permiso del obispo de su diócesis pueden realizar un exorcismo: lo decimos por si el Director de Juego quiere ponerle las cosas un poco más difíciles al PJ')
                ->duration('Al menos cinco horas')
                ->effects('Este ritual, muy parecido al de Confrontación, permite a un sacerdote expulsar —o incluso destruir— a un demonio o criatura malvada que haya poseído un cuerpo. Si la tirada de activación tiene éxito, el sacerdote exorcista deberá comparar su RR con la IRR de la criatura y consultar la Tabla de Exorcismo, aunque tanto la RR como la IRR se verán modificadas previamente con los siguientes modificadores
                <ul>
                <li>Si el exorcista ha alcanzado la santidad: multiplica x2 su RR.</li>
                <li>Si el exorcista ha obtenido un crítico en la tirada de activación del ritual: multiplica x2 su RR.</li>
                <li>Si el Exorcismo tiene lugar en un espacio sagrado (una iglesia, una catedral, un cementerio, un lugar afectado por el ritual de Sacralización, etc.): +10 a la RR del sacerdote.</li>
                <li>Si el Exorcismo se lleva a cabo en un lugar maldito (una Puerta al Infierno, un lugar de celebración de aquelarres, etc.): +10 a la IRR de la criatura.</li>
                <li>Si el exorcista utiliza durante el ritual un objeto que haya sido bendecido (véase Bendición): +10 a la RR del sacerdote.</li>
                <li>Si el exorcista se encuentra en estado de gracia: +10 a la RR del sacerdote.</li>
                <li>Si el exorcista moja al poseído con agua bendita (véase Bendición): +5 a la RR del sacerdote.</li>
                <li>Por cada voto privado que haya hecho el sacerdote (véase "Votos y Promesas", pág. 267): +5 a la RR del sacerdote.</li>
                <li>Por cada persona que ayude al exorcista y que se encuentre en estado de gracia (máximo 7 personas): +5 a la RR del sacerdote.</li>
                <li>Por cada persona que ayuda al exorcista que abandone el ritual antes de que se finalice: +10 a la IRR de la criatura.</li>
                </ul>
                Consulta los métodos de posesión que tiene la criatura que está siendo expulsada en el apartado correspondiente del capítulo del Bestiario. Además, como ya dijimos en el ritual de Confrontación, el Director de Juego deberá amoldar los resultados obtenidos en la tabla a las características concretas del enfrentamiento y de la criatura'),
            RitualFluent::make(name: 'Iluminación')->latin('Illustratio')
                ->ceremony('Un sacerdote sólo puede llevar a cabo este ritual si se encuentra en ese momento intentando acabar con el plan de algún demonio mayor o menor, ya lo esté llevando a cabo él mismo o alguno de sus seguidores (sea humano o criatura irracional). Si es así, el sacerdote sólo tiene que rezar una oración con mucha devoción')
                ->duration('1 asalto')
                ->effects('El sacerdote le pide a Dios que le ilumine el camino para poder enfrentarse al Adversario y a sus seguidores. Si lo activa con éxito, la divinidad dará la orden a uno de los Tronos (véase pág. 311) para que le conceda sabiduría al sacerdote. En términos de juego, el personaje verá como una de sus competencias de Cultura aumenta hasta el 100%. La competencia concreta la elegirá el DJ, aunque deberá ser vital para que el sacerdote pueda derrotar al demonio: Conocimiento Mágico, para reconocer un talismán; Conocimiento Mineral, para localizar una Puerta al Infierno; Idioma, para saber el idioma en que está escrito un libro, etc. Una vez que el personaje haya hecho una única tirada con dicha competencia, el porcentaje volverá a su nivel inicial.
                Este ritual de fe sólo puede utilizarse una vez por aventura aunque, si se falla la tirada, el sacerdote puede volver a repetirla hasta que tenga éxito, o pifie, momento en que el Trono le castigará por importunarles tanto. Por cierto, que el Trono nunca se presentará físicamente delante del sacerdote, sino que le "insuflará" la verdad directamente en la cabeza'),
            RitualFluent::make(name: 'Maldición Divina')->latin('Divinum Maledictum')
                ->ceremony('El sacerdote deberá apuntar con la mano extendida al receptor de la maldición, que ha de ser una criatura malvada, pues no sirve contra simples criaturas irracionales o humanos, por muy malos que sean. Además, el sacerdote tiene que pronunciar la maldición en voz alta y de forma clara, por lo que este ritual no puede utilizarse sin hacer gestos o sin pronunciar palabras en voz alta (véase pág. 246)')
                ->duration('1 asalto')
                ->effects('Si se activa con éxito el ritual y la criatura que lo recibe falla su tirada de IRR, el receptor recibirá una maldición celestial y, a partir de entonces, todo lo que haga le saldrá terriblemente mal. En términos de juego, el receptor verá aumentadas en +10% sus posibilidades de pifia para todas las tiradas que haga (si, por ejemplo, sus posibilidades de pifia para una tirada eran de 96 a 00, ahora serán de 86 a 00). Además, su Suerte se verá reducida a la mitad. Los efectos de la maldición durarán hasta que el receptor pierda de vista al sacerdote'),
            RitualFluent::make(name: 'Oración')->latin('Oratio')
                ->ceremony('El sacerdote, que debe haber perdido RR en las últimas dos horas, debe retirarse a orar y rezar a un lugar tranquilo y sosegado (una iglesia, una capilla, una ermita, la celda de un convento, etc.) durante, al menos, una hora')
                ->duration('1 hora, al menos')
                ->effects('Cuando un sacerdote ha perdido RR por la razón que sea (por contemplar a una criatura irracional, por ver los efectos de un hechizo, etc.) en las últimas dos horas, puede retirarse a orar para limpiar su alma de nuevo utilizando este ritual, que tiene un penalizador adicional de -100% (además de todos los penalizadores habituales en la realización de rituales de fe), pero por cada hora posterior a la primera que pase rezando, este penalizador se verá reducido en un 10%. De esta forma, si el sacerdote se retira a rezar durante tres horas, el penalizador será sólo de -80% (dos horas por encima de la primera, son un 20% en que se reduce el -100%)
                Si se activa correctamente el ritual, su alma se tranquilizará un poco y recuperará algo de la fe perdida (y con suerte puede que toda): recuperará un dado de RR igual al dado que tiró para perderla, con un máximo igual a la RR perdida. Por ejemplo, si la pérdida de RR se debió a la contemplación de una criatura irracional, el sacerdote perdió 1D10 RR, tirará ahora otro 1D10, aunque en ningún momento recuperará más puntos de RR que los que tenía originalmente. Si la pérdida de RR era fija (por ejemplo, perdió 5 puntos de RR por ver un hechizo de vis quinta), el sacerdote hará una tirada de dado cuyo máximo sea la RR perdida (en el ejemplo anterior tirará 1D5).
                Si la tirada de activación es un éxito crítico, el sacerdote recuperará toda la RR perdida. Pero si se trata de una pifia, su fe se verá aún más resentida, y perderá 1D10 puntos de RR adicionales.
                En el caso de que el sacerdote hubiera tenido varias pérdidas de RR en las últimas dos horas (por ejemplo, por contemplar a una criatura irracional y la ejecución de un hechizo al mismo tiempo), él elegirá de cuál de esas pérdidas se quiere recuperar, pero nunca podrá hacerlo de todas a la vez'),
            RitualFluent::make(name: 'Procesión')->latin('Pompa')
                ->ceremony('El sacerdote debe dirigir una procesión de alabanza a Dios por las calles o campos de un pueblo o ciudad y en la que deben participar al menos doscientas personas. Durante todo el trayecto, el sacerdote entonará en todo momento salmos y oraciones de alabanza al Altísimo')
                ->duration('Al menos tres horas')
                ->effects('Si el ritual se lleva a cabo con éxito, el sacerdote conseguirá que Dios le eche una mano al pueblo o a sus habitantes con algún tipo de problema que estén sufriendo. Algunos ejemplos de soluciones pueden ser:
                <ul>
                <li>Si el pueblo sufre los efectos del clima (una sequia, una nevada, etc.), el tiempo irá cambiando gradualmente en los próximos días.</li>
                <li>Si está sufriendo una epidemia, todos los que puedan contagiarse de la enfermedad podrán hacer a partir de ahora dos tiradas de Resistencia para resistirse a ella (consulta las reglas de enfermedades en la pág. 103).</li>
                <li>Si los habitantes van a acudir a una batalla, recibirán una inyección de moral que les puede venir bien (en términos de juego aumenta en uno la calidad de las tropas a las que pertenece el sacerdote y mueve una columna a su favor en la Tabla de Combates, tal y como aparece en las reglas de combates de masas en el Apéndice IV, pág. 526).</li>
                </ul>
                El Director de Juego es libre de decidir los efectos concretos de una procesión basándose en las circunstancias concretas en que se llevara a cabo. Este ritual sólo puede utilizarse una vez cada mes (de tiempo de juego), se tenga éxito o no en la tirada de activación'),
            RitualFluent::make(name: 'Purga')->latin('Purgatio')
                ->ceremony('El sacerdote reza una breve oración ante una comida o bebida')
                ->duration('1 asalto')
                ->effects('Con este ritual el sacerdote bendice los alimentos que va a ingerir él mismo o alguno de los presentes y elimina de ellos las impurezas que pudieran tener, como enfermedades o venenos, por lo que, si se utiliza con éxito, la bebida o comida quedará completamente purgada y desaparecerá de ella todos los efectos nocivos que pudiera tener, aunque la tirada de activación tendrá un penalizador adicional según el tipo de impureza que contenga, tal y como se puede ver a continuación:
                <ul><li>Bebida o alimento con algún tipo de laxante, somnífero, tranquilizante, etc.: -5% al porcentaje.</li>
                <li>Bebida o alimento en mal estado (comida pasada, agua de una charca estancada, etc.): -10% al porcentaje.</li>
                <li>Bebida o alimento contaminados por una enfermedad (cólera, mal de San Antón…): -20% al porcentaje.</li>
                <li>Bebida o alimento envenenados: -30% al porcentaje.</li></ul>
                Este penalizador se añade a los penalizadores habituales por utilizar un ritual de fe. Además, por muy buena tirada que obtenga el sacerdote, no se puede hacer comestible ninguna comida o bebida que no lo sea de forma habitual (por ejemplo, una roca seguiría siendo incomestible, igual que un tazón de lava ardiendo)'),
            RitualFluent::make(name: 'Purificación')->latin('Purificatio')
                ->ceremony('El sacerdote lleva a cabo un ritual en el que impregna de agua bendita y sal (o de oraciones cúficas, en caso de los musulmanes) el lugar que desea purificar, al tiempo que pronuncia diversos salmos y oraciones. Durante la ceremonia puede ser ayudado por hasta siete personas que estén en estado de gracia (da igual la religión a la que pertenezcan), que tampoco podrán dejar de rezar durante todo el tiempo que dure la ceremonia.
                Este ritual, al igual que ocurre con Exorcismo, suele atraer la atención de las criaturas malvadas que se encuentren en los alrededores, que intentarán interrumpir de la forma que sea la ceremonia del ritual. Además, también se trata de un ritual que exige, según la normativa eclesiástica, el permiso de un obispo o superior para poder llevarlo a cabo (el Director de Juego decidirá si es o no necesario para que el sacerdote lo realice)')
                ->duration('Al menos cinco horas')
                ->effects('Con este ritual, muy parecido al de Exorcismo, el sacerdote puede limpiar la mancha del demonio de una localización, ya sea una casa, una caverna, un claro o incluso una iglesia que haya sido mancillada. Si se lleva a cabo correctamente, el lugar quedará de nuevo inmaculado a ojos de Dios, al menos hasta que vuelva a ser ensuciado por la presencia del Maligno (para evitarlo se puede utilizar el ritual de Sacralización, que se explica más adelante).
                El ritual de Purificación se lleva a cabo sin medias tintas: o se tiene éxito o no. El sacerdote podrá limpiar una zona, pero no puede limpiarla a medias. Para comprobar si se consigue, una vez activado correctamente el ritual, el sacerdote deberá comparar su RR con la IRR del lugar (consulta los ejemplos de lugares más abajo), que será mayor cuanto mayor sea la profanación: si el sacerdote tiene una RR mayor, el lugar quedará purificado.
                <ul><li>Infierno: IRR de 500.</li>
                <li>Guarida de Lucifer: IRR de 400.</li>
                <li>Guarida de un Demonio Mayor: IRR de 300.</li>
                <li>Guarida de un Demonio Menor: IRR de 200.</li>
                <li>Entrada al Infierno: IRR de 200.</li>
                <li>Lugar de celebración de un hechizo de Gran Aquelarre: IRR 150.</li>
                <li>Lugar de celebración de un hechizo de Aquelarre o Misa Negra: IRR 125.</li>
                <li>Lugar de celebración de un hechizo de Invocar Demonios Elementales: IRR 110.</li>
                <li>Laboratorio o guarida de un poderoso Mago Goético: IRR 100.</li>
                <li>Guarida de un Engendro Infernal o de un Demonio Elemental: IRR 100.</li>
                <li>Iglesia o Camposanto mancillado: IRR 80.</li>
                <li>Campo de batalla especialmente sangriento: IRR 60.</li></ul>
                De todas formas, el sacerdote puede ver aumentada o disminuida su RR con base en los siguientes modificadores:
                <ul><li>El sacerdote ha obtenido un éxito crítico en la activación del ritual: multiplica x2 su RR.</li>
                <li>El sacerdote ha alcanzado la santidad: multiplica x2 su RR.</li>
                <li>El sacerdote utiliza un objeto sagrado que haya sido bendecido (véase Bendición): +10 a su RR.</li>
                <li>El sacerdote se encuentra en estado de gracia: +10 a su RR.</li>
                <li>Por cada persona que ayude al sacerdote en el ritual: +5 a su RR (máximo, siete personas).</li>
                <li>Por cada voto privado que tenga el sacerdote: +5 a su RR.</li>
                <li>Por cada persona, de las que le acompañan, que deje de rezar antes de acabar la ceremonia: -10 a su RR.</li></ul>'),
        ])
            ->map(callback: fn (RitualFluent $fluent): RitualFluent => $fluent->ordo(3));
    }

    public function getFourthOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Ángel de la Guarda')->latin('Angelus Custodiae')
                ->ceremony('El sacerdote sólo puede utilizar este hechizo cuando se encuentre en peligro mortal o esté en una situación al borde de la muerte (aunque no sea consciente de ello). Además, sólo puede utilizarse si se encuentra en estado de gracia')
                ->duration('Instantánea')
                ->effects('Si el sacerdote activa correctamente este ritual, delante del sacerdote y visible únicamente a sus ojos se aparecerá su ángel de la guarda (véase pág. 313), que tratará de ayudarle en la medida de sus posibilidades para evitar la muerte que ronda al sacerdote, ya sea curándolo, avisándole de algún peligro físico o proporcionándole una pista que le permita salvar la vida por su cuenta. El ángel nunca luchará ni provocará daño alguno a otra criatura (por muy demoníaca que sea) y su ayuda no será tampoco definitiva: por ejemplo, no curará al PJ de todos los PV perdidos, sólo los justos para que él pueda continuar su misión. En manos del Director de Juego queda el alcance exacto de esa ayuda basándose en las circunstancias exactas.
                La invocación a un ángel de la guarda no es un asunto baladí, así que recomendamos que no se pueda utilizar este ritual más de una vez por aventura. Y recordamos además el requisito de encontrarse en estado de gracia, lo que significa que cualquier pequeño desliz o pecadillo cometido por el sacerdote a lo largo de la aventura invalidará completamente el ritual'),
            RitualFluent::make(name: 'Bendición Perpetua')->latin('Aeterna Benedictio')
                ->ceremony('Se trata de una ceremonia muy parecida a la de Bendición, pero debe prolongarse durante todo un día y toda una noche, tiempo en el que el sacerdote no parará de rezar y de invocar la bendición de Dios sobre el objeto. Los cristianos acostumbran a llevarlo a cabo rezando y haciendo repetidamente el signo de la cruz sobre el objeto, mientras que los musulmanes escriben y graban una azora del Corán (normalmente las "azoras protectoras", la CXIII o la CXXXIV) en el objeto, de manera similar a como lo hacen los judíos con el Antiguo Testamento')
                ->duration('24 horas')
                ->effects('Los efectos de este ritual son iguales a los de Bendición, pero el objeto quedará bendecido de forma permanente (hasta que se utilice, en el caso del agua, o se rompa). Además, el ritual de Bendición Perpetua exige una gran fuerza de voluntad por parte del sacerdote, lo que impide que un sacerdote lleve a cabo este ritual sobre más de un objeto al mismo tiempo: si, por ejemplo, se ha utilizado Bendición Perpetua sobre un arma, hasta que ésta no sea destruida no podrá volver a utilizarse el ritual sobre otro objeto (ya sea un arma u otra cosa). Y antes de que se te pase por la cabeza la idea de romper tú mismo el objeto, te recordamos que Dios ve con muy malos ojos a todos aquéllos que se dedican a destruir objetos benditos. De todas formas, nada impide que el sacerdote utilice los rituales de Bendición normales'),
            RitualFluent::make(name: 'Disipación')->latin('Dissipatio')
                ->ceremony('El sacerdote debe tocar con sus manos el objeto o persona que haya sido objeto de un hechizo (si no es posible, debe estar lo más cerca posible del lugar donde tienen lugar los efectos del hechizo) y rezar con ferviente empeño durante un minuto')
                ->duration('Un minuto (cinco asaltos aproximadamente)')
                ->effects('Con este ritual, el sacerdote puede disipar un hechizo, anulando los efectos de todos aquellos hechizos que tengan una duración temporal. Una vez activado el ritual con éxito, el sacerdote deberá hacer una tirada de RR con una penalización igual al de la vis del hechizo (por ejemplo, -35% si es vis tertia, -100% si es vis sexta, etc.), tirada en la que no podrá gastar puntos de Suerte: si tiene éxito en esa tirada, el hechizo habrá sido destruido y sus efectos desaparecerán por completo. En caso de que esa tirada fuera una pifia, el hechizo pasaría a afectar también al sacerdote'),
            RitualFluent::make(name: 'El Brazo de Dios')->latin('Bracchium Dei')
                ->ceremony('Para poder utilizar este ritual el sacerdote debe estar en estado de gracia y sólo podrá recurrir a él si se enfrenta a algún demonio mayor o a alguno de sus servidores, ya sean demonios menores, elementales o engendros del Infierno (este enfrentamiento no tiene por qué desembocar en un combate, sino en el hecho de que el sacerdote está intentando destruir los trabajos de alguno de estos demonios o de sus seguidores). La ceremonia se reduce a una súplica por parte del sacerdote para solicitar la ayuda de un arcángel determinado')
                ->duration('1 asalto')
                ->effects('Si se realiza correctamente el ritual, el sacerdote invocará la ayuda de los arcángeles, que le otorgarán un don, según el tipo de arcángel que haya sido invocado. En el caso de que el sacerdote utilice el ritual mientras se enfrenta directamente a un demonio mayor, en lugar de otorgarle un don, el arcángel hará acto de presencia para combatir él mismo al demonio, y todos los asistentes al prodigio ganarán automáticamente 1D10 puntos de RR.
                El arcángel al que el sacerdote se encomienda durante el ritual variará según el demonio o la criatura a la que se enfrente, y cada uno de ellos otorgará dones diferentes:
                <ul>
                <li>Anael: Actuará si el sacerdote se enfrenta a Silcharde o a sus sirvientes (Bael, Ondinas, etc.). Salvará de la muerte a todo aquél que intente ayudar a la persona que se enfrenta al demonio (ya sea el sacerdote o algún amigo de esa persona).</li>
                <li>Cassiel: Actuará para enfrentarse a Guland o a sus sirvientes (Andrialfo, Silfos, etc.). Curará automáticamente al sacerdote o a alguno de sus compañeros.</li>
                <li>Gabriel: Actuará para enfrentarse a Masabakes o a sus sirvientes (Lilith, íncubos, súcubos, etc.). Proporciona al sacerdote derecho a realizar una segunda tirada de RR contra hechizos o puede enviar un aviso a los compañeros del sacerdote para que le ayuden.</li>
                <li>Miguel: Actuará para enfrentarse a Belzebuth, Astaroth y todos los demonios menores. Regenerará los puntos de Suerte del sacerdote hasta su total inicial y, en ocasiones (si se obtiene un crítico en la tirada de activación del ritual), los doblará durante todo el tiempo que dure el enfrentamiento con los demonios.</li>
                <li>Rafael: Actuará para enfrentarse a Frimost y a sus sirvientes (Haborimo, ígneos, etc.). Calmará los ánimos de todos los participantes en la contienda y apaciguará las dispuestas.</li>
                <li>Sachiel:Actuará para enfrentarse a Surgat y a sus sirvientes (Anazareth, gnomos, etc.). Si el sacerdote ha demostrado ser una persona generosa o altruista, le otorgará las riquezas suficientes para facilitarle la tarea.</li>
                <li>Samael: Actuará para enfrentarse a Agaliaretph o a sus sirvientes (Beherito, Abigor, sombras, meigas, etc.). Da fuerzas a los que combaten en una guerra santa o envía miembros de la hueste angélica (la jauría de Dios, hayyoth, malache habbalah, criaturas de Abbadon o un ángel castigador) para ayudar al sacerdote: el DJ determinará exactamente la criatura que llega en representación de Samael.</li>
                </ul>
                Los sacerdotes musulmanes sólo reconocen a dos de estos arcángeles, a Gabriel (al que llaman Jibrail) y a Miguel (que denominan Mijail) y, por tanto, no podrán invocar la ayuda de los demás arcángeles, aunque en su lugar pueden recabar la ayuda de dos criaturas divinas, el ababil y el burak, que pueden ser invocados cuando se enfrente a algún demonio que no esté cubierto por Gabriel o Miguel:
                <ul>
                <li>Ababil: Ayudará al sacerdote en una batalla.</li>
                <li>Burak: Trasladará al sacerdote rápidamente a otro lugar.</li>
                </ul>
                Tenga éxito o no la invocación, sólo es posible utilizar este ritual una sola vez por sesión de juego'),
            RitualFluent::make(name: 'Excomunión')->latin('Anathema')
                ->ceremony('Para llevar a cabo este ritual (que los judíos denominan Cherem), el sacerdote debe poseer cierto rango dentro de la jerarquía eclesiástica: si es cristiano, debe ser al menos obispo o abad; si es judío, un rab; y si es musulmán, un cadí. Además, tendrá que estar acompañado durante toda la ceremonia por otros dos sacerdotes de su misma religión (no importa el rango que tengan), que actuarán como testigos.
                Durante la ceremonia, el sacerdote debe increpar al receptor, utilizando oraciones y salmos, al tiempo que le despoja de sus ropajes. No es necesario que el receptor acuda voluntariamente a la ceremonia (vamos, que se le puede llevar preso), pero son condiciones fundamentales que pertenezca a la misma religión que el sacerdote, que tenga menos puntos de RR que el sacerdote y que haya cometido algún tipo de pecado dentro de su religión, por pequeño que sea (aunque recordamos que la desobediencia a la Iglesia y a sus ministros ya se considera pecado), ya que si no es así, el ritual fallará automáticamente')
                ->duration('Dos horas al menos')
                ->effects('Con este ritual se puede expulsar a un creyente del seno de la Iglesia que profesa. Si se lleva a cabo la ceremonia correctamente, el receptor deberá hacer una tirada de RR con un penalizador igual a la RR del sacerdote: si falla, se le considera automáticamente excomulgado. A partir de ahora no podrá utilizar rituales de fe (se considera que ha perdido todos sus Puntos de Fe) ni rezar a los santos (falla automáticamente las tiradas). En el caso de que el personaje excomulgado sea algún tipo de gobernante (rey, señor feudal, etc.), se le retirará su derecho divino a gobernar a sus vasallos, que a partir de ahora se pueden considerar hombres libres (al menos en teoría, que la práctica puede ser muy diferente). Además, mientras sea una persona sin religión (en resumen, hasta que se retire la excomunión o sea "bautizado" en otra religión), se le considerará a todos los efectos como una criatura malvada y, por tanto, se verá afectado por los rituales de fe lanzados sobre él. Cualquier sacerdote (en el sentido de PJ que puede utilizar rituales de fe) que se encuentre a un excomulgado, se dará cuenta automáticamente de ello haciendo una simple tirada de RR.
                Los efectos de la Excomunión pueden durar toda la vida, hasta que el sacerdote que lo excomulgó (u otro con un rango superior dentro de la jerarquía eclesiástica) retire la excomunión llevando a cabo una ceremonia de la misma duración o el receptor se acoja a otra religión utilizando sobre él el ritual de Bautismo'),
            RitualFluent::make(name: 'Éxtasis Divino')->latin('Divinum Exstasis')
                ->ceremony('El sacerdote deberá ayunar al menos durante un día entero, tiempo que pasará aislado en un lugar lo más solitario y silencioso posible (una iglesia, una capilla, la celda de un monasterio, el desierto, el monte, etc.), ayunando, rezando y leyendo las Escrituras. Cuando crea que ha llegado el momento, sólo tendrá que levantar las manos, cerrar los ojos y solicitar humildemente contemplar el rostro del Altísimo')
                ->duration('Al menos 24 horas, pero puede extenderse mucho más')
                ->effects('on este ritual, el sacerdote podrá llegar a vislumbrar brevemente el rostro de Dios y su omnipotencia divina. Para conseguirlo deberá tener éxito en la tirada de activación del ritual que contará con un penalizador adicional de -75% (además de los posibles penalizadores que tienen todos los rituales): este penalizador especial se puede reducir en un 5% por cada día por encima del primero que el personaje pase ayunando. Por ejemplo, si pasase un total de diez días ayunando, el penalizador quedaría reducido a tan sólo -30%, ya que serían nueve días por encima del primero (que no cuenta para esa reducción), lo que daría un total de 9x5=45%, que se le descontaría al -75%. Durante todo el tiempo que dure el ayuno el sacerdote sufrirá los efectos del hambre (véase pág. 108), así que deberá tener cuidado para no morir de inanición.
                Si la tirada tiene finalmente éxito, el sacerdote quedará embargado por un éxtasis de una intensidad increíble, al mismo tiempo que una paz interior inconmensurable se asienta en su alma. En términos de juego, su RR aumentará en +1D10 puntos, su Suerte Actual volverá al nivel de la Suerte Inicial (si la había perdido), no se verá afectado durante toda una semana por todos aquellos rasgos de carácter o vergüenzas que afecten a su personalidad (si así lo desea), recuperará todos los Puntos de Fe que haya perdido por pecados (véase "Pecados y Penitencias", pág. 264) y los Puntos de Aprendizaje que gaste al final de la aventura para aumentar las competencias de Cultura valdrán el doble (pero sólo para competencias basadas en Cultura).
                Claro que existen todavía un par de cosas que no se han dicho de este ritual. En el caso de que el sacerdote obtenga un crítico en la tirada de activación, su cuerpo se verá envuelto por una luz brillante y levitará unos metros del suelo, haciendo que todos los presentes queden maravillados por el milagro (y ganando 1D10 puntos de RR), además de absortos durante los minutos que dura tal portento. Por el contrario, si el sacerdote obtiene una pifia, será el Diablo el que meterá el rabo en el asunto y lo que podrá ver el personaje serán los ardientes campos del Infierno, lo que le obligará a hacer una tirada de IRR: si falla, ganará 2D10 puntos de IRR.
                Este ritual es uno de los más poderosos que existen, pero habrá de utilizarse con cuidado: se sabe de sacerdotes que se han quedado completamente ciegos por intentar utilizar este ritual con demasiado frecuencia, ya que contemplar el rostro de Dios no es algo que soporten unos ojos mortales'),
            RitualFluent::make(name: 'Instrumento Divino')->latin('Divinum Instrumentum')
                ->ceremony('Este ritual sólo puede llevarse a cabo en una ciudad que posea al menos 5.000 habitantes y que corra algún tipo de peligro: una batalla inminente, algún desastre climático, una epidemia, tumultos, un asedio, etc. El sacerdote debe pasar orando al menos veinticuatro horas en la catedral o en la iglesia principal de la ciudad. Luego abandonará el templo y predicará a las gentes en la principal plaza de la ciudad (que suele estar junto a la catedral), convenciéndoles con una tirada de Elocuencia o Mando de que deben tener fe en Dios y en sus enviados, ganándoselos de esa forma para la causa')
                ->duration('24 horas más el tiempo que dure la predicación')
                ->effects('Si se lleva a cabo correctamente el ritual, el sacerdote se convierte en el recipiente de un Principado (véase pág. 312), uno de los ángeles que tienen por misión custodiar y proteger las ciudades y naciones del mundo. El Principado poseerá el cuerpo del sacerdote, modificando sus características y competencias, proporcionándole, además, inmunidad a la magia y un aura mágica que le protege del daño. Una vez que el peligro haya pasado, o que la ciudad haya sufrido sus consecuencias, el Principado abandonará al sacerdote, que recuperará sus características habituales. Este ritual sólo puede intentarse, como máximo, una vez al año, se tenga éxito o no en la tirada de activación'),
            RitualFluent::make(name: 'La Armadura de Dios')->latin('Armatura Dei')
                ->ceremony('El sacerdote debe aferrarse a un objeto sagrado de su religión y apretarlo contra el pecho, al tiempo que entona una y otra vez una oración o salmo de protección (existen muchos, pero el preferido suele ser el número veintisiete, Confianza en la Prueba). Los sacerdotes islámicos no utilizan objeto sagrado alguno, y sólo tienen que repetir constantemente la sachada')
                ->duration('Variable (la duración la decide el sacerdote)')
                ->effects('Si se activa con éxito el ritual, el sacerdote se vuelve completamente inmune a cualquier tipo de magia negra, ya sea infernal o no, excepto aquellos hechizos lanzados por magos o criaturas irracionales que tengan una IRR superior al doble de la RR del sacerdote. Para que el ritual se mantenga activo, el sacerdote no puede hacer otra cosa más que rezar y moverse a la mitad de su velocidad normal: en el momento en que deje de hacerlo o suelte el objeto, el ritual acabará y el sacerdote volverá a ser vulnerable a los hechizos. Mientras dure el ritual, el cuerpo del sacerdote quedará envuelto en una suave aura luminosa que parece emanar de su interior, un aura que sólo será visible en lugares en penumbra u oscuros.
                Un par de anotaciones: el mago es inmune a los efectos mágicos en sí, pero no a los efectos que un hechizo pueda causar en su alrededor (por ejemplo, no podrá ser dañado directamente con magia, pero si se utiliza la magia para afectar a lo que le rodea, ya sea el suelo, su ropa, su equipo, etc., esto si le afectará normalmente); además, la inmunidad a la magia no evita que pueda ganar IRR si contempla los efectos de un hechizo. Por último, es necesario recordar que este hechizo sólo protege de la magia, pero nada impide que el sacerdote pueda ser atacado por un arma más mundana, como una espada, una flecha o unas garras bien afiladas'),
            RitualFluent::make(name: 'Sacralización')->latin('Sancta Sanctorum')
                ->ceremony('El sacerdote debe llevar a cabo un ritual en el cual salpicará con agua bendita toda la estancia que desee bendecir al tiempo que pronuncia los salmos y oraciones adecuadas. Los sacerdotes musulmanes acostumbran a inscribir en el suelo del centro de la habitación una azora en forma de espiral (el llamado "agujero de demonios") o también pueden sacrificar un animal salvaje en su interior')
                ->duration('Al menos dos horas')
                ->effects('Con este ritual se puede bendecir la estancia de una casa o edificio de manera temporal. Si se lleva a cabo con éxito, se considerará a partir de entonces lugar sagrado, pudiendo oficiar en su interior las oraciones de la religión del sacerdote, además de servir de lugar de recogimiento si el personaje desea retirarse a orar (por ejemplo, para utilizar los rituales de Oración o Revelación). Cualquier sacerdote que intente realizar en su interior un ritual de Confrontación o Exorcismo verá aumentada su RR en +10%. Además, cualquier criatura malvada que tenga una IRR de 150 o menos no podrá penetrar en dicha estancia (en el caso de que se haya trazado un "agujero de demonios" en su interior, la criatura se verá arrastrada por la espiral que la precipitará directamente en el Infierno). Los efectos desaparecerán en cuanto el sacerdote abandone la estancia que ha bendecido.
                Este ritual no puede llevarse a cabo en un lugar que haya sido mancillado por el Demonio o por sus seguidores: si se da el caso, el sacerdote deberá realizar primero un ritual de Purificación y, a continuación, el de Sacralización'),
        ])
            ->map(callback: fn (RitualFluent $fluent): RitualFluent => $fluent->ordo(4));
    }

    public function getFifthOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Ayuda Divina')->latin('Auxilium Dei')
                ->ceremony('El sacerdote debe encontrarse en estado de gracia y enfrentarse directamente a demonios, ya sean mayores, menores o elementales (no puede utilizarse, por tanto, si tiene delante a engendros del Infierno, a otras criaturas irracionales o a oponentes humanos, por muy malvados que sean). Para usarlo, es necesario simplemente invocar la ayuda divina')
                ->duration('1 asalto')
                ->effects('Este ritual es, posiblemente, uno de los más poderosos que puede utilizar un humano que no haya alcanzado la santidad, aunque sigue unas reglas ligeramente distintas al resto. Si la tirada de activación del ritual tiene éxito, el sacerdote recibirá la ayuda directa de la Divinidad, que socorrerá al personaje de una forma espectacular: se abrirán las nubes, los mares se levantarán, las huestes celestiales descenderán desde el Cielo montadas en bestias de furia y justicia, etc. Como comprenderás, los demonios se retirarán a las profundidades del Abismo (aunque los elementales serán fulminados por la ira divina), mientras que todos los asistentes, incluyendo al sacerdote, quedarán petrificados ante la maravilla de la que han sido testigos (los más piadosos puede incluso que se tiren al suelo de rodillas, con lágrimas en los ojos), y todos ganarán automáticamente +1D10 RR.
                Pero en el caso de que falle la tirada, el sacerdote sentirá de primera mano cómo el mismo Dios le ha retirado su apoyo, así que perderá de forma automática todos sus Puntos de Fe (que podrá luego recuperar a base de penitencias, tal y como se indica en la pág. 266), y no podrá volver a utilizar rituales de fe hasta que alcance, como mínimo, la suma de 10 PF. De todas formas, tenga o no éxito, el sacerdote no podrá volver a usar este ritual hasta que no pase al menos un mes desde la última vez que lo intentara.
                Como se puede ver, la Ayuda Divina no es un ritual que pueda realizarse a la ligera, y aunque la ceremonia es simple y rápida, los más sabios recomiendan utilizarlo sólo en la más peligrosa de las situaciones, pues como gustan de recordar, Dios no está para servirnos a nosotros, sino nosotros para servirle a él'),
            RitualFluent::make(name: 'Consagración')->latin('Consecratio')
                ->ceremony('Para realizar este ritual, el receptor del mismo debe estar enfrentándose a un demonio o a alguno de sus sirvientes (o debe estar a punto de hacerlo) y, además, debe encontrarse en estado de gracia. Para llevar a cabo la ceremonia, el sacerdote pondrá sus manos sobre la cabeza del receptor y ambos rezarán las oraciones pertinentes durante, al menos, diez minutos')
                ->duration('10 minutos')
                ->effects('Este ritual es muy parecido a Bendición o Sacralización, pero ahora el sacerdote lo que solicita es que la Divinidad mande su bendición sobre una persona (que en ningún caso puede ser él mismo). Si se lleva a cabo con éxito la ceremonia, el receptor deberá hacer una tirada de RR: si falla, el ritual habrá fallado igualmente. Pero si tiene éxito, el receptor sentirá cómo una paz inconmensurable invade su cuerpo, aumentando en +1D10 su RR. A partir de entonces dejará de sentir el dolor (no podrá caer inconsciente por las heridas y no se verá afectado por ninguno de los penalizadores de las mismas) y será completamente inmune a la enfermedad y al veneno. Además, podrá tirar RR para defenderse de cualquier hechizo que sea lanzado contra él, aunque el hechizo no lo permitiera, y su Templanza se verá multiplicada por dos. El ritual acabará en el momento en el que el sacerdote deje de ver al receptor o cuando éste cometa algún pecado, por pequeño que sea'),
            RitualFluent::make(name: 'Curación Milagrosa')->latin('Mirabilis Sanatio')
                ->ceremony('Para que este ritual pueda llevarse a cabo el sacerdote debe encontrarse en estado de gracia. La ceremonia consiste en tocar a la persona enferma (que también deberá estar en estado de gracia) y rezar junto a él las oraciones pertinentes, solicitando fervientemente que Dios le conceda la curación')
                ->duration('30 minutos al menos')
                ->effects('Con este ritual el sacerdote puede llevar a cabo todo tipo de curaciones milagrosas: restaurará la vista a los ciegos, la capacidad de andar a los paralíticos, curará cualquier tipo de enfermedad (incluso las incurables, como la lepra) o cualquier otro tipo de dolencia de carácter permanente (menos la muerte, claro). Si se lleva a cabo con éxito la ceremonia, el receptor deberá también mostrar la fuerza de su Fe, para lo que realizará una tirada de RR: si es un éxito crítico, se curará instantáneamente (otros resultados no valen, ni siquiera un éxito simple). En esta tirada es imposible utilizar la Suerte. Todos aquéllos que asistan al portento (incluido el enfermo) se maravillarán de lo ocurrido y ganarán +1D10 puntos de RR.
                Recomendamos no utilizar este ritual más de una vez por aventura (se tenga o no éxito al usarlo), ya que al Cielo no le agrada que se vaya por ahí realizando milagros a diestro y siniestro por minucias como una ceguera o una parálisis. Además, si alguna de las tiradas que se lleven a cabo en el ritual (ya sea de la de activación o la de RR del receptor) se obtuviera una pifia, el sacerdote sufriría un castigo similar a la dolencia que estaba intentando curar (se quedaría ciego, paralítico, leproso, etc.)'),
            RitualFluent::make(name: 'Fruto del Edén')->latin('Fructus ex Eden')
                ->ceremony('Para llevar a cabo este ritual, el sacerdote debe estar en estado de gracia. La ceremonia necesaria para activar el ritual es repetir continuamente oraciones de alabanza a Dios')
                ->duration('Al menos un asalto')
                ->effects('Este ritual es uno de los más poderosos con los que puede contar un sacerdote, ya que le permitirá saborear la fruta del árbol de la vida (Génesis 2, 9), lo que ha permitido en el pasado que muchos santos y mártires aguantaran sin problemas el martirio. Si se lleva a cabo correctamente la activación del ritual, mientras el sacerdote continúe repitiendo las oraciones de alabanza será completamente inmune al daño físico, ya sea provocado por armas, fuego, caídas, venenos, magia, etc.: el sacerdote no puede perder ningún Punto de Vida, ni tampoco caer inconsciente, y la tortura no tendrá ningún efecto sobre él. De todas formas, aunque es inmune al daño producido por los hechizos (como el que produce Sangre de Dragón), aquéllos que no provoquen ninguno le afectarán normalmente (como Alma de Estatua, por ejemplo).
                Los efectos del ritual acabarán en el momento en que el sacerdote lleve a cabo alguna acción que no sea recitar las oraciones o andar despacio. Además, si la tirada de activación es una pifia, lo que saboreará será el árbol del Conocimiento, lo que le volverá loco automáticamente'),
            RitualFluent::make(name: 'Sacralización Perpetua')->latin('Sancta Sanctorum Aeterna')
                ->ceremony('Para poder utilizar este ritual sobre un edificio es necesario que el sacerdote tenga el permiso de un superior eclesiástico (por ejemplo, si es un sacerdote cristiano deberá solicitar permiso al obispo de su diócesis), y que haya pasado al menos un mes viviendo en su interior, orando al menos doce horas diarias durante todos los días del mes. Si es así, podrá comenzar la ceremonia del ritual, durante la que entonará alabanzas y salmos al tiempo que salpica todas las habitaciones de la casa con agua bendita y esparce sal por todos sus suelos. Los sacerdotes musulmanes acostumbran a realizar la sacralización inscribiendo azoras en letras cúficas por las paredes y, en ocasiones, por los suelos del edificio')
                ->duration('iez horas por cada cinco varas cuadradas que tenga el edificio')
                ->effects('Este ritual es similar a Sacralización, sólo que sus efectos serán permanentes. Si se lleva a cabo con éxito, el sacerdote deberá hacer una tirada de RR con una penalización igual al ordo del ritual (o sea, con -80%): si lo consigue, habrá sacralizado completamente el edificio. Si no, deberá comenzar la ceremonia de nuevo.
                A partir de ahora el edificio se considera lugar sagrado, y se pueden oficiar en su interior las ceremonias habituales de la religión del sacerdote (misas, oraciones del viernes, etc.), podrá servir de lugar de recogimiento para aquellos personajes sacerdotes que necesiten retirarse para rezar (por ejemplo, para utilizar los rituales de Oración, Revelación, etc.), y si se lleva a cabo en su interior un ritual de Confrontación o Exorcismo, la RR del sacerdote se verá aumentada en +10% para calcular su total. Las criaturas malvadas o demonios que no tengan al menos un 200 en IRR no podrán entrar en el interior del edificio.
                Es imposible sacralizar solamente parte de un edificio: deben bendecirse todas y cada una de sus estancias. Tampoco puede llevarse a cabo dentro de un lugar que haya sido mancillado por el Demonio o por sus seguidores, si no se ha utilizado previamente el ritual de Purificación'),
            RitualFluent::make(name: 'Transfiguración')->latin('Transfiguratio')
                ->ceremony('El sacerdote sólo puede llevar a cabo este ritual si se enfrenta físicamente a un demonio o a alguno de sus sirvientes de manera directa (ambos están en un combate, comparten la misma estancia, etc.). Para realizarlo, el sacerdote debe pasar al menos un minuto orando, con el rostro levantado hacia el cielo, sin llevar a cabo ninguna otra acción')
                ->duration('1 minuto (aproximadamente cinco asaltos)')
                ->effects('Si el sacerdote activa con éxito el ritual, (el sacerdote) se verá rodeado de una luz brillante que durará hasta que lleve a cabo cualquier acción que no sea rezar (atacar, moverse, hablar, etc.). La brillante luz que le rodea cegará a todos los que estén a su alrededor, otorgando un penalizador igual a la RR del sacerdote a todas las tiradas de ataque y defensa que se hagan a menos de diez varas de él. Además, el demonio o el sirviente contra el que se esté enfrentando el sacerdote deberá llevar a cabo una tirada de IRR, a la que se restará la RR del sacerdote (con un -5% adicional por cada voto privado que tenga el sacerdote): si falla, no podrá acercarse a menos de diez varas del sacerdote ni podrá atacarle en forma alguna (ni con armas o hechizos), mientras duren los efectos de la Transfiguración'),
        ])
            ->map(callback: fn (RitualFluent $fluent): RitualFluent => $fluent->ordo(5));
    }

    public function getSixthOrdo(): Collection
    {
        return collect([
            RitualFluent::make(name: 'Milagro')->latin('Miraculum')
                ->ceremony('El único ritual de fe que existe dentro del sextus ordo es el de Milagro, ya que una vez llegados a este punto, el poder de la Divinidad se transmite casi directamente a sus sirvientes. Y tanto es así que este ritual sólo puede ser utilizado por aquellos personajes que hayan alcanzado la santidad (véase la pág. 242) o aquellas criaturas celestiales que pertenezcan a la Triada Superior o que sean arcángeles')
                ->duration('Variable')
                ->ordo(6)
                ->effects('El efecto concreto del ritual es tan variado como los diferentes tipos de milagro que existen, pero en todo caso se trata de portentos de la naturaleza que nunca pasarán desapercibidos y que obligarán a todos los que contemplen el milagro a aumentar su RR en 1D10 puntos. Algunos ejemplos de milagros famosos pueden ser los siguientes, aunque el Director de Juego es libre de utilizar este ritual para otros fines de similares características:
                <ul>
                <li>Resucitar a una persona muerta.</li>
                <li>Provocar todo tipo de plagas, desde las típicas enfermedades hasta las de animales (langostas, tábanos, etc.).</li>
                <li>Hacer llover azufre y fuego.</li>
                <li>Un relámpago que fulmina a un enemigo (provocándole la muerte en el acto).</li>
                <li>Convertir a una persona en una estatua de sal.</li>
                <li>Convertir todo el agua de la zona en sangre.</li>
                <li>Dividir las aguas.</li>
                <li>Crear una gran columna de fuego que se abate desde el Cielo sobre los enemigos.</li>
                <li>Hacer llover maná desde el cielo.</li>
                <li>Permitir que una persona ascienda al Cielo (o descienda al Infierno) sin necesidad de morir.</li>
                </ul>
                Además, al tratarse de rituales de tan magno poder, la posibilidad de que ocurran no puede dejarse en manos del azar, y sólo tendrán lugar cuando así lo disponga el Altísimo (en términos de juego, cuando lo decida el Director de Juego). Recomendamos, de todas formas, que el DJ no haga un uso excesivo de los milagros en juego, ya que se trata de fenómenos de una enorme trascendencia que tienen lugar cada varios siglos, y que incluso los arcángeles utilizan como último recurso: un milagro debe ser milagroso, no el pan nuestro de cada día...'),
        ]);
    }
}
