<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Rituals\Application;

use App\Game\Core\Features\Rituals\Application\Pages\ListRituals;
use App\Game\Core\Features\Rituals\Application\Schemas\RitualInfolist;
use App\Game\Core\Features\Rituals\Application\Tables\RitualTable;
use App\Game\Core\Features\Rituals\Infrastructure\Models\Ritual;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class RitualResource extends Resource
{
    protected static ?string $model = Ritual::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return RitualTable::admin($table);
    }

    public static function infolist(Schema $schema): Schema
    {
        return RitualInfolist::admin($schema);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListRituals::route('/'),
            'view' => Pages\ViewRitual::route('/{record}')
        ];
    }
}
