<?php

declare(strict_types=1);

namespace Database\Seeders\Core\Competences;

use Aquelarre\Core\Framework\Infrastructure\Seed\Loaders\Book\BookLoader;
use Aquelarre\Core\Framework\Infrastructure\Seed\Loaders\Characteristic\CharacteristicsLoader;
use Aquelarre\Core\Framework\Infrastructure\Seed\Seeder;

class CompetenceSeeder extends Seeder
{
    public string $table = 'competences';

    public function run(): void
    {
        $this->db->table(table: $this->table)->insert(values: $this->getData());
    }

    public function getData(): array
    {
        /** @var BookLoader $books */
        $books = tap(
            value: $this->getLoader(class: BookLoader::class),
            callback: static fn (BookLoader $loader) => $loader->load()
        );
        /** @var CharacteristicsLoader $characteristics */
        $characteristics = tap(
            value: $this->getLoader(class: CharacteristicsLoader::class),
            callback: static fn (CharacteristicsLoader $loader) => $loader->load()
        );

        return [
            [
                'name' => 'Alquimia',
                'latin' => 'Alchimia',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Con siglos de tradición a sus espaldas, la alquimia medieval es una extraña mescolanza de ciencia y filosofía, de química y astrología, de física y arte. El alquimista es capaz de rodearse en su laboratorio de alambiques y atanores para experimentar con los elementos y preparados más extraños del universo y, al mismo tiempo, reflexionar sobre la influencia de los astros, la existencia de los homúnculos, la creación de los autómatas o el descubrimiento de la piedra filosofal. Y es que ellos son así... En el ámbito del juego, la competencia de Alquimia permite al personaje fabricar compuestos químicos sencillos —como drogas, venenos, antídotos, ácidos y otros sustancias de boticario—, elaborar ungüentos y pociones mágicas —véase el capítulo sobre magia para más información, págs. 156 y 157—, y entender el complicado lenguaje que aparecen en las obras alquímicas y la aún más complicada jerga que utilizan los alquimistas para difundir sus secretos… o para no difundirlos.',
            ],
            [
                'name' => 'Arco',
                'latin' => 'Arci',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano y Soldado. Esta competencia de armas permite al personaje utilizar todo tipo de arcos, ya sean cortos, largos o compuestos, armas utilizadas en la Península exclusivamente para la caza. Para más información sobre esta competencia, consulta el apartado sobre combate (pág. 128).',
            ],
            [
                'name' => 'Artesanía',
                'latin' => 'Artificium',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Con esta competencia el personaje será capaz de fabricar, construir y reparar todo tipo de utensilios, sin importar lo pequeños —joyas, herraduras, sillas…— o grandes —muebles, casas, molinos…— que sean, siempre y cuando cuente con los materiales adecuados para ello. Cada tipo de artesanía es diferente en sus métodos y en sus herramientas de trabajo y tratar de realizar aquí una lista de las diferentes clases y gremios artesanales que existieron en el Medievo sería un trabajo arduo y extenso, y ni tan siquiera mencionando los tipos de artesanos más usuales tendríamos una lista pequeña: carpinteros, herreros, sastres, zapateros, panaderos, cuchilleros, caldereros, campaneros, tejedores, vinateros, vidrieros, armeros, orfebres, canteros, plateros y cientos más. Por eso, cuando un personaje aprende a utilizar esta competencia más allá del porcentaje básico que posea en Habilidad, debe elegir un campo de experiencia, una artesanía concreta, en la que está especializado (carpintería, herrería, platería, etc.). De esa forma, obtendrá su porcentaje completo cada vez que trate de realizar un trabajo relacionado con su especialidad, pero si se trata de llevar a cabo un trabajo que escapa completamente a los límites de su campo de experiencia, la tirada de Artesanía la realizará a la mitad de su valor (redondeando hacia arriba) para indicar su desconocimiento de los métodos habituales de esa especialización. Claro que si se trata de un caso que no corresponde a su especialidad, pero no le es completamente indiferente, el DJ podría otorgarle una mayor dificultad, sin llegar a reducir su porcentaje a la mitad',
            ],
            [
                'name' => 'Astrología',
                'latin' => 'Astrologia',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia engloba el conocimiento que se poseía en la época sobre los astros, su movimiento, sus particularidades y su influencia sobre la vida y la conducta de las personas mediante los signos zodiacales y su horóscopo. A nivel práctico, el uso de la Astrología permite al personaje orientarse mediante la posición de las estrellas, saber la hora según la localización del sol, deducir el momento concreto en que ocurrirán determinados acontecimientos astronómicos —eclipses de sol y de luna, apariciones de cometas, lluvias de estrellas…—, confeccionar la carta astral de una persona o calcular la alineación planetaria necesaria para llevar a cabo según que invocaciones mágicas.',
            ],
            [
                'name' => 'Ballesta',
                'latin' => 'Arcuballistae',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Soldado y de Noble. Esta competencia de armas permite al personaje utilizar cualquier tipo de ballesta, armas diseñadas tanto para la guerra como para la caza y de gran difusión en la Edad Media peninsular. Para más información consulta el apartado sobre combate (pág. 128)',
            ],
            [
                'name' => 'Cabalgar',
                'latin' => 'Equitare',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia indica la habilidad del personaje para montar caballos, mulas, jumentos o burros5. Con sólo tener un porcentaje del 15% en la competencia (o del 5% para mulas y burros), el personaje será capaz de mantenerse erguido sin demasiados problemas sobre su montura, siempre y cuando vaya al paso, aunque deberá hacer una tirada de Cabalgar para evitar que se encabrite, para que se mantenga tranquilo si se enzarza en un combate o si se desea que se ponga a trotar, a galopar o a realizar algún tipo de salto o acrobacia. Un fallo en la tirada significaría que el jinete no puede controlar la montura y que puede llegar a derribarlo si se obtiene una pifia o un fallo reiterado en una situación especialmente delicada —caer de un caballo en movimiento es el equivalente a caer desde una altura de 3 varas o lo que es lo mismo, que el jinete reciba 1D6 Puntos de Daño—. Recordamos a todos aquéllos que gusten de combatir encima de un caballo que, tal y como se menciona en el capítulo dedicado al combate (pág. 125), el porcentaje de ataque cuando se lucha montado nunca puede ser superior al porcentaje que tengamos en Cabalgar.',
            ],
            [
                'name' => 'Cantar',
                'latin' => 'Cantare',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Ya se trate de una cántiga de amor trovadoresca, un sagrado canto gregoriano o el acompañamiento de una danza cortesana, el personaje que domine esta competencia sabrá cómo afinar adecuadamente su voz. De forma similar a lo que ocurre con las competencias de Idioma, el porcentaje que posee el PJ en Cantar indica el nivel de entonación y modulación que es capaz de aportar a su voz, así que rara vez tendrá que realizar tiradas por esta competencia, excepto en determinados casos especiales: una actuación importante, lograr un tono determinado o incluso emocionar con una melodía a un demonio del averno.',
            ],
            [
                'name' => 'Comerciar',
                'latin' => 'Negotiari',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia mide la capacidad del personaje para realizar pequeñas operaciones financieras, conocer las mejores rutas comerciales entre dos puntos concretos, vender o comprar todo tipo de productos, realizar cambios de moneda lo más beneficiosos posible, sobornar a un representante de la ley para que haga la vista gorda6, o regatear el precio de un artículo o servicio concreto. En este último caso, el vendedor y el comprador del objeto deberán realizar una confrontación de Comerciar: si gana el vendedor, el precio se mantendrá inalterable, y si gana el comprador, podrá adquirir el objeto a un precio rebajado, que puede ser de hasta un 30% en caso de obtener un éxito crítico en su tirada, aunque lo habitual es una rebaja de entre el 10 y el 20% del precio original.',
            ],
            [
                'name' => 'Conducir Carro',
                'latin' => 'Vehiculare',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Para controlar y manejar cualquier tipo de vehículo de tracción animal, como carros, carretas, carruajes o incluso arados, debemos utilizar esta competencia. La mayor parte del tiempo no será necesaria tirada alguna para conducir un carro, pero en ciertas ocasiones —los animales se encabritan; el carro pierde el control; se rompe una rueda mientras se viaja rápidamente; se realiza una maniobra a la que no están acostumbrados los animales, como un giro violento, una frenada brusca, lanzar el carro a toda velocidad…—, sí que será necesario realizar una tirada por la competencia para comprobar el éxito de la acción.',
            ],
            [
                'name' => 'Conocimiento Animal',
                'latin' => 'Scientia Animalis',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa los conocimientos que posee el personaje sobre la vida y las costumbres animales, tanto a nivel práctico como teórico. Gracias a ella, el personaje podrá identificar a un animal concreto según sus huellas, excrementos o costumbres, conocer sus hábitos alimenticios y su actitud frente al hombre, predecir su conducta ante una situación determinada, e incluso sabrá cómo se lo puede domar o domesticar —en caso de tratarse de un animal de monta, el personaje tirará por la competencia de Cabalgar o de Conocimiento Animal, la que tenga menor porcentaje de las dos—. Hemos de recordar que Conocimiento Animal sólo debe usarse sobre aquellos animales que no posean una naturaleza mágica y nunca sobre criaturas irracionales.',
            ],
            [
                'name' => 'Conocimiento de Área',
                'latin' => 'Scientia Regionis',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia engloba el conocimiento que un personaje pueda tener sobre una zona determinada, no mayor que una región, comarca o ciudad en concreto: sus gentes y costumbres, su historia, la organización de su gobierno, sus accidentes geográficos, sus habitantes más conocidos, etc. Naturalmente, esta competencia debe adquirirse por separado para cada zona geográfica o para cada ciudad —no es lo mismo Conocimiento de Área (Burgos) que Conocimiento de Área (baronía de Rincón)—, así que el porcentaje básico con el que empieza el PJ en esta competencia corresponderá al lugar de origen del personaje; a partir de ahí, será libre de aumentarla o elegir otro Conocimiento de Área diferente7.',
            ],
            [
                'name' => 'Conocimiento Mágico',
                'latin' => 'Scientia Magices',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Si un personaje de Aquelarre desea adentrarse en el misterioso mundo de la magia necesitará esta competencia, pues representa los conocimientos teóricos que el personaje posee sobre todo tipo de artes mágicas: rituales, instrumentos, elementos, fórmulas, invocaciones, conjuros, etc. —estamos hablando siempre a nivel teórico, no práctico: para lanzar un hechizo el personaje debe aprender dicho hechizo de forma separada a esta competencia—. Una tirada exitosa de esta competencia le permitiría leer grimorios escritos en intrincados lenguajes herméticos, reconocer un hechizo examinando los restos de los componentes que se utilizaron en su elaboración, o analizar viejas reliquias y artefactos mágicos de procedencia olvidada. También se puede usar Conocimiento Mágico para reconocer las peculiaridades mágicas que poseen ciertas criaturas del mundo irracional, una información mucho más académica y “científica” —llamémoslo así— que la que nos ofrece la competencia Leyendas, aunque sólo obtendremos aquellos datos que se relacionen con el mundo de la magia y su utilización.',
            ],
            [
                'name' => 'Conocimiento Mineral',
                'latin' => 'Scientia Metallis',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa el conocimiento que posee el personaje sobre todo tipo de minerales, metales y tierras, lo que le permite identificarlos y conocer sus propiedades. Con una tirada exitosa el personaje podrá, por ejemplo, distinguir a simple vista una moneda de oro de una vulgar imitación, reconocer un suelo fértil de uno árido, localizar una veta de plata dentro de una mina, saber el tipo de mineral que se extrae de una cantera determinada e incluso orientarse en el interior de una cueva siguiendo el curso del agua o las corrientes de aire.',
            ],
            [
                'name' => 'Conocimiento Vegetal',
                'latin' => 'Scientia Plantae',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Todos aquellos conocimientos que posee el personaje sobre el mundo de las plantas se ven reflejados en esta competencia. Con ella el personaje puede identificar fácilmente todo tipo de hierbas y vegetales, incluyendo sus propiedades naturales, ya sean curativas, alimenticias o nocivas. También le permitirá conocer qué tipo de flora crece en un entorno determinado, dónde podría plantarse de la forma más provechosa un cultivo determinado o dónde se localizaría una planta determinada. Es posible, por tanto, realizar una tirada combinada de esta competencia con Descubrir para forrajear o para encontrar una hierba en un lugar concreto.',
            ],
            [
                'name' => 'Correr',
                'latin' => 'Currere',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Al contrario de lo que pueda parecer, esta competencia no indica la distancia o velocidad que un personaje pueda recorrer corriendo —de lo que hablaremos en el capítulo dedicado al combate, pág. 116—, sino su aguante en carreras de larga distancia, su habilidad para sortear obstáculos, el esfuerzo adicional que supone la realización de un sprint o incluso la capacidad de realizar determinadas artimañas durante una persecución.',
            ],
            [
                'name' => 'Corte',
                'latin' => 'Regia',
                'characteristic_id' => $characteristics->communication(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'El ambiente y el entorno que rodea las cortes palaciegas medievales no ha alcanzado aún los delicados niveles de intriga y conspiración de los siglos venideros, pero eso no significa que no se trate de un auténtico nido de víboras, donde los rumores, los cuchicheos, las confabulaciones, los complots y las maniobras políticas están a la orden del día, y donde es tan difícil labrarse un nombre como fácil es perder la confianza del rey y terminar desterrado. Esta competencia cubre todos los conocimientos que necesita un buen cortesano para medrar en las estancias palaciegas de los reinos medievales; desde conocer los múltiples matices que posee la etiqueta palaciega, manejar correctamente el extenso protocolo que rige el día a día de la vida cortesana, extender un rumor de la mejor forma posible —ya sea verdadero o falso—, o controlar los sutiles juegos de la intriga y la conspiración en las estancias y alcobas reales. Además, y ya fuera de la corte, una tirada de esta competencia permitirá al personaje conocer las sutilezas sociales que distinguen a las diferentes clases y cómo debe comportarse en una situación concreta, ya sea una audiencia real, un banquete en el castillo del señor local o una ceremonia de difuntos tras una cruenta batalla.',
            ],
            [
                'name' => 'Cuchillo',
                'latin' => 'Cultri',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano, Soldado y Noble. Gracias a esta competencia de armas un personaje puede utilizar durante un combate cuerpo a cuerpo todo tipo de armas blancas de pequeño tamaño, tales como cuchillos, dagas, puñales, etc. Para más información consulta el apartado sobre combate (pág. 129).',
            ],
            [
                'name' => 'Degustar',
                'latin' => 'Gustare',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia indica la capacidad del personaje para paladear y olfatear, y cuanto más alto sea su porcentaje en ella más refinados serán ambos sentidos, permitiéndole con tan sólo tomar un sorbo detectar alimentos y bebidas en mal estado o incluso envenenados, oler en el aire la presencia de sustancias aromáticas o pestilentes —rastros en el ambiente de un leve perfume, el aroma de una planta, el hedor del azufre…—, o distinguir un plato refinado y bien cocinado de una simple sopa de ajos recalentada.',
            ],
            [
                'name' => 'Descubrir',
                'latin' => 'Inquirere',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, el personaje puede percatarse de aquellas cosas que a simple vista no se podrían detectar, ya lo haga de forma consciente o no. Con Descubrir, por tanto, se podrá inspeccionar una habitación para encontrar puertas secretas, escudriñar en el interior de un arcón en busca de un doble fondo oculto, registrar los ropajes de una persona por si ocultara algún arma, localizar a un ladrón oculto entre las sombras —lo que implica un enfrentamiento entre nuestro Descubrir y el Sigilo del ladrón— o divisar desde una muralla al ejército enemigo que se acerca hasta nosotros.',
            ],
            [
                'name' => 'Disfrazarse',
                'latin' => 'Simulare',
                'characteristic_id' => $characteristics->communication(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Al contrario de lo que pueda parecer, el uso de esta competencia no conlleva la utilización ni de disfraces ni de maquillajes —casi inexistentes en el Medievo, por cierto, y muy poco útiles—, sino la capacidad de un personaje para hacerse pasar por quien no es realmente. Con ella, utilizando ropas, actitudes y ademanes bien estudiados, un PJ podría fingir que procede de una ciudad o una región diferente a la suya, que tiene una profesión distinta, que su posición social no es la que verdaderamente posee o incluso puede llegar a hacerse pasar por una persona del sexo contrario, aunque para ello se le debería asignar un penalizador a la tirada de, al menos, un -40%.',
            ],
            [
                'name' => 'Elocuencia',
                'latin' => 'Elocuentia',
                'characteristic_id' => $characteristics->communication(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa la soltura retórica y dialéctica del personaje, su verborrea y su labia. Con ella un personaje puede convencer a otro de un argumento determinado, cambiando su parecer por uno que sea más beneficioso para él: solicitar al guardia de un castillo que no registre su carromato; conseguir que se le fie en una taberna; demostrar al señor local que es inofensivo, para que le permita paso franco por sus tierras, o persuadir al abad de que le deje hojear ese bello códice que tan celosamente guarda en su biblioteca. También se puede usar para mentir de la manera más sincera posible, aunque en este caso la tirada de Elocuencia se debe enfrentar a la Empatía de la persona que está siendo engañada. De todas formas, esta competencia no puede usarse para obligar a un PNJ a llevar a cabo acciones del todo imposibles e impensables para él—por ejemplo, que un rico comerciante nos convierta, de la noche a la mañana, en herederos de su fortuna—, o que vayan en contra de los ideales de la persona que está siendo convencida —no podemos, por ejemplo, persuadir al guardia que vigila la celda en la que estamos presos de que nos deje libres sólo con nuestra labia—. Tampoco podemos usarlo ni para reducir el precio de un objeto —para eso existe Comerciar—, ni para seducir a un miembro del sexo opuesto —ya tenemos Seducción para hacerlo—, ni se puede usar contra otro personaje jugador —para hacer eso deben conversar los propios jugadores, sin tirada alguna que valga—. Además, si usamos Elocuencia en un idioma que no sea el natal, el porcentaje de la competencia no podrá ser superior al porcentaje que poseamos en ese idioma.',
            ],
            [
                'name' => 'Empatía',
                'latin' => 'Simpathia',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa la habilidad que posee el personaje para captar el estado emocional de otra persona, para ponerse en su lugar y así poder conocer su estado de ánimo aunque trate de ocultarlo. Una tirada exitosa de Empatía permitiría al personaje saber si la persona con la que hablamos nos está mintiendo —mediante un enfrentamiento con la Elocuencia del otro personaje—; si tras su aparente simpatía oculta recelos u odios; si está sufriendo por dentro, aunque nos sonría continuamente, o incluso si tras el rostro amable de una persona se oculta una mente fría, calculadora y quién sabe si tan siquiera humana.',
            ],
            [
                'name' => 'Enseñar',
                'latin' => 'Docere',
                'characteristic_id' => $characteristics->communication(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, un personaje será capaz de transmitir de la forma más eficaz posible los conocimientos que posee, tanto a nivel teórico como práctico. Es una competencia ideal para todos aquéllos que deseen convertirse en instructores o maestros de otros personajes, ya sean PJs o PNJs, pues con ella podrán aumentar el porcentaje que posee el alumno en una competencia, tal y como se explica en el apartado ‟Enseñanza” de este mismo capítulo (pág. 92).',
            ],
            [
                'name' => 'Escamotear',
                'latin' => 'Praestigiae',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Mediante el uso de esta competencia, un personaje será capaz de realizar pequeños juegos malabares con objetos del tamaño de pelotas, naranjas o incluso cuchillos —por lo que habría que otorgar un penalizador a la tirada—, además de permitir usar de manera ágil las manos y los engaños visuales para esconder objetos pequeños ante los ojos de la gente, tal y como se realiza en el juego del trile.
Además de todo ello, la velocidad y coordinación manual que conlleva el uso de la competencia de Escamotear permitiría utilizarla para robar de forma disimulada aquellos objetos de pequeño tamaño que un personaje pueda llevar encima, como las bolsas con el dinero que cuelgan de los cinturones, papeles o notas que se guardan en bolsillos y mangas, e incluso anillos, pendientes y otro tipo de joyas. Para llevar a cabo el robo, el personaje debe enfrentar su Tirada de Escamotear contra la tirada de Descubrir de su víctima —si se trata de otro PJ, la debe realizar el Director de Juego de forma oculta para no hacerle sospechar que está siendo robado—: un éxito por parte del ladrón indica que coge el objeto y un éxito por parte de la víctima indica que advierte que está siendo robado. Por tanto, un éxito por ambas partes haría que la víctima se diera cuenta del robo, pero también permitiría al ladrón alcanzar el objeto deseado. Sin embargo, un crítico por parte del ladrón indica que coge el objeto sin que su víctima se percate de nada, y uno por parte de la persona robada, significa que advierte que está siendo robado incluso antes de que el ladrón le meta mano al objeto, lo que le permitiría evitarlo. De todas formas, recordamos al DJ y a los personajes “amigos de lo ajeno”, que en la Edad Media el robo era castigado con gran dureza: habitualmente, se le cortaba la mano al ladrón y aquí paz y después gloria…',
            ],
            [
                'name' => 'Escuchar',
                'latin' => 'Auscultare',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Siempre que un personaje use su sentido del oído estará utilizando esta competencia, pues gracias a ella podrá escuchar ruidos que en circunstancias normales pasarían desapercibidos —sentir como se pronuncia el nombre del personaje en medio de una pelea de taberna—, percibirá sonidos por muy atenuados que estén —escuchar una conversación a través de una puerta—, o incluso oirá aquellos ruidos que le hubieran pasado por alto al no prestar atención —escuchar el ruido de unos pasos que se acercan mientras se está dormido—. Es habitual enfrentar esta competencia contra el Sigilo de un personaje que desea moverse en silencio.',
            ],
            [
                'name' => 'Escudo',
                'latin' => 'Scutum',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Noble. Con esta competencia de armas un personaje podrá utilizar en combate cuerpo a cuerpo cualquier tipo de arma blanca de tamaño medio, como espadas, cimitarras, espadas cortas, etc. Para más información consulta el apartado sobre combate (pág. 129).',
            ],
            [
                'name' => 'Espadas',
                'latin' => 'Spathae',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Noble. Con esta competencia de armas un personaje podrá utilizar en combate cuerpo a cuerpo cualquier tipo de arma blanca de tamaño medio, como espadas, cimitarras, espadas cortas, etc.',
            ],
            [
                'name' => 'Espadones',
                'latin' => 'Enses',
                'characteristic_id' => $characteristics->strength(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Noble. Esta competencia de armas permite a un personaje utilizar en combate cuerpo a cuerpo cualquier tipo de arma blanca de gran tamaño, como los montantes o alfanjes. Para más información sobre su utilización, consulta el apartado sobre combate (pág. 130).',
            ],
            [
                'name' => 'Esquivar',
                'latin' => 'Vitare',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, un personaje puede evitar el ataque de un oponente, utilizando para ello su destreza, su rapidez, su velocidad de reacción y cierto grado de intuición que no todo el mundo posee. A pesar de todo, algunos ataques no pueden esquivarse, como aquéllos que proceden de armas de proyectil —flechas, saetas, piedras…—. Esta competencia se describe con todo detalle en el capítulo de combate (pág. 121).',
            ],
            [
                'name' => 'Forzar Mecanismos',
                'latin' => 'Mechanica',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia mide la habilidad del personaje para manipular aquellos artilugios mecánicos que eran habituales en la época, aunque es utilizado especialmente para abrir las cerraduras de puertas, cofres o similares utilizando ganzúas y alambres —si no se pudieran utilizar, la tirada de Forzar Mecanismos tendría un penalizador considerable y la cerradura quedaría inservible tras su apertura—, además de para desmontar otro tipo de artefactos protomecánicos, como trampas, cebos, etc. En el caso de que el DJ desee aumentar la dificultad para abrir o manipular cerraduras u otro tipo de mecanismos, le recordamos que en el Medievo este tipo de dispositivos son mucho más grandes, aparatosos y, por tanto, simples que las contrapartidas actuales que nosotros manejamos y que, por tanto, sólo aquellas obras de cerrajería ideadas por verdaderos maestros artesanos deben considerarse como un reto para los personajes.',
            ],
            [
                'name' => 'Hachas',
                'latin' => 'Bipennes',
                'characteristic_id' => $characteristics->strength(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano y Soldado. Esta competencia de armas permite a un personaje utilizar en un combate cuerpo a cuerpo cualquier tipo de hacha, sea cual sea el tamaño que posea, ya sean hachas de mano o de combate. Para más información consulta el apartado sobre combate (pág. 130).',
            ],
            [
                'name' => 'Hondas',
                'latin' => 'Fundae',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano. Esta competencia de armas permite a un personaje utilizar cualquier tipo de honda; una de las armas de proyectiles más conocidas en la Edad Media peninsular, especialmente entre pastores y ganaderos, pero que también se utilizaba durante la batalla por honderos profesionales. Para más información consulta el apartado sobre combate (pág. 130)',
            ],
            [
                'name' => 'Idioma',
                'latin' => 'Lingua',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'El porcentaje que posee un personaje en esta competencia indica el grado de conocimiento que tiene sobre ese lenguaje en concreto; por tanto, cada una de las lenguas que conozca el PJ será tratada como una competencia de Idioma diferente con un porcentaje distinto para cada una de ellas: si, por ejemplo, se conoce correctamente el castellano y un poco del catalán, se tendría Idioma (Castellano) al 100% e Idioma (Catalán) al 30%. De esta forma, los idiomas que se desconocen por completo tienen un 0% y hasta que no se aprendiese el vocabulario mínimo en ellos —subiendo el porcentaje de la competencia— no se podría sumar el valor de su característica base, la Cultura. Recuerda además que esta competencia conlleva únicamente el conocimiento hablado de la lengua: para escribir o leer se utiliza otra competencia, Leer y Escribir. Aunque a veces el DJ puede solicitar una tirada de Idioma para entender una conversación enrevesada o para ocultar el acento del personaje, no suele ser lo habitual, pues, como hemos dicho antes, el porcentaje de la competencia nos muestra la fluidez que tiene el personaje con esa lengua en concreto. A discreción del Director de Juego, todo personaje que habite durante un tiempo en una zona que posea un idioma que todavía no domine podrá recibir de forma gratuita Puntos de Aprendizaje para gastar exclusivamente en el aumento de dicho idioma1.',
            ],
            [
                'name' => 'Juego',
                'latin' => 'Alea',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia indica los conocimientos que posee el personaje sobre todo aquello que esté relacionado con los juegos de azar o de tablero de la época: sus reglas, sus normas, las costumbres asociadas a ellos, etc. En aquellas partidas de juegos que no sean de azar, como el ajedrez, todos los participantes podrán realizar una tirada por esta competencia para comprobar quién gana, pero en el resto de juegos de azar, como los dados o las cartas, se deben enfrentar a la característica de Suerte de los contendientes, no a esta competencia. Además, una tirada exitosa les permitirá llevar a cabo trampas durante el transcurso de una partida o detectar si algún otro participante las está realizando y de qué tipo son.',
            ],
            [
                'name' => 'Lanzar',
                'latin' => 'Iacere',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, el personaje podrá arrojar objetos con precisión para que lleguen a un determinado lugar —lanzar un arma a las manos de un amigo, colar una bola por un agujero…—, para afianzar el objeto a un punto en concreto —como una cuerda con garfios en el saledizo de una casa—, o para utilizar un arma arrojadiza —un cuchillo, un hacha de mano, una piedra…—, aunque de este último tema se hablará largo y tendido en el capítulo de combate (pág. 117). Cualquier objeto que quepa en una mano y esté equilibrado puede ser arrojado a una distancia máxima igual a la Fuerza del personaje en varas; si es mayor o no está equilibrado, la distancia se reducirá considerablemente —si el Director de Juego lo estima conveniente se puede arrojar un objeto a una distancia superior a la máxima aplicando un penalizador de -5% por cada vara adicional—.',
            ],
            [
                'name' => 'Lanzas',
                'latin' => 'Hastae',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencias de Soldado y Noble. Con esta competencia un personaje podrá utilizar en combate cuerpo a cuerpo todo tipo de armas de asta, sin importar su tamaño y peso, como la lanza corta, la lanza de caballería, la morosa, etc. Para más información consulta el apartado sobre combate (pág. 131).',
            ],
            [
                'name' => 'Leer y Escribir',
                'latin' => 'Legere et Scribere',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa la capacidad de lectura y escritura que posee el personaje sobre todos aquellos idiomas que conoce —si no se posee la competencia de Idioma correspondiente, el PJ no sabrá ni leer ni escribir en ese lenguaje—. Una tirada exitosa le permitiría descifrar un texto escrito de forma apresurada, copiar párrafos de un viejo tomo, falsificar correctamente un documento oficial12, caligrafiar con buena y hermosa letra un libro de liturgia, traducir un libro de un idioma a otro —siempre que se conozcan ambos idiomas, claro…—, ojear por encima los volúmenes de una biblioteca o dejar constancia de sus conocimientos para la posteridad, aunque el porcentaje que utilizaremos para la tirada de Leer y Escribir nunca podrá ser superior al porcentaje que poseamos en la competencia de Idioma correspondiente.',
            ],
            [
                'name' => 'Leyendas',
                'latin' => 'Fabulae',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Todos los conocimientos que posee un personaje sobre leyendas y cuentos populares se ven reflejados en esta competencia. Con una tirada exitosa de Leyendas podemos descubrir las particularidades y debilidades de algún ser legendario, las supersticiones y creencias más extendidas en una zona, o las historias y fábulas míticas que rodean a un acontecimiento, persona o lugar, aunque la información obtenida debe ser empleada con cierta cautela, ya que las leyendas no tienen por qué ser del todo ciertas. De todas formas, recordamos al Director de Juego que el porcentaje que posee el personaje en su competencia de Leyendas corresponde a las historias y cuentos de su región de origen, por lo que el Director de Juego es libre de otorgarle una mayor dificultad a la tirada —y, por tanto, mayores penalizadores— cuando se trate de reconocer leyendas de una zona alejada de su lugar de nacimiento: por ejemplo, un PJ de origen gallego que tiene 60% en Leyendas podría tener un -25% para reconocer una leyenda catalana o incluso un -50% para una leyenda de origen árabe, a discreción del DJ.',
            ],
            [
                'name' => 'Mando',
                'latin' => 'Imperium',
                'characteristic_id' => $characteristics->communication(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias al uso de esta competencia, el personaje podrá dar órdenes a todos aquellos PNJs que se encuentren a su servicio o tengan un rango o una clase social inferior, ya sea de forma individual o como grupo. Si se obtiene un éxito en la tirada, el PNJ obedecerá la orden recibida, siempre y cuando no sea un mandato que atente contra sus principios, que contradiga las órdenes recibidas por un mando superior al del PJ, o que dañe directa o indirectamente su propia persona o la de sus seres queridos. De todas formas, para evitar que los PJs de posición social alta conviertan a todos los PNJs que aparezcan en el juego en sus comparsas y criados, el Director de Juego podrá limitar el uso de esta competencia si detecta un abuso por parte de los jugadores, o incluso volverla en contra del personaje —fueron tantas las sublevaciones campesinas que tuvieron que sufrir los señores feudales en el Medievo, que una más no importará demasiado. También es posible utilizar Mando para intimidar a otro PNJ, ya sea mediante amenazas más o menos veladas, manipulando los sentimientos y emociones del otro, con insultos directos, miradas amenazantes o incluso utilizando la simple presencia del personaje, pues de lo que se trata es de obligar a la víctima a llevar a cabo alguna acción movida únicamente por el miedo. Lo que sí debe quedar claro es que la competencia de Mando nunca podrá usarse para que un PJ obligue a otro PJ a realizar algo que no desee hacer y tampoco puede ser superior al porcentaje que poseamos en el idioma en que se dan las órdenes o se intimida.',
            ],
            [
                'name' => 'Mazas',
                'latin' => 'Clavae',
                'characteristic_id' => $characteristics->strength(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Villanos y Soldados. Mediante esta competencia el personaje podrá utilizar en combate cuerpo a cuerpo todo tipo de mazas, sin importar su tamaño o peso, como la maza pequeña, la maza pesada o el garrote. Para más información consulta el apartado sobre combate (pág. 131).',
            ],
            [
                'name' => 'Medicina',
                'latin' => 'Ars Medica',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'La medicina medieval, especialmente en los reinos cristianos, está poco avanzada, basando todos sus diagnósticos y tratamientos en los viejos estudios de médicos romanos y griegos, especialmente Galeno, cuya teoría del equilibrio de los cuatro humores en el cuerpo dominará toda la medicina hasta muy avanzada la Edad Moderna. Los judíos y árabes, sin embargo, poseen técnicas de curación y diagnosis mucho más avanzadas que las cristianas, como demuestran los grandes estudios médicos que se publican en lengua árabe durante toda la Edad Media. Esta competencia, por tanto, representa el nivel de conocimientos que posee el personaje sobre medicina y anatomía, permitiéndole diagnosticar y curar enfermedades, heridas o envenenamientos, siempre y cuando disponga del equipo médico adecuado —melecinas, enemas, sangrías, vendas…—, además de tiempo y reposo por parte del paciente. Para más información, consulta el apartado Curación del capítulo III (pág. 110).',
            ],
            [
                'name' => 'Memoria',
                'latin' => 'Memoria',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia determina la capacidad de retentiva del personaje y la posibilidad de acceder rápidamente a los recuerdos que se poseen sobre experiencias pasadas. Con una tirada exitosa de Memoria —que siempre se debe hacer a instancias del Director de Juego, nunca por propia iniciativa del jugador—, el personaje podrá recordar aquellos detalles que se le habían pasado por alto, un nombre perdido en sus memorias de la infancia o una cara que una vez atisbó entre una multitud. Además, si el DJ piensa que alguno de los jugadores ha olvidado un elemento importante de la aventura que se está jugando, puede hacer tirar al personaje por Memoria para recordárselo y así reconducir la partida.',
            ],
            [
                'name' => 'Música',
                'latin' => 'Musica',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'La música medieval en los reinos peninsulares de los siglos XIV y XV es una mescolanza de diversas corrientes musicales, como los cantos sefardíes, las cántigas cristianas, los cantares andalusíes y árabes, las pervivencias de los ritos mozárabes, las influencias francesas del ars nova o los sonidos gregorianos del rito romano, impuesto en la liturgia cristiana desde el siglo XII. Sea como fuere, esta competencia representa los conocimientos musicales que posee el personaje, tanto a nivel teórico, como la lectura de notaciones neumáticas —las partituras del Medievo— o la capacidad de distinguir influencias o autores en una melodía determinada, como a nivel práctico, pues el personaje será capaz de tocar un instrumento en concreto, que debe especificar en cuanto posea un porcentaje en la competencia por encima del valor básico de Cultura. También puede usar el resto de instrumentos, pero tendrá unos penalizadores de -25% a la tirada.
Los instrumentos musicales más utilizados en la Península fueron el arpa, la bandurria, el caramillo, la cítara, la gaita, la flauta, el laúd, el órgano y la vihuela, aunque existieron muchos más.',
            ],
            [
                'name' => 'Nadar',
                'latin' => 'Natare',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Siempre que un personaje quiera nadar o bucear tendrá que utilizar esta competencia, que representa su habilidad para moverse en el agua, ya sea sobre o bajo ella. Cada éxito obtenido en la competencia permitirá al personaje moverse hasta 6 varas en un solo asalto, que pueden ser más si obtiene un crítico en la tirada; un fallo solo indicaría que no se mueve ese asalto, pero debe tener cuidado, ya que si falla tres veces consecutivas o si pifia cualquiera de las tiradas, el personaje empezará a ahogarse (véanse las reglas de Asfixia en la pág. 102). Las tiradas de Nadar se pueden ver modificadas por el estado de las aguas —un río agitado, fuertes corrientes, tiempo tempestuoso—, el peso que se lleva encima y la armadura que use el personaje.
También se puede usar Nadar para rescatar a una persona del agua, pero en ese caso la tirada de Nadar se verá reducida a la mitad de su porcentaje, a lo que luego habrá que añadir los posibles penalizadores que el Director de Juego considere oportunos por peso, armadura o estado de las aguas.',
            ],
            [
                'name' => 'Navegar',
                'latin' => 'Navigare',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, un personaje podrá gobernar cualquiera de las embarcaciones que surcan los mares en el Medievo, desde una simple barca de remos hasta la inmensa galera, pasando por galeotas piratas, galeazas mercantiles, carracas italianas o saetas corsarias. Hay que tener en cuenta que las naves pequeñas sí que podrán ser conducidas por el mismo personaje que hace la tirada, pero las embarcaciones más grandes necesitarán una tripulación mínima para poder dirigirlas, por lo que en esos casos es habitual hacer una tirada combinada de esta competencia con la de Mando. Además, las tiradas de Navegar que lleve a cabo el personaje podrán verse modificadas por el estado de las aguas, por la climatología —galernas, tempestades, niebla, tormentas— o por la embarcación que utilicemos, ya que no todas poseen las mismas características marineras.',
            ],
            [
                'name' => 'Ocultar',
                'latin' => 'Occultare',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias al uso de esta competencia, el personaje podrá esconder objetos de pequeño o mediano tamaño para que sea más difícil su localización, como ocultar un cuchillo entre los ropajes, una carta en una estancia o una joya en un baúl. Una tirada exitosa de Ocultar también le permitirá ayudar a otros personajes a ocultarse de la vista de los demás —aunque recordamos que para esconderse uno mismo es necesario utilizar la competencia de Sigilo—. Por todo ello, es habitual enfrentar las tiradas de Ocultar contra la competencia Descubrir de quien trata de encontrar a la persona u objeto ocultos.',
            ],
            [
                'name' => 'Palos',
                'latin' => 'Fustes',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano. Gracias a esta competencia el personaje podrá utilizar en combate cuerpo a cuerpo todo tipo de varas, palos y cayados, como los bastones de combate o los bordones de peregrinos. Para más información consulta el apartado sobre combate (pág. 134).',
            ],
            [
                'name' => 'Pelea',
                'latin' => 'Pugna',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => true,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Competencia de Armas de Villano, Soldado y Noble. Esta competencia mide la habilidad del personaje tanto para utilizar sus puños y piernas en un combate como para utilizar tretas más o menos honorables durante el mismo, como zancadillas, empujones, etc. Para más información, consulta el apartado sobre combate, pág. 134.',
            ],
            [
                'name' => 'Rastrear',
                'latin' => 'Vestigare',
                'characteristic_id' => $characteristics->perception(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, el personaje podrá seguir el rastro que un animal o una persona deja tras de sí mediante la observación del terreno, como huellas, pisadas en el barro o en la nieve, excrementos dejados por el animal, pelaje en un arbusto, ramas quebradas en un sendero, despojos abandonados, etc. También permitirá acechar a una persona o animal que se tiene a la vista en una ciudad o en un despoblado, y poder así seguirlo sin que la víctima se percate de ello —aunque este uso de Rastrear requiere enfrentar la competencia contra el Descubrir de la persona o animal vigilado—. Además, esta competencia permitirá ocultar las huellas que dejamos tras nosotros para evitar que podamos ser rastreados por otros personajes —aunque también conlleva ralentizar nuestra marcha—, o encontrar en una zona despoblada refugio, alimento, caza, agua y todo lo necesario para poder sobrevivir a la intemperie.',
            ],
            [
                'name' => 'Saltar',
                'latin' => 'Salire',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa la capacidad que posee el personaje para llevar a cabo todo tipo de saltos, ya sean de altura o de longitud. Siempre que haya tomado carrerilla para coger impulso, una tirada exitosa de Saltar le permitiría al personaje realizar un salto igual a su altura en vertical o hasta dos veces su altura si lo realiza en horizontal. Si se realiza el salto sin coger carrerilla, la distancia recorrida se verá reducida a la mitad, e igualmente, si se obtiene un crítico en la tirada, el DJ puede aumentar de forma razonable la distancia saltada13. Además, una tirada de Saltar le permitiría al personaje llevar a cabo acrobacias sencillas o incluso girar en el aire para aterrizar de la mejor forma posible durante una caída, como se explica en el apartado sobre salud y heridas (pág. 102).',
            ],
            [
                'name' => 'Sanar',
                'latin' => 'Sanare',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Si la competencia Medicina incluye todos los conocimientos teóricos que el personaje puede poseer sobre la anatomía médica y el tratamiento de enfermedades, esta competencia pretende cubrir todos aquellos métodos prácticos de curación que no pertenecen exclusivamente a la ciencia medicinal, unos tratamientos muy similares a nuestros actuales primeros auxilios14. Por eso, con una tirada exitosa de Sanar podemos estabilizar a un herido agonizante, restañar una hemorragia, extraer una flecha, reanimar a un ahogado o hacer volver en sí a una persona desfallecida. Para más información sobre el uso de Sanar consulta el apartado sobre curación (pág. 110).',
            ],
            [
                'name' => 'Seduccion',
                'latin' => 'Delenimentum',
                'characteristic_id' => $characteristics->aspect(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Gracias a esta competencia, el personaje podrá mantener una relación lo más íntima posible —por decirlo de una manera bonita— con un miembro del sexo opuesto, o incluso del mismo sexo si ambos personajes comparten aficiones similares en materias carnales. Claro que, como ocurre en la vida real, el juego de la conquista amorosa no es llegar y besar el santo, y es que para poder seducir completamente a una persona, el PJ deberá tener éxito en tres tiradas consecutivas de Seducción: con la primera tirada se iniciará la fase de la amistad, en la que la pareja compartirá confidencias y secretos íntimos —lo cual puede resultar muy útil para recabar información—; la segunda tirada indica una verdadera confianza en la pareja, sucediéndose los abrazos, los besos y las caricias; y por fin, tras la última tirada, el personaje conseguirá llegar, literalmente, a la cama de la otra persona —o a algún otro sitio reservado y discreto, si no se es muy remilgado—15. Claro que un solo fallo en alguna de las tres tiradas romperá todo el proceso y habrá que empezar desde el principio, mientras que una pifia en cualquiera de las fases significará que el PJ ha ofendido gravemente a la otra persona, con todo lo que ello pueda conllevar si ésta es de naturaleza vengativa o tiene familiares dispuestos a lavar, según que afrentas, el honor.
Como ya habrás observado, esta competencia no depende de ninguna de las siete características principales, sino de una de las secundarias, Aspecto. A pesar de todo, su utilización no difiere en nada del resto de competencias; a lo sumo, permitirá al PJ aumentar más fácilmente el porcentaje de Seducción por encima del 100% si cuenta con un Aspecto superior a 20.',
            ],
            [
                'name' => 'Teología',
                'latin' => 'Theologia',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Esta competencia representa los conocimientos que posee el personaje sobre las doctrinas, los dogmas, la liturgia, los ritos y la historia de la religión que profesa, ya sea cristianismo, judaísmo o islamismo. Con una tirada exitosa de Teología podrá saber, por ejemplo, la regla que rige un monasterio cisterciense, cómo distinguir a un obispo de un arzobispo, a qué santo se puede rezar para infundir valor en el combate, en qué lugar de un templo se suelen guardar los objetos preciosos o qué versículo del Corán debemos utilizar para alejar el mal de ojo. Naturalmente, Teología es una competencia primordial para todos aquéllos que deseen realizar rituales de fe. Ya que las tres religiones que se practican en la Península poseen algunos puntos en común, un PJ de una de dichas religiones también puede llegar a conocer determinados aspectos de las otras dos religiones que no profesa: para ello, deberá hacer una tirada por su valor de Teología con un penalizador de -50%, a no ser que posea la competencia de Idioma que se utiliza en la religión de la que se quiere saber algo —que puede ser latín, hebreo o árabe—, ya que, en este caso, podrá tirar por dicho porcentaje con un -25% si el resultado así obtenido es mayor que el de Teología –50%. De todas formas, al igual que ocurre con las tiradas combinadas, el porcentaje de Idioma no podrá ser nunca superior al valor de Teología que tenga el personaje.',
            ],
            [
                'name' => 'Sigilo',
                'latin' => 'Sigillum',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Si el personaje desea pasar desapercibido ésta es la competencia que deberá utilizar, pues con ella podrá moverse de forma silenciosa, haciendo el menor ruido posible; mezclarse en una multitud para escapar de una persecución o esconderse en las sombras para evitar ser visto. Es habitual que las tiradas de Sigilo sean modificadas por el Director de Juego teniendo en cuenta la situación concreta en la que tiene lugar la acción del personaje, pues el clima (niebla, lluvia, nieve…), los objetos circundantes (rocas, árboles, hojas caídas, muros…), o el momento (noche, día…) pueden favorecer o dificultar los intentos del personaje de pasar desapercibido. Además, es muy frecuente enfrentar la competencia de Sigilo del personaje que se oculta contra el Descubrir o Escuchar de aquéllos que pueden descubrirle.',
            ],
            [
                'name' => 'Tormento',
                'latin' => 'Supplicium',
                'characteristic_id' => $characteristics->ability(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'La vida en el Medievo era dura y difícil, y esta competencia, habitual en soldados, bandidos e inquisidores, lo demuestra, pues gracias a ella el PJ podrá sonsacarle información a una persona utilizando métodos físicos o psicológicos, pero en todo caso, claramente violentos. Si se utiliza de forma intimidatoria, sin ánimo de hacer daño físico al otro, el personaje deberá enfrentar su tirada de Tormento a la Templanza de su víctima: si gana el enfrentamiento, el personaje atormentado dirá lo que el PJ quiera saber. En el caso de que el personaje opte por utilizar la tortura física, también deberá enfrentar su Tormento con la Templanza del otro, aunque éste último tendrá un penalizador de -25% en su tirada. Claro que si el PJ falla su tirada de Tormento, dañará a su víctima, provocándole la pérdida de 1D6 Puntos de Vida; y si pifia, la persona torturada muere en el acto. Un crítico en cualquiera de las situaciones supone ganar de forma automática el enfrentamiento y que la víctima hable directamente.',
            ],
            [
                'name' => 'Trepar',
                'latin' => 'Scandere',
                'characteristic_id' => $characteristics->agility(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Al utilizar esta competencia el personaje podrá subir por superficies y terrenos más o menos verticales, como murallas, acantilados, riscos, árboles o paredes. Un éxito en una tirada de Trepar significa que el personaje puede escalar en ese asalto una distancia máxima de 4 varas —gastando sus dos acciones de asalto—, y aunque un fallo supondría no moverse en dicho asalto, dos fallos consecutivos o una pifia en la tirada conllevaría la caída del personaje —consulta el capítulo III sobre salud y heridas para determinar los efectos de la caída, pág. 102—. Si la necesidad obliga, el personaje podría recorrer una distancia mayor cada asalto, aunque deberá restar -10% a su porcentaje de Trepar por cada vara adicional que desee subir ese asalto. Claro que siempre se pueden utilizar escalas, gradillas o cuerdas para ayudarse en el ascenso, utensilios éstos que pueden proporcionar hasta un +40% a la tirada de Trepar.',
            ],
            [
                'name' => 'Andalusí',
                'latin' => '',
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Dialecto popular del reino nazarí de Granada y de los moriscos de la Península compuesto por una mezcla de palabras castellanas, árabes y catalanas, utilizada únicamente para la comunicación hablada, y nunca para la escrita o para la liturgia, donde se utilizaba el árabe',
            ],
            [
                'name' => 'Árabe',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Lengua oficial del reino nazarí de Granada, conocida igualmente por los moriscos de toda la Península y por buena parte de los sabios y eruditos de la época, pues fueron muchos los escritores musulmanes que la utilizaron para sus libros',
            ],
            [
                'name' => 'Aragonés',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Idioma popular utilizado en toda la corona de Aragón y que, a comienzos del siglo XV, iría desapareciendo progresivamente en favor del castellano',
            ],
            [
                'name' => 'Bable',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Lengua romance utilizada por los estratos populares y rurales de la zona de Asturias y parte de León y Cantabria.',
            ],
            [
                'name' => 'Castellano',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Llamado también “español”, es el idioma romance popular utilizado en el reino de Castilla, convertido en oficial por Alfonso X, y el más extendido en la Península',
            ],
            [
                'name' => 'Catalán',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Denominado también “català” es otra de las lenguas romances de la Península, utilizada de forma popular en toda Cataluña, en Baleares y en el reino de Valencia',
            ],
            [
                'name' => 'Euskera',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'También conocido como “vasco” o “vascuence”, es la lengua extendida por las zonas rurales de buena parte del reino de Navarra y del norte de Castilla',
            ],
            [
                'name' => 'Gallego',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Denominado también “galaicoportugués”, es otro idioma romance utilizado de forma popular en el reino de Galicia y en Portugal, muy utilizado por trovadores y juglares gracias a su sonoridad',
            ],
            [
                'name' => 'Griego',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'También conocido como "bizantino", es la lengua originaria de Grecia, perteneciente a la rama griega de las lenguas indoeuropeas. Utiliza un sistema de escritura del que deriva el alfabeto latín (alfabeto griego, derivado del fenicio), y es la lengua indoeuropea con más historia documentada (3400 años de evidencia escrita)',
            ],
            [
                'name' => 'Hebreo',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Idioma erudito del pueblo judío usado casi de forma exclusiva en la literatura, la enseñanza y la liturgia, y que rara vez se utiliza en conversaciones',
            ],
            [
                'name' => 'Ladino',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'También conocido como “judeoespañol” es una mezcla del hebreo con palabras castellanas, catalanas, aragonesas e incluso árabes, hablado comúnmente por la minoría judía en toda la Península',
            ],
            [
                'name' => 'Latín',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Junto al árabe y al hebreo, es el idioma de la cultura y la ciencia durante todo el Medievo y, aunque es usado en la mayor parte de los casos en su forma escrita, muchos sacerdotes y clérigos también lo hablaban con fluidez',
            ],
            [
                'name' => 'Mozárabe',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => true,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->aq3ed(),
                'created_by' => null,
                'description' => 'Dialecto hablado por los mozárabes cristianos del reino de Granada con diversas palabras castellanas y árabes. Al contrario que otras lenguas romances, el mozárabe se escribía siempre con caracteres arábigos, no latinos',
            ],
            [
                'name' => 'Demonología',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => false,
                'book_id' => $books->daemonolatreia(),
                'created_by' => null,
                'description' => 'Competencia de base de Cultura, que al igual que los idiomas parte de cero hasta que sea aprendida. Es una especialización de Conocimiento Mágico, que va más allá aún, pues explora a los demonios, sus clases, jerarquías, poderes o debilidades, y secretos de los mismos. Además funciona también como la competencia Corte a efectos de etiqueta infernal (saber como «comportarse» adecuadamente) y como un lenguaje, pudiendo el que posea la competencia hablar con los demonios en su propia lengua: el lenguaje oscuro. Los demonios entenderán al demonólogo (aunque para ellos tendrá un acento de paleto); sin embargo este «idioma» no se puede usar con éxito entre dos humanos más que para comunicar conceptos básicos (generalmente una palabra: alto, hola, comida, agua, etcétera), a no ser que se tenga a un 101 %.
Esta competencia tiene varios usos. Si se hacen unos preparativos adicionales de al menos media hora en la ceremonia de invocación o aquelarre de cualquier entidad demoníaca y se pasa una tirada de Demonología con éxito, se consigue un bonificador de +15 % a la tirada de invocación. Una vez aparece la entidad, si se pasa otra tirada, se tendrá un bonificador de +15 % a cualquier tirada de Elocuencia contra ella, pues se descubre qué agrada a la entidad, o la forma de comunicarse correctamente con ella, etcétera. Estos usos anteriores no son aplicables a los demonios servidores, ya que la competencia actúa de forma distinta, proveyendo de los conocimientos necesarios para poder invocar a dichos entes que, en un principio, no deberían salir de los Infiernos.
Pero la competencia Demonología no solo es patrimonio de brujos. A aquellos monjes y sacerdotes dedicados al exorcismo les vendría bien conocer la competencia. Si se saca una tirada antes de un ritual de Exorcismo (pág. 255/177 del manual de juego), el exorcista obtiene un bonificador de +15 % al exorcismo, por haber descubierto algo que moleste y debilite al demonio. Si la tirada es un crítica, el exorcista recuerda que el demonio en cuestión tiene una debilidad fatal (quizá no soporte un salmo en concreto, el ajo, o que odie el amanecer, etcétera). Si el exorcista se consigue aprovechar de la debilidad y trae el objeto de la repulsa del demonio a su presencia, obtendría un bonificador de +50 % (en algunos casos incluso más). Si no lo consigue, puede atormentar al espíritu por tener una debilidad tan tonta, ganando un bonificador de +25 %. Con este uso de Demonología también se puede usar en el hechizo Expulsión (pág. 203/156 del manual de juego).'
            ],
            [
                'name' => 'Criptografía',
                'latin' => null,
                'characteristic_id' => $characteristics->culture(),
                'is_weapon' => false,
                'is_language' => false,
                'initial' => true,
                'starts_with_base' => true,
                'book_id' => $books->daemonolatreia(),
                'created_by' => null,
                'description' => 'permite cifrar o descifrar códigos criptográficos (desde palabras clave a intercambio de letras, números, símbolos o figuras alegóricas). Era común en la Edad Media que los libros de ocultismo estuvieran protegidos crip¬tográficamente, para evitar que magos o brujos rivales obtuviesen el conocimiento que tenían, o por simple autoprotección (a un monje no le gustaría que su abad se enterase del verdadero contenido de ese libro que tanto consulta). Además, la criptografía usada en libros ocultos estaba envuelta en un halo de magia y misterio; era práctica normal recitar conjuros o encomen¬darse a ángeles o demonios para que ayudasen al lector a entender el texto.
Para poder descifrar un texto encriptado, suponiendo que se tenga la clave, se necesitará al menos un porcentaje del 25 % en Criptografía y se tarda una cuarta parte más de tiempo de lo normal en leerlo respecto a un texto sin encriptar (si el texto estuviese encriptado con un código fuerte, este tiempo podría incrementarse según lo estime el DJ).
Si se desea encriptar un libro, se ha de pasar una tirada de Criptografía antes de empezar el trabajo, en lo cual se tardará una semana. Esta tirada puede tener un penalizador (–25 %, –50 % o –75 %), que decidirá el propio criptógrafo a fin de hacer su código más fuerte. Si se pasa se puede empezar a escribir el libro cifrado, el cual tardará en escribirse un 15 % más de tiempo, más otro 15 % extra por cada –25 % de penalizador que tuviese la tirada. Si no se pasa, se puede volver a intentar con otra semana de estudio y una nueva tirada. Un crítico aumenta el penalizador para romper el código en –25 % sin coste de tiempo adicional a la hora de escribirlo. La pifia puede hacer pensar al escritor que el código es bueno, dando luego un libro incomprensible, o simplemente retrasar el trabajo un mes, antes de poder hacer una nueva tirada'
            ],
        ];
    }
}
