<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Kingdom\Application;

use App\Game\Core\Features\Kingdom\Application\Pages\ListKingdoms;
use App\Game\Core\Features\Kingdom\Application\Schemas\KingdomInfolist;
use App\Game\Core\Features\Kingdom\Application\Tables\KingdomTable;
use App\Game\Core\Features\Kingdom\Infrastructure\Models\Kingdom;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class KingdomResource extends Resource
{
    protected static ?string $model = Kingdom::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function infolist(Schema $schema): Schema
    {
        return KingdomInfolist::admin($schema);
    }

    public static function table(Table $table): Table
    {
        return KingdomTable::admin($table);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListKingdoms::route('/'),
        ];
    }
}
