<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Characteristics\Application;

use App\Game\Core\Features\Characteristics\Application\Pages\ListCharacteristics;
use App\Game\Core\Features\Characteristics\Application\Pages\ViewCharacteristic;
use App\Game\Core\Features\Characteristics\Application\Schemas\CharacteristicInfolist;
use App\Game\Core\Features\Characteristics\Application\Tables\CharacteristicTable;
use App\Game\Core\Features\Characteristics\Infrastructure\Models\Characteristic;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class CharacteristicResource extends Resource
{
    protected static ?string $model = Characteristic::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function infolist(Schema $schema): Schema
    {
        return CharacteristicInfolist::admin($schema);
    }

    public static function table(Table $table): Table
    {
        return CharacteristicTable::admin($table);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListCharacteristics::route('/'),
            'view' => ViewCharacteristic::route('/{record}'),
        ];
    }
}
