<?php

declare(strict_types=1);

namespace Database\Seeders\Core\Professions\DataProviders\Competences;

use Aquelarre\Core\Framework\Infrastructure\Seed\Loaders\Competence\CompetencesLoader;
use Aquelarre\Core\Framework\Infrastructure\Seed\Loaders\Profession\ProfessionLoader;
use Aquelarre\Core\Profession\Domain\Dto\CompetenceFluent;
use Database\Seeders\Contracts\DataProvider;

class Basic extends DataProvider
{
    public function getData(): array
    {
        /** @var ProfessionLoader $professions */
        $professions = $this->getLoadedLoader(ProfessionLoader::class);
        /** @var CompetencesLoader $competences */
        $competences = $this->getLoadedLoader(CompetencesLoader::class);
        return [
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('conocimiento_de_area'))->primary(),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('correr'))->primary(),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('escuchar'))->primary(),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('rastrear')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('alguacil'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('escudo'))->primary(),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('esquivar'))->primary(),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('cuchillo')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('rastrear')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('almogavar'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('alquimia'))->primary(),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('astrologia'))->primary(),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('conocimiento_magico'))->primary(),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('conocimiento_mineral')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('griego')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('latin')),
            CompetenceFluent::profession($professions->profession('alquimista'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('corte'))->primary(),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('ensenar'))->primary(),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('artesania')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('ama'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('artesania'))->primary(),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('memoria'))->primary(),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('conducir_carro')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('cuchillo')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('artesano'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('tormento'))->primary(),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('ballesta')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('rastrear')),
            CompetenceFluent::profession($professions->profession('bandido'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('medicina'))->primary(),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('sanar'))->primary(),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('conducir_carro')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('cuchillo')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('barbero_cirujano'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('alquimia'))->primary(),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('astrologia'))->primary(),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('conocimiento_magico'))->primary(),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('conocimiento_vegetal'))->primary(),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('conocimiento_mineral')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('medicina')),
            CompetenceFluent::profession($professions->profession('brujo'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('disfrazarse'))->primary(),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('saltar'))->primary(),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('musica')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('bufon'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('latin')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_hombre'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('sanar'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('latin')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('caballero_de_orden_militar_mujer'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('alquimia'))->primary(),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('conocimiento_mineral'))->primary(),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('artesania')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('cuchillo')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('cambista'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('arco'))->primary(),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('escuchar'))->primary(),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('rastrear'))->primary(),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('cabalgar')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('cazador'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('latin'))->primary(),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('griego')),
            CompetenceFluent::profession($professions->profession('clerigo'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('idioma'))->primary(),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('conducir_carro')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('nadar')),
            CompetenceFluent::profession($professions->profession('comerciante'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('disfrazarse'))->primary(),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('memoria'))->primary(),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('conducir_carro')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('escamotear')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('comico'))
                ->competence($competences->get('teologia')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('corte'))->primary(),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('seduccion'))->primary(),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('cabalgar')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('cortesano'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('alquimia'))->primary(),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('conocimiento_magico'))->primary(),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('sanar'))->primary(),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('conocimiento_mineral')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('curandero'))
                ->competence($competences->get('medicina')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('conocimiento_magico')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('derviche'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('conducir_carro'))->primary(),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('alquimia')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('disfrazarse')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('escamotear')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('embaucador'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('idioma'))->primary(),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('memoria'))->primary(),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('escriba'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('arco'))->primary(),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('escudo')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('ghazi'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('cantar'))->primary(),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('seduccion'))->primary(),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('latin')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('pelea')),
            CompetenceFluent::profession($professions->profession('goliardo'))
                ->competence($competences->get('teologia')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('mando'))->primary(),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('ballesta')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('escudo')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('infanzon'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('cantar'))->primary(),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('musica'))->primary(),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('pelea')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('saltar')),
            CompetenceFluent::profession($professions->profession('juglar'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('correr'))->primary(),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('esquivar'))->primary(),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('trepar'))->primary(),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('disfrazarse')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('forzar_mecanismos')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('ladron'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('conocimiento_magico'))->primary(),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('alquimia')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('conocimiento_mineral')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('conocimiento_vegetal')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('medicina')),
            CompetenceFluent::profession($professions->profession('mago'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('conocimiento_de_area'))->primary(),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('escuchar'))->primary(),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('forzar_mecanismos'))->primary(),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('saltar')),
            CompetenceFluent::profession($professions->profession('malsin'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('nadar'))->primary(),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('navegar'))->primary(),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('trepar'))->primary(),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('idioma'))->quantity(2),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('marino'))
                ->competence($competences->get('seduccion')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('conocimiento_vegetal'))->primary(),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('medicina'))->primary(),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('sanar'))->primary(),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('alquimia')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('conocimiento_animal')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('conocimiento_mineral')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('medico'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('comerciar'))->primary(),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('conocimiento_de_area'))->primary(),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('disfrazarse')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('escamotear')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('leer_y_escribir')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('mediero'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('memoria'))->primary(),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('artesania')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('pelea')),
            CompetenceFluent::profession($professions->profession('mendigo'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('ensenar'))->primary(),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('latin'))->primary(),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('cantar')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('griego')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('arabe')),
            CompetenceFluent::profession($professions->profession('monje'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('empatia'))->primary(),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('pelea'))->primary(),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('saltar')),
            CompetenceFluent::profession($professions->profession('muccadim'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('mando'))->primary(),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('rastrear')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('pardo'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('conocimiento_animal'))->primary(),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('escuchar'))->primary(),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('rastrear'))->primary(),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('artesania')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('hondas')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('palos')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('saltar')),
            CompetenceFluent::profession($professions->profession('pastor'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('descubrir'))->primary(),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('nadar'))->primary(),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('navegar'))->primary(),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('ballesta')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('lanzar')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('seduccion')),
            CompetenceFluent::profession($professions->profession('pirata'))
                ->competence($competences->get('trepar')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('cantar'))->primary(),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('musica'))->primary(),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('seduccion'))->primary(),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('idioma')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('qaina'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('hebreo'))->primary(),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('astrologia')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('arabe')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('latin')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('rabino'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('escamotear'))->primary(),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('seduccion'))->primary(),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('forzar_mecanismos')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('ramera'))
                ->competence($competences->get('ocultar')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('latin'))->primary(),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('cantar')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('conocimiento_de_area')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('mando')),
            CompetenceFluent::profession($professions->profession('sacerdote'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('artesania'))->primary(),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('conducir_carro'))->primary(),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('conocimiento_vegetal'))->primary(),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('sigilo'))->primary(),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('correr')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('comerciar')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('degustar')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('juego')),
            CompetenceFluent::profession($professions->profession('siervo_de_corte'))
                ->competence($competences->get('saltar')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('ballesta'))->primary(),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('cabalgar'))->primary(),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('escudo'))->primary(),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('conducir_carro')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('cuchillo')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('esquivar')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('pelea')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('sanar')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('soldado'))
                ->competence($competences->get('tormento')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('elocuencia'))->primary(),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('musica'))->primary(),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('seduccion'))->primary(),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('cabalgar')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('cantar')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('leyendas')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('memoria')),
            CompetenceFluent::profession($professions->profession('trovador'))
                ->competence($competences->get('sigilo')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('arabe'))->primary(),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('leer_y_escribir'))->primary(),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('memoria'))->primary(),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('teologia'))->primary(),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('corte')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('descubrir')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('elocuencia')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('empatia')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('ensenar')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('escuchar')),
            CompetenceFluent::profession($professions->profession('ulema'))
                ->competence($competences->get('idioma')),
        ];
    }
}
