<?php

declare(strict_types=1);

namespace Database\Seeders\Commerce\Items;

use Aquelarre\Commerce\Domain\Dto\DBSeed\Items\Item;
use Database\Seeders\Contracts\DataProvider;

class ArmorSeeder extends DataProvider
{
    public function getData(): array
    {
        return collect([
            Item::armor('Pelliza de piel')->description('Una vestimenta rústica, pues se trata de una prenda de abrigo fabricada con pieles de animales sin curtir, típica de campesinos, de bandidos y de gentes con poco dinero que gastar en pren das de vestir. Cubre únicamente pecho y abdomen'),
            Item::armor('Ropas gruesas')->description('Aunque son en esencia unas ropas de abrigo diseñadas para proteger del frío usando para ello la lana, las pieles, el vellón o una mezcla de todo ello, también proporcionan una mínima protección contra el daño. Lo usan de forma habitual plebeyos y, usando materiales de mejor calidad, nobles, especialmente en zonas de alta montaña o en buena parte de la Península durante el invierno'),
            Item::armor('Brazales')->description('Protección de cuero curtido que se utiliza entre el codo y la muñeca, muy habitual entre los arqueros (para evitar rozaduras al usar el arco) y que a menudo se puede decorar mediante la técnica del repujado del cuero. Cubre únicamente los brazos'),
            Item::armor('Gambesón')->description('La más sencilla de las armaduras propiamente dichas, una especie de túnica con mangas fabricada con cuero curtido o tela rellena de retales o pelo de caballo. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Gambesón Reforzado')->description('Se trata de un desarrollo del gambesón normal, pero con añadidos de lona recia, cuero crudo (cuero que ha sido endurecido cociéndolo en agua, cera o grasa) e incluso de metal en zonas de poca movilidad, lo que refuerza aún más su protección. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Grebas de Cuero')->description('La mayor parte de las armaduras completas, sean del tipo que sean, sólo protegen las piernas hasta la rodilla, dejando expuesta toda la pierna hasta el tobillo. Para otorgar una pequeña protección a esa zona se crearon las grebas, fabricadas con cuero curtido. Sólo protegen las piernas'),
            Item::armor('Velmez')->description('Recibe este nombre el jubón de cuero que se usa debajo de otras armaduras más pesadas para amortiguar los golpes recibidos, aunque también es posible usarlo de forma independiente. Sólo cubre pecho y abdomen'),
            Item::armor('Coracina')->description('Denominada también "armadura de escamas", se trata de una túnica de tela sobre la que se colocan láminas de metal superpuestas a manera de escamas, y aunque es más resistente que la loriga de malla, también es cierto que es mucho más incómoda de llevar. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Coraza Corta')->description('Es una armadura ligera, muy ornamentada, que utilizan buena parte de los nobles guerreros del reino nazarí de Granada. Cubre únicamente pecho y abdomen y nunca se complementa con yelmo, sino con casco de metal'),
            Item::armor('Cota de Placas')->description('Denominada también "loriga de malla reaforzada" ya que no se trata más que de un desarrollo de la loriga de mallas, que se refuerza usando láminas de metal en determinadas zonas rígidas, como antebrazos, pecho, etc., para aumentar la protección que ofrece. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Grebas de Metal')->description('Un desarrollo de las grebas de cuero que utiliza láminas de metal para proteger la pierna entre la rodilla y el tobillo, usando cintas de cuero anudadas en la parte posterior. Sólo protegen las piernas'),
            Item::armor('Loriga de Malla')->description('Utilizada desde la época romana, la cota de malla vivió un resurgimiento durante la Edad Media. Fabricada con cientos de anillos que se unían mediante remaches para formar una túnica que se cosía a un velmez o gambesón de cuero, la loriga de malla cubría el tronco, parte de los brazos y las piernas hasta las rodillas, y fue probablemente la protección más comúnen los reinos peninsulares de los siglos XIV y XV. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Arnés')->description('Llamado también "armadura blanca", "completa" o "de placas", el arnés es el mayor perfeccionamiento de la armadura medieval, una protección formada por numerosas piezas metálicas unidas entre sí mediante correas, hebillas, clavos y ganchos y que, junto con el uso de un yelmo, protegía todo el cuerpo del usuario. Se trataba de armaduras extraordinariamente pesadas, utilizadas exclusivamente en duelos y batallas y con un precio exorbitante, así que sólo los nobles con mayor nivel económico podían permitirse el lujo de tener una. Con el tiempo, el arnés se transformó en una vestidura de gala para militares y perdió su función defensiva. Cubre todo el cuerpo, excepto la cabeza'),
            Item::armor('Bacinete')->description('La más habitual de las protecciones para la cabeza, un casco de metal semiesférico que protege también las orejas, aunque no posee ni visera ni gola y que puede llevarse con cualquier tipo de armadura (aunque combinar un arnés con un bacinete quedaba un pelín vulgar). Recibía también el nombre de "almete" o, si posee alas metálicas, de "sombrero de hierro"'),
            Item::armor('Capacete')->description('Un casco similar al bacinete, pero mucho más barato y ligero, pues está fabricado con cuero duro, lo que otorga una mínima protección en la cabeza. Aunque se puede combinar con cualquier tipo de armadura, no suele estar bien visto llevar capacete con armaduras metálicas o completas'),
            Item::armor('Celada')->description('Un casco de metal muy similar al yelmo, pero que deja libre la parte inferior de la cara (boca, barbilla y cuello), lo que aligera su peso y permite que se lleve con una mayor comodidad. Sólo puede combinarse con una coracina, una loriga o un arnés'),
            Item::armor('Gorro de Cuero')->description('Se trata básicamente de un sombrero fabricado con cuero que proporciona una ínfima protección en la cabeza. Al igual que ocurre con las ropas gruesas, el gorro se considera una prenda de vestir habitual, y no una armadura como tal. Se puede combinar con cualquier armadura blanda o ligera'),
            Item::armor('Yelmo')->description('Sin lugar a dudas, el único casco que otorga una protección completa a la cabeza es el yelmo, pues sus distintas partes y piezas (cimera, collar, babera y visera) recubren completamente el cráneo, la cara y el cuello del portador. Se solía diseñar muchas veces con una apariencia puntiaguda en la parte frontal e incluso con formas de dientes de sierra en su parte inferior, para aumentar la ferocidad del guerrero que lo portaba. A pesar de todo, el yelmo merma en gran medida la percepción de la persona que lo lleva, pues la visera le impide ver correctamente y los oídos quedan obstruidos por el metal que los rodea; de todas formas, es posible subir la visera, lo que reduce la penalización a las competencias de Percepción de -25% a -15%, aunque también disminuye la Protección de 8 a 7 puntos. El yelmo sólo puede combinarse con una coracina, una cota de placas, una loriga o un arnés, nunca con armaduras inferiores'),
        ])->toArray();
    }
}
