<?php

declare(strict_types=1);

namespace Database\Seeders\Commerce\Items;

use Aquelarre\Commerce\Domain\Dto\DBSeed\Items\Item;
use Database\Seeders\Contracts\DataProvider;

class PoisonSeeder extends DataProvider
{
    public function getData(): array
    {
        return collect([
            Item::poison('Acónito')->description('Planta de flores azules o violetas que crece junto a los manantiales y cursos de agua. Su ingestión es tremendamente tóxica, produciendo mareos, ojos llorosos, temblores y finalmente la muerte por fallo respiratorio y sanguíneo. A pesar de todo se trata de una planta con un sabor muy amargo, por lo que es fácil detectarla con una tirada de Degustar'),
            Item::poison('Adormidera')->description('Planta de flores rojas o blancas de la que se obtiene el opio. En dosis pequeñas provoca un ligero adormecimiento, pero con una dosis mayor —una onza, unos 30 gramos— al envenenado se le enturbia la visión, la cara adquiere un tono amarillento, los labios se tornan verdosos y las uñas se ennegrecen, hasta acabar muriendo lentamente por falta de oxígeno y con los miembros rígidos'),
            Item::poison('Albayalde')->description('Pigmento de color blanco fabricado con plomo deshecho en vinagre muy fuerte, y que es utilizado en pintura y en cosmética, donde recibe también el nombre de "blanco de plomo" o "cerusa". Si se ingiere, ya sea por error o de forma intencionada, la lengua y el paladar se tornan blancos y causa sequedad, dolores de estómago e hinchazón del vientre, hasta que poco a poco se van viendo afectadas las extremidades, que se vuelven frías, y por último alcanza los pulmones, que se detienen causando la muerte'),
            Item::poison('Arsénico')->description('Mineral que puede adquirir un tono blanco y transparente (denominado "rejalgar"), amarillo ("oropimente") o rojo ("sandáraca"). Si se administra con tino y conocimiento es considerado un buen medicamento pero, en la mayor parte de las ocasiones, se utiliza como veneno debido a su alta toxicidad, pues provoca en todo aquél que lo ingiere la muerte de forma tan rápida y fulminante que pocos son los que se dan cuenta de lo que ocurre'),
            Item::poison('Beleño')->description('Denominado también "hierba loca" o "beleño negro", es una planta muy común en toda Castilla, habitual en terraplenes, baldíos y zonas arenosas, de hojas grandes y flores ocres que despiden un olor desagradable. En pequeñas cantidades, el beleño provoca somnolencia, pero suministrado en dosis elevadas produce una gran debilidad, abscesos de pus en la lengua, abundante espuma en la boca, enturbiamiento de la visión, pérdida de oído y finalmente estado de inconsciencia previo a la muerte'),
            Item::poison('Cantáridas')->description('El polvo de cantáridas procede de unos pequeños insectos llamados abadejos que habitan en los brotes de los olivos, fresnos y sauces, todos ellos árboles de hojas tiernas. Para obtener el producto, los insectos deben recogerse antes de que salga el sol agitando los árboles en los que viven, se sumergen a continuación en vinagre hasta que estén secos y se los tritura para conseguir el polvo venenoso, que se debe guardar en un recipiente sellado para que no pierda sus propiedades. Es una sustancia afrodisiaca, siempre y cuando se tome en pequeñas cantidades, ya que si se consume una dosis elevada provoca inflamación del hígado, gran dolor al expulsar la orina, que aparece mezclada con sangre, y finalmente desmayos que terminan con la vida'),
            Item::poison('Cicuta')->description('Planta muy parecida al perejil y al hinojo, aunque de olor desagradable, que crece en lugares frescos y húmedos, como la orilla de los ríos. Posee flores blancas y semillas negruzcas de donde se obtiene un zumo extremadamente venenoso con un fuerte olor a orina. La cicuta, un veneno casi fulminante, provoca en el envenenado sollozos y un frío intenso en las extremidades que va subiendo hacia el pecho, provocando la muerte por asfixia al detener los pulmones'),
            Item::poison('Escorpión')->description('El veneno del escorpión, arácnido muy extendido en la Península, produce una gran inflamación en la zona afectada, alternándose periodos de calor con otros de frío, pero aparte de eso y un tremendo dolor en la zona afectada, no tiene otro efecto sobre el hombre'),
            Item::poison('Mandrágora')->description('La mandrágora —el vegetal, no la criatura irracional— es una planta de hojas dentadas que crece en zonas sombrías y húmedas donde no llega la luz del sol, con frutos parecidos a la manzana —aunque de olor fétido— y con una raíz que adopta extrañas formas, recordando muchas veces a un cuerpo humano. Precisamente, la raíz de mandrágora hervida en vino o masticada directamente provoca un profundo sueño en todo aquél que la consume'),
            Item::poison('Sardonia')->description('La "yerba sardonia" o "apio sardónico" es una planta de color verde brillante, con hojas dentadas y flores de color amarillo. Crece en lugares húmedos y arenosos, y de ella se obtiene un veneno tremendamente tóxico, que produce en todo aquél que la bebe espasmos en el cuerpo y en el rostro —que se contrae formando una sonrisa forzada— , matándole de forma lenta y dolorosa'),
            Item::poison('Setas Venenosas')->description('Es creencia común que sólo las setas de colores llamativos y olores desagradables son venenosas, pero nada más alejado de la realidad, pues muchas que nos parecen a simple vista inofensivas pueden ser terriblemente perjudiciales. Las más tóxicas son la "oronja verde", la "cicuta blanca" o el "cortinario de la montaña", que pueden acabar con aquél que las consuma en unos días tras sufrir una muerte agónica con vómitos, terribles dolores abdominales y una severa diarrea'),
            Item::poison('Vívora')->description('El veneno de víbora, serpiente muy común en los reinos peninsulares, especialmente en su variedad de víbora áspid, fue probablemente el más utilizado durante el Medievo, sobre todo mezclado como ponzoña en la comida de un rival. El infortunado que recibe el veneno de víbora irá palideciendo poco a poco, sufriendo pequeñas sangrías en las encías, inflamación del hígado, dolores en el vientre, vómitos, somnolencia y un frío extremo que poco a poco irá destruyendo sus fuerzas'),
            Item::poison('Zaragatona')->description('Llamada también "psilio", es una hierba parecida al heno con flores blancas que aparecen en forma de espigas. Si se consume en abundante cantidad —lo que le suele ocurrir más al ganado que a las personas—, produce graves dificultades respiratorias y problemas circulatorios que terminan matando al que lo toma'),
        ])->toArray();
    }
}
