<?php

declare(strict_types=1);

namespace Database\Seeders\Commerce\Items;

use Aquelarre\Commerce\Domain\Dto\DBSeed\Items\Item;
use Database\Seeders\Contracts\DataProvider;

class WeaponSeeder extends DataProvider
{
    public function getData(): array
    {
        return collect([
            Item::weapon('Alfanje')->muslim()->greatSword()->description('Se trata de la versión musulmana del montante, una espada de gran longitud con la hoja ancha, ligeramente curvada y de un solo filo. Su nombre procede del árabe aljanyar ("puñal")'),
            Item::weapon('Almarada')->muslim()->dagger()->description('Aunque fue concebida en principio como una herramienta de trabajo, se convirtió finalmente en un arma punzante con un filo de acero muy estrecho y la empuñadura de madera. No posee filo cortante, pues, de forma similar al estilete, se utiliza introduciéndola violentamente entre las junturas de la armadura del enemigo —se la denominaba "chupasangre" por las graves hemorragias internas que era capaz de provocar—, aunque es imposible lanzarla o usarla para parar un ataque'),
            Item::weapon('Arbalesta')->christian()->crossbow()->description('Es una versión pesada de la ballesta normal, más voluminosa y con las palas construidas siempre con acero, lo que otorgaba a las saetas una mayor capacidad de penetración y un alcance mayor, aunque debía usarse un cranequín —una maquina tensadora con ruedas dentadas— para recargarla'),
            Item::weapon('Archa')->christian()->axe()->description('Llamada también "guadaña de guerra", es un arma que mezcla la idea del hacha y de la lanza, pues se compone de una empuñadura de gran longitud —entre 1,5 y 2 varas– en cuyo extremo hay una hoja en forma de cimitarra o espada curva de una anchura cercana al pie, aunque para usarla es necesario utilizar ambas manos. Alcanzaron cierta relevancia en los ejércitos cristianos, que incluso llegaron a formar cuerpos de archeros en sus ejércitos'),
            Item::weapon('Arco Corto')->bow()->description('Dentro de su rareza, el arco corto es el más conocido en la Península Ibérica, un arco de tamaño medio (una vara, aproximadamente) utilizado principalmente por cazadores'),
            Item::weapon('Arco Largo')->bow()->description('Utilizados principalmente por soldados ingleses, que acostumbran a fabricarlos con madera de tejo, el arco largo es prácticamente desconocido en los reinos peninsulares. Si los personajes llegan a ver uno lo más probable es que esté en manos de algún mercenario de la Europa del Norte o de las Islas Británicas'),
            Item::weapon('Arco (Re)curvado')->bow()->description('De origen mongol, el arco recurvado se ha hecho un hueco en el ejército nazarí. Fabricado con huesos, madera y tendones de animales, posee una gran estabilidad, y aunque requiere el uso de ambas manos para su utilización, deja libres tres dedos de la mano que sujeta la flecha, que pueden usarse para manejar unas riendas, lo que permite su uso a caballo. A pesar de todo, requiere la misma fuerza para utilizarlo que el arco largo, su fabricación necesita una gran cantidad de tiempo y son muy susceptibles a los climas húmedos, lo que no propició su adopción en el norte de la Península o en Europa'),
            Item::weapon('Ballesta')->crossbow()->description('Se trata de la ballesta arquetípica, una versión en madera con las palas en metal que, en comparación con el arco, necesita más tiempo para ser recargada —requiere un estribo, una especie de torniquete a manivela—. Gracias a su facilidad de uso estuvo muy extendida en la Edad Media'),
            Item::weapon('Ballesta Ligera')->crossbow()->description('Una versión más reducida de la ballesta muy extendida en los estamentos nobiliarios, donde era usada en sus partidas de caza, y que llegó a tal grado de perfeccionamiento que a comienzos del siglo XV se podían fabricar desmontables o tan pequeñas que cabían perfectamente en la manga de un jubón. Para tensarlas, al contrario que las demás ballestas, sólo se usan las manos, lo que agiliza el proceso de recarga'),
            Item::weapon('Bastón de Combate')->staff()->description('Se trata de un arma que sólo puede encontrarse en aquellas zonas de Navarra y Aragón que se encuentran más cercanas al Pirineo, pues el bastón de combate es de procedencia francesa —allí lo llaman canne de combat—. No es más que un bastón de madera de aproximadamente una vara de longitud, característica ideal para pasar desapercibido, pues nadie creería que es posible utilizarlo de forma eficaz en combate'),
            Item::weapon('Bordón')->staff()->description('Palo de madera utilizado por los caminantes o peregrinos para ayudarse en su marcha. Suele tener una longitud de entre 1,7 y 2 varas, con un grosor inferior al del cayado y a menudo reforzado con metal en ambas extremidades. Aunque no se trata de su función principal, muchos son los caminantes que han perfeccionado su uso como arma ofensiva'),
            Item::weapon('Bracamante')->dagger()->description('Se trata de una evolución del cuchillo y la daga, pues el bracamante posee una hoja de media vara de longitud, ancha y con un solo filo, muy usada por la infantería de los reinos de Castilla y Aragón, por cazadores para despiezar las piezas cobradas o por marineros y piratas. No puede lanzarse debido a su peso'),
            Item::weapon('Cayado')->staff()->description('Es una vara gruesa de madera de una longitud entre 1,7 y 2 varas, a menudo con la parte superior curvada. Aunque puede usarse como arma improvisada, su labor principal es ayudar al pastor a prender y retener las reses que custodia'),
            Item::weapon('Clava')->mace()->description('La maza menos estilizada de todas, pues se trata poco más que de un garrote, una gruesa rama o un trozo de madera, al que a veces se le añaden de forma tosca clavos o filos cortantes en su extremo superior'),
            Item::weapon('Coltell')->christian()->dagger()->description('Una de las armas habituales en el equipo del almogávar: un cuchillo de hoja larga y ancha, ligeramente menor que el bracamante. Los almogávares acostumbraban a combinarlo con un escudo de metal, de madera o una rodela, y un par de azconas (lanzas cortas) para arrojarlas en combate. El coltell no está bien equilibrado y no puede ser usado como arma arrojadiza'),
            Item::weapon('Cuchillo')->dagger()->description('Bajo este epígrafe se recogen todos aquellos cuchillos utilizados principalmente como herramientas, ya sea para preparar la carne, despellejar a un animal, cortar pequeñas ramas o, en caso de necesidad, como arma improvisada'),
            Item::weapon('Dabus')->mace()->description('Una maza de madera sólida de una vara de longitud con refuerzos metálicos en su extremo, un arma muy utilizada por guardianes y porteros de casas adineradas o por los muccadin de las aljamas judías. Fue muy utilizada en los reinos peninsulares, especialmente en la zona dominada por los musulmanes'),
            Item::weapon('Daga')->dagger()->description('Arma usada por la nobleza como secundaria, pues sirve de complemento de la espada, o como arma personal de damas y mujeres. Posee doble filo y guarda para proteger el puño, y su longitud se encuentra entre un pie y media vara'),
            Item::weapon('Espada Corta')->sword()->description('Aunque similar al bracamante o al terciado, la espada corta es simplemente una espada de mano con una hoja recta muy reducida, de una longitud aproximada de media vara, y doble filo. Junto a la daga, la espada corta es, quizá, el arma secundaria más apreciada por nobles y damas'),
            Item::weapon('Espada de Mano')->sword()->description('El arma medieval por antonomasia, símbolo del caballero cristiano que era el único que tenía la potestad de portar una. Posee una hoja recta y de doble filo con una longitud que solía alcanzar la vara'),
            Item::weapon('Espada Bastarda')->greatSword()->description('Es una variante de la espada de mano, denominada también "espada de mano y media" pues, aunque mantiene su misma longitud, su empuñadura es más larga para permitir su manejo con dos manos, otorgándole una mayor fuerza. Por eso mismo, al tratarse de una fusión entre la espada y el espadón recibe el nombre de "bastarda". Por otro lado, aunque para usarla correctamente se requiere el uso de ambas manos, es posible usarla con una sola; en este caso, la Fuerza mínima del personaje aumentaría hasta 15'),
            Item::weapon('Estilete')->dagger()->description('Llamada también "misericordiosa" (ya que muchos caballeros la usaban para rematar a sus contrincantes en el campo de batalla), es un arma muy similar a la almarada, pues su filo es punzante y no cortante, aunque posee una longitud mucho menor que ésta, lo que la hace perfecta para ser ocultada, aunque no es posible lanzarla ni usarla para parar un ataque'),
            Item::weapon('Estoque')->sword()->description('Una variante de la espada con un filo mucho más estrecho y que se usa principalmente como arma de perforación, y no de corte20. Con el tiempo, el estoque evolucionaría hasta convertirse en la espada ropera del XVI y XVII'),
            Item::weapon('Gumía')->muslim()->dagger()->description('Daga de origen marroquí con la hoja curva y la empuñadura de hueso. Es utilizada por muchos asesinos, pues la gumía suele guardarse en una funda metálica con una curvatura más pronunciada que la hoja, que posee un cierre hermético, lo que permite conservar el arma empapada en veneno durante largos periodos de tiempo. No se puede usar como arma arrojadiza'),
            Item::weapon('Hacha')->axe()->description('Aunque no es más que una simple herramienta para cortar madera, en caso de necesidad puede ser utilizada como arma ofensiva, llegando a ser peligrosa en unas manos bien entrenadas en su uso. La longitud de su empuñadura no suele llegar a la media vara. Éstas son las únicas hachas que pueden usarse como armas arrojadizas'),
            Item::weapon('Hacha de Armas')->axe()->description('Llamada también "hacha de mano", es una variante del hacha normal, diseñada exclusivamente para la guerra y fabricada completamente en metal, con una longitud de aproximadamente 0,7 varas'),
            Item::weapon('Hacha de Combate')->axe()->description('La más devastadora de las armas medievales, aunque requiere el uso de dos manos para poder usarla en combate, y consta simplemente de un filo de hacha doble en el extremo de una empuñadura de madera con una longitud de una vara o superior'),
            Item::weapon('Hacha de Petos')->axe()->description('Una variante del hacha de armas con un mango de gran longitud —entre 1,5 y 1,8 varas—, por lo que requiere el uso de ambas manos; una hoja de hacha con un pico o martillo en el lado contrario y, en ocasiones, una punta de lanza en el extremo del asta. Fue usada principalmente en duelos, torneos y entrenamientos, por lo que solía ser una de las pocas hachas que podía llegar a dominar un noble o un caballero. Con el tiempo, el hacha de petos se transformó en la alabarda'),
            Item::weapon('Honda')->sling()->description('Aunque se fabrica con muy diversos materiales — cáñamo, cuero, etc.— y utiliza diferentes proyectiles —piedra, plomo, arcilla cocida…—, no hay grandes diferencias en el ámbito del juego entre las hondas que puedan encontrarse los jugadores'),
            Item::weapon('Horquilla')->spear()->description('Una variante militar de la horca usada por los campesinos para trasladar las mieses. Se trata de una lanza que termina en dos o tres puntas en forma de tridente y que requiere el uso de ambas manos para su manejo. No estuvo muy extendida entre los ejércitos peninsulares'),
            Item::weapon('Jineta Nashrí')->muslim()->sword()->description('Una espada de origen nazarí, utilizada en el reino de Granada. Se trata de una espada de poca longitud — entre 0,6 y 0,7 varas—, de hoja recta de doble filo, empuñadura de pomo redondo y guarda de hueso. La mayoría de las jinetas se fabricaban con materiales lujosos y exóticos, y era normal que su empuñadura estuviera recubierta de oro y piedras preciosas, lo que las convertía en un tipo de armamento de lujo que sólo podían permitirse grandes nobles nazaríes, por lo que era costumbre regalar una a embajadores de otros reinos'),
            Item::weapon('Lanza Corta')->spear()->description('Llamada también "chuzo", la lanza corta es la más pequeña de todas las lanzas, pues su longitud no acostumbraba a sobrepasar las 1,5 varas. Eso permite que, además de poder ser utilizada en combate cuerpo a cuerpo, pueda ser usada como arma arrojadiza, cuando recibía también el nombre de "dardo", "venablo" o "azcona"; aunque, al contrario que otras armas arrojadizas, el alcance de una lanza es mucho mayor: su distancia corta será igual al valor en Fuerza del atacante, la media será su Fuerza x2 y la larga su Fuerza x3'),
            Item::weapon('Lanza de Caballería')->spear()->description('La lanza más extendida durante el Medievo, ya fuera utilizada por unidades de infantería para enfrentarse a las cargas de la caballería o como el arma principal de muchos jinetes, que las usaban precisamente para cargar. Por todo ello, la lanza larga es un arma inútil en un combate singular hombre contra hombre, y sólo puede utilizarse por un guerrero a caballo para realizar la acción de ataque Carga a caballo o por un soldado a pie para llevar a cabo la acción defensiva Alancear. Por tanto, debe quedar claro que es imposible parar con ella cualquier ataque'),
            Item::weapon('Lanza Larga')->spear()->description('Una variante de la lanza corta, denominada también "lanzón", que posee una mayor longitud, entre 1,7 y 2 varas de altura, por lo que requiere el uso de ambas manos para ser utilizada en combate. Algunos tipos de lanzas largas, llamadas "podaderas" u "hocinos", poseen una punta saliente orientada hacia atrás que podía usarse para derribar a un jinete —véase la acción de ataque Descabalgar en la pág. 120—'),
            Item::weapon('Mangual')->mace()->description('Denominado en ocasiones "látigo de armas", el mangual se compone de un mango de madera de una longitud de media vara en cuyo extremo cuelga una cadena con una bola metálica con pinchos. Se trata de otra variante militar del mayal, que permitía además desarmar fácilmente al contrincante, al usar la cadena para atrapar el arma del contrario (el uso de la acción ofensiva Desarmar no requiere la división del porcentaje de la competencia por la mitad). Al igual que el arco largo, es un arma extremadamente rara en la Península, aunque fue muy utilizada en Centroeuropa'),
            Item::weapon('Martillo de Guerra')->mace()->description('Aunque no se trata más que de una variante militar de la herramienta, el martillo de guerra, llamado también "lucerna", podía convertirse en un arma muy eficaz en manos de un soldado entrenado en su manejo. La longitud del arma variaba entre media y una vara, y eran consideradas armas muy ligeras, hasta tal extremo que muchos guerreros las tenían como sus armas principales'),
            Item::weapon('Mayal de Armas')->mace()->description('El mayal es una herramienta campesina utilizada para desgranar cereales y consta de dos mangos de madera unidos por una cadena, uno de ellos de menor tamaño, que es el que se usa para golpear la mies. El mayal de armas es, por tanto, una variante militar de dicha herramienta con refuerzos metálicos y, en ocasiones, una cabeza de armas con pinchos para producir un mayor daño. Era un arma campesina utilizada principalmente por milicianos de baja extracción social y requiere el uso de ambas manos para su manejo'),
            Item::weapon('Maza')->mace()->description('Aunque se trata de una de las armas más antiguas conocidas por el hombre, en la época de Aquelarre la maza se fabrica completamente con hierro, plomo o incluso bronce, un cabezal de sección circular o poligonal y una longitud aproximada de 0,5-0,7 varas. A lo largo del Medievo irá evolucionando rápidamente hasta convertirse en la llamada "maza de armas", mucho más efectiva en combate, por lo que la maza normal prácticamente dejó de utilizarse'),
            Item::weapon('Maza de Armas')->mace()->description('Llamada también "maza barreteada", la maza de armas es una evolución de la maza a la que se le añaden unos apéndices de hierro o acero en el cabezal —llamados "cuchillas" o "aletas"—, dispuestos de tal forma que forman filos puntiagudos. Eran armas fáciles de fabricar y con muy bajo coste, lo que permitía armar a todo un ejército de manera barata'),
            Item::weapon('Maza Pesada')->mace()->description('Una variante de la maza de armas de mayor longitud y peso, causa un mayor nivel de daño cuando se utiliza, aunque requiere el uso de ambas manos para poder ser utilizada con propiedad'),
            Item::weapon('Montante')->greatSword()->description('Llamado en ocasiones "espada larga", el montante es el espadón por excelencia, una evolución de la espada que aumenta la longitud de su filo para poder enfrentarse a las nuevas armaduras que aparecen en el siglo XIV. Como todos los espadones, requiere el uso de dos manos para poder emplearse en combate'),
            Item::weapon('Morosa')->muslim()->spear()->description('Lanza larga de origen islámico cuyo extremo se duplica en dos astas metálicas afiladas, una mayor que la otra, y cuenta en la mitad del arma con unas anillas para introducir los dedos que le proporcionan mayor estabilidad a la sujeción. Al igual que la lanza larga, sólo puede ser usada por un jinete que cargue a caballo o por un soldado que use la acción de Alancear, pero en caso de que el arma quede ensartada en el cuerpo de nuestro enemigo, se supone que ambas astas han quedado hincadas en su interior, provocándole de forma automática un daño de 3D6, en lugar de los 2D6 habituales en las lanzas largas'),
            Item::weapon('Nimcha')->muslim()->sword()->description('Una variante del saif, la nimcha es una cimitarra de origen magrebí con una mayor curvatura en su hoja y que cuenta con un entrante en la empuñadura que permite alojar en él el dedo meñique, facilitando su agarre. Por tanto, si se usa para realizar una acción de parada y las reglas indican que perdemos el arma, la nimcha sólo caerá de nuestras manos si fallamos una tirada de FUEx5'),
            Item::weapon('Pico de Cuervo')->axe()->description('Más que un hacha, esta arma es una especie de variante militar de un martillo, pues, en lugar de filo cortante, posee un pico extremadamente aguzado y largo que puede alcanzar una longitud de hasta un pie'),
            Item::weapon('Saif')->muslim()->sword()->description('Llamada "cimitarra" por los cristianos, el saif es el equivalente musulmán de la espada, con una hoja ligeramente curva y de un solo filo. Las más famosas eran las fabricadas con acero de Damasco y al igual que ocurre con la espada cristiana, el saif es un símbolo de Allah y, por tanto, sólo era portada por aquellos que hubieran sido bendecidos por Él (o sea, los nobles)'),
            Item::weapon('Takuba')->muslim()->sword()->description('También de origen islámico, la takuba es una espada de hoja recta de doble filo utilizada por los tuaregs del Sahara , aunque posee una hoja mucho más ancha que la jineta nashrí, y suele estar adornada con varias acanaladuras e inscripciones con motivos geométricos, por lo que es fácil de distinguir'),
            Item::weapon('Telek')->muslim()->dagger()->description('Un puñal muy delgado y afilado, de origen islámico, utilizado por los tuaregs junto con su espada, la takuba. Acostumbran a llevarlo envainado en una funda que cuelga de la muñeca y está especialmente diseñado para abrazar al enemigo en combate y apuñalarlo por la espalda, por lo que si es usado en un ataque de melé, añade un bonificador de +10% a las tiradas de ataque'),
            Item::weapon('Terciado')->muslim()->dagger()->description('Se trata de una versión musulmana del bracamante, de filo igualmente ancho pero ligeramente curvo, y al igual que éste, no se puede usar para ser lanzado'),
            Item::weapon('Tripa')->mace()->description('Un arma muy rústica y primitiva, y por tanto muy extendida entre la población campesina. Se trata de un saco de cuero lleno de arena o piedras que se sujeta con una tira del mismo material, ya que para usarla se volteaba de forma similar a las hondas y se hacía caer sobre el enemigo (lo que además impide que pueda usarse para parar un ataque). Estuvo muy extendida por las zonas montañosas de la Península, especialmente en las tierras meridionales de Castilla, Navarra y Aragón'),
        ])->toArray();
    }
}
