<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Spells\Spell\Application;

use App\Game\Core\Features\Spells\Spell\Application\Pages\ListSpells;
use App\Game\Core\Features\Spells\Spell\Application\Pages\ViewSpell;
use App\Game\Core\Features\Spells\Spell\Application\Schemas\SpellInfolist;
use App\Game\Core\Features\Spells\Spell\Application\Tables\SpellTable;
use App\Game\Core\Features\Spells\Spell\Infrastructure\Models\Spell;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class SpellResource extends Resource
{
    protected static ?string $model = Spell::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function infolist(Schema $schema): Schema
    {
        return SpellInfolist::admin($schema);
    }

    public static function table(Table $table): Table
    {
        return SpellTable::admin($table);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListSpells::route('/'),
            'view' => ViewSpell::route('/{record}')
        ];
    }
}
