<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Skills\Application;

use App\Game\Core\Features\Skills\Application\Pages\ListSkills;
use App\Game\Core\Features\Skills\Application\Pages\ViewSkill;
use App\Game\Core\Features\Skills\Application\Schemas\SkillInfolist;
use App\Game\Core\Features\Skills\Application\Tables\SkillTable;
use App\Game\Core\Features\Skills\Infrastructure\Models\Skill;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class SkillResource extends Resource
{
    protected static ?string $model = Skill::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return SkillTable::admin($table);
    }

    public static function infolist(Schema $schema): Schema
    {
        return SkillInfolist::admin($schema);
    }

    public static function getPages(): array
    {
        return [
             'index' => ListSkills::route('/'),
             'view' => ViewSkill::route('/{record}'),
        ];
    }
}
