<?php

declare(strict_types=1);

namespace App\Game\Core\Features\Professions\Application;

use App\Game\Core\Features\Professions\Application\Pages\ListProfessions;
use App\Game\Core\Features\Professions\Application\Pages\ViewProfession;
use App\Game\Core\Features\Professions\Application\Schemas\ProfessionInfolist;
use App\Game\Core\Features\Professions\Application\Tables\ProfessionsTable;
use App\Game\Core\Features\Professions\Infrastructure\Models\Profession;
use App\Shared\Filament\Navigation\NavigationGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use UnitEnum;

class ProfessionResource extends Resource
{
    protected static ?string $model = Profession::class;

    protected static string | UnitEnum | null $navigationGroup = NavigationGroup::CORE;

    public static function form(Schema $schema): Schema
    {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }

    public static function infolist(Schema $schema): Schema
    {
        return ProfessionInfolist::admin($schema); // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return ProfessionsTable::admin($table); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => ListProfessions::route('/'),
            'view' => ViewProfession::route('/{record}'),
        ];
    }
}
